'use strict';
class BreadthService{
  constructor({universe,store,calculator,enabled=true,intervalMs=10000,maxAgeMs=30000,now=Date.now,logger={warn(){}}}={}){Object.assign(this,{universe,store,calculator,enabled,intervalMs,maxAgeMs,now,logger});this.running=false;this.calculating=false;this.timer=null;this.latest=null;this.latestContext=null;this.stats={calculations:0,successfulCalculations:0,failedCalculations:0,overlapPrevented:0,enrichmentsAttempted:0,enrichmentsAttached:0,enrichmentsUnavailable:0,enrichmentsStale:0,lastFailure:null}}
  async start(){if(!this.enabled||this.running)return;this.running=true;await this.calculate();this.schedule()}
  schedule(){clearTimeout(this.timer);if(this.running)this.timer=setTimeout(async()=>{await this.calculate();this.schedule()},this.intervalMs);this.timer?.unref?.()}
  async calculate(){if(this.calculating){this.stats.overlapPrevented++;return this.latest}this.calculating=true;this.stats.calculations++;try{const result=await this.calculator.calculate(this.universe.getSnapshot(),this.store);this.latest=result.snapshot;this.latestContext=result.context;this.stats.successfulCalculations++;this.stats.lastFailure=null;return this.latest}catch(error){this.stats.failedCalculations++;this.stats.lastFailure=error.message;this.logger.warn('radar_breadth_failed',{message:error.message});return this.latest}finally{this.calculating=false}}
  getLatest(){return this.latest}
  getLatestContext(){return this.latestContext}
  getForEnrichment(){this.stats.enrichmentsAttempted++;if(!this.latestContext){this.stats.enrichmentsUnavailable++;return null}if(this.now()-this.latestContext.calculatedAt>this.maxAgeMs){this.stats.enrichmentsStale++;return{...this.latestContext,breadth:{...this.latestContext.breadth,dataQuality:'STALE'},freshness:'STALE'}}this.stats.enrichmentsAttached++;return this.latestContext}
  diagnostics(){const snapshot=this.latest,age=snapshot?Math.max(0,this.now()-snapshot.calculatedAt):null;return{enabled:this.enabled,running:this.running,snapshotVersion:this.calculator.schemaVersion,contextVersion:this.calculator.contextVersion,timeframe:this.calculator.timeframe,calculationCadenceMs:this.intervalMs,maxAgeMs:this.maxAgeMs,...this.stats,latestSnapshotId:snapshot?.snapshotId||null,latestCalculatedAt:snapshot?.calculatedAt||null,latestAgeMs:age,expectedMarkets:snapshot?.coverage.expectedMarkets||0,usableMarkets:snapshot?.coverage.usableMarkets||0,expectedAssets:snapshot?.coverage.expectedAssets||0,usableAssets:snapshot?.coverage.usableAssets||0,marketCoverage:snapshot?.coverage.marketCoverage||0,assetCoverage:snapshot?.coverage.assetCoverage||0,assetsUp:snapshot?.assetsUp||0,assetsDown:snapshot?.assetsDown||0,assetsFlat:snapshot?.assetsFlat||0,marketsUp:snapshot?.marketsUp||0,marketsDown:snapshot?.marketsDown||0,marketsFlat:snapshot?.marketsFlat||0,excluded:snapshot?.coverage.excluded||{},dataQuality:snapshot?.dataQuality||'UNAVAILABLE',latestContextId:this.latestContext?.contextId||null}}
  async stop(){this.running=false;clearTimeout(this.timer);this.timer=null;while(this.calculating)await new Promise(resolve=>setTimeout(resolve,1))}
}
module.exports={BreadthService};
