'use strict';
const crypto=require('node:crypto');
const {MARKET_TYPES,marketId}=require('./market-identity.js');
const SCHEMA_VERSION=1,EXCHANGES=Object.freeze(['binance','bybit','okx','bingx']),DATA_QUALITY=Object.freeze(['COMPLETE','PARTIAL','WARMING_UP','STALE','DEGRADED']);
const safe=value=>typeof value==='string'&&/^[A-Za-z0-9:_-]{1,120}$/.test(value),timestamp=value=>Number.isFinite(Number(value))&&Number(value)>0,timeframe=value=>value==null||/^(1|3|5|15|30)m$|^(1|2|4|6|8|12)h$|^1d$|^1w$|^1M$/.test(value);
function validateMarket(market){const errors=[];if(!market||typeof market!=='object')return['market is required'];if(!EXCHANGES.includes(market.exchange))errors.push('invalid exchange');if(!MARKET_TYPES.includes(market.marketType))errors.push('marketType is required');if(!safe(market.symbol)||!safe(market.baseAsset)||!safe(market.quoteAsset))errors.push('invalid market identity');if(!safe(market.marketId)||market.marketId!==marketId(market))errors.push('invalid marketId');return errors}
function validateCommon(event,{unified=false}={}){const errors=[];if(!event||typeof event!=='object')return{valid:false,errors:['event is required']};if(event.schemaVersion!==SCHEMA_VERSION)errors.push('unsupported schemaVersion');if(!safe(event.detectorId)||!safe(event.detectorVersion))errors.push('detector identity is required');if(!safe(event.eventType))errors.push('eventType is required');errors.push(...validateMarket(event.market));if(!timeframe(event.timeframe))errors.push('invalid timeframe');for(const key of ['eventTimestamp','observedAt','createdAt'])if(!timestamp(event[key]))errors.push(`invalid ${key}`);if(unified&&!safe(event.eventId))errors.push('eventId is required');return{valid:errors.length===0,errors}}
const validateCandidateEvent=event=>{const result=validateCommon(event);if(!safe(event?.candidateId)){result.errors.push('candidateId is required');result.valid=false}return result};
function validateUnifiedEvent(event){const result=validateCommon(event,{unified:true});if(event?.deepLink){const link=event.deepLink,errors=[];if(!EXCHANGES.includes(link.exchange)||!MARKET_TYPES.includes(link.marketType)||!safe(link.symbol)||!safe(link.marketId)||link.marketId!==marketId(link))errors.push('invalid market identity');if(!timeframe(link.timeframe))errors.push('invalid timeframe');if(link.eventTimestamp!=null&&!timestamp(link.eventTimestamp))errors.push('invalid eventTimestamp');result.errors.push(...errors.map(value=>`deepLink ${value}`));result.valid=result.errors.length===0}return result}
function assertValid(event,validator,label){const result=validator(event);if(!result.valid){const error=new Error(`${label}: ${result.errors.join(', ')}`);error.code='INVALID_EVENT';error.validationErrors=result.errors;throw error}return event}
const createCandidateEvent=(value,{id=crypto.randomUUID(),now=Date.now()}={})=>assertValid({schemaVersion:SCHEMA_VERSION,candidateId:id,metrics:{},evidence:[],confirmationFactors:[],metadata:{warmupStatus:null,dataQuality:null,sourceCoverage:null},createdAt:now,...value},validateCandidateEvent,'Invalid CandidateEvent');
const createUnifiedEvent=(value,{id=crypto.randomUUID(),now=Date.now()}={})=>assertValid({schemaVersion:SCHEMA_VERSION,eventId:id,metrics:{},eligibility:{liquidityTier:null,universePreset:null,universePolicyVersion:null},marketContext:{regime:null,breadth:null,btcState:null,ethState:null},score:{value:null,modelVersion:null,factors:[]},confirmationFactors:[],humanReadable:{label:null,explanationCodes:[]},microChart:null,createdAt:now,...value},validateUnifiedEvent,'Invalid UnifiedEvent');
module.exports={SCHEMA_VERSION,EXCHANGES,DATA_QUALITY,validateMarket,validateCandidateEvent,validateUnifiedEvent,createCandidateEvent,createUnifiedEvent};
