'use strict';
const freeze=value=>{if(value&&typeof value==='object'&&!Object.isFrozen(value)){Object.values(value).forEach(freeze);Object.freeze(value)}return value};
class InterpretationPolicy{
  constructor({version='interpretation-v1'}={}){this.version=version;this.stats={evaluations:0,failures:0,countsByCode:{}}}
  evaluate({setupType,direction,score,marketContext}){this.stats.evaluations++;try{let code,label,summary;if(setupType==='MOMENTUM_WITH_VOLUME_CONFIRMATION'){if(direction==='DOWN'){code='DOWNSIDE_MOMENTUM_VOLUME_CONFIRMATION';label='Downside Momentum + Volume Confirmation';summary='Downside momentum is confirmed by elevated trading volume.'}else{code='MOMENTUM_VOLUME_CONFIRMATION';label='Momentum + Volume Confirmation';summary='Strong upside momentum with abnormal volume.'}}else if(setupType==='VOLUME_EXPANSION'){code='UNUSUAL_VOLUME_ACTIVITY';label='Unusual Volume Activity';summary='Unusual volume activity was detected without clear directional momentum.'}else if(direction==='DOWN'){code='DOWNSIDE_MOMENTUM_EXPANSION';label='Downside Momentum Expansion';summary='A strong downside price movement stands out from recent behavior.'}else{code='MOMENTUM_EXPANSION';label='Momentum Expansion';summary='A strong upside price movement stands out from recent behavior.'}const quality=marketContext?.breadth?.dataQuality;if(direction!=='NONE'&&quality==='COMPLETE')summary+=this.aligned(direction,marketContext)?' Market context broadly supports the event direction.':'';else if(quality==='PARTIAL')summary+=' Market context is partial, so ranking relies mainly on local market evidence.';const result=freeze({version:this.version,code,label,summary,quality:score.quality,reasons:[...score.factors]});this.stats.countsByCode[code]=(this.stats.countsByCode[code]||0)+1;return result}catch(error){this.stats.failures++;throw error}}
  aligned(direction,context){const target=direction==='UP'?'UP':'DOWN',pct=Number(direction==='UP'?context.breadth.pctAssetsUp:context.breadth.pctAssetsDown);return pct>=50||context.btc?.direction===target||context.eth?.direction===target}
  diagnostics(){return{version:this.version,evaluations:this.stats.evaluations,failures:this.stats.failures,countsByCode:{...this.stats.countsByCode}}}
}
module.exports={InterpretationPolicy};
