'use strict';
const healthy=candidate=>candidate?.metadata?.dataQuality==='COMPLETE';
const latest=(rows,id)=>rows.filter(item=>item.detectorId===id).sort((a,b)=>b.eventTimestamp-a.eventTimestamp)[0]||null;
class QualificationPolicy{
  constructor({version='qualification-v1',windowMs=90000,momentumMinZScore=4,volumeMinRelativeVolume=3,volumeMinZScore=4}={}){Object.assign(this,{version,windowMs,momentumMinZScore,volumeMinRelativeVolume,volumeMinZScore})}
  evaluate({candidate,relatedCandidates=[]}){if(!healthy(candidate))return this.result(false,{reasonCodes:['UNHEALTHY_SOURCE_DATA'],sources:[candidate]});const related=relatedCandidates.filter(item=>item.market.marketId===candidate.market.marketId&&item.timeframe===candidate.timeframe&&Math.abs(item.eventTimestamp-candidate.eventTimestamp)<=this.windowMs),usable=[candidate,...related].filter(healthy),momentum=latest(usable,'price-momentum'),volume=latest(usable,'volume-anomaly');if(momentum&&volume){const sources=[momentum,volume];return this.result(true,{setupType:'MOMENTUM_WITH_VOLUME_CONFIRMATION',direction:this.direction(momentum),reasonCodes:['MOMENTUM_VOLUME_CONFIRMED','RELATED_CONFIRMATION_FOUND'],confirmationFactors:['PRICE_MOMENTUM','VOLUME_ANOMALY','SAME_TIMEFRAME_CONFIRMATION'],sources,metrics:this.metrics(momentum,volume)})}if(momentum&&Math.abs(Number(momentum.metrics.deviationZScore))>=this.momentumMinZScore)return this.result(true,{setupType:'MOMENTUM',direction:this.direction(momentum),reasonCodes:['MOMENTUM_STANDALONE_STRONG'],confirmationFactors:['PRICE_MOMENTUM'],sources:[momentum],metrics:this.metrics(momentum,null)});if(volume&&Number(volume.metrics.relativeVolume)>=this.volumeMinRelativeVolume&&Number(volume.metrics.deviationZScore)>=this.volumeMinZScore)return this.result(true,{setupType:'VOLUME_EXPANSION',direction:'NONE',reasonCodes:['VOLUME_STANDALONE_EXTREME'],confirmationFactors:['VOLUME_ANOMALY'],sources:[volume],metrics:this.metrics(null,volume)});return this.result(false,{reasonCodes:['INSUFFICIENT_STANDALONE_STRENGTH'],sources:[candidate]})}
  direction(momentum){return momentum.eventType==='PRICE_MOMENTUM_UP'?'UP':momentum.eventType==='PRICE_MOMENTUM_DOWN'?'DOWN':'NONE'}
  metrics(momentum,volume){return{price:momentum?.metrics?.price??volume?.metrics?.price??null,priceChangePct:momentum?.metrics?.priceChangePct??null,momentumDeviationZScore:momentum?.metrics?.deviationZScore??null,volume:volume?.metrics?.volume??null,relativeVolume:volume?.metrics?.relativeVolume??null,volumeDeviationZScore:volume?.metrics?.deviationZScore??null}}
  result(qualified,{setupType=null,direction='NONE',reasonCodes=[],confirmationFactors=[],sources=[],metrics={}}){return{qualified,setupType,direction,reasonCodes,confirmationFactors,sourceCandidateIds:sources.map(item=>item.candidateId),policyVersion:this.version,metrics,metadata:{sourceCandidates:sources.map(item=>({candidateId:item.candidateId,detectorId:item.detectorId,detectorVersion:item.detectorVersion,eventTimestamp:item.eventTimestamp}))},sources}}
}
module.exports={QualificationPolicy};
