'use strict';
const freeze=value=>{if(value&&typeof value==='object'&&!Object.isFrozen(value)){Object.values(value).forEach(freeze);Object.freeze(value)}return value};
const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
const numeric=value=>value!=null&&value!==''&&Number.isFinite(Number(value));
const band=value=>value>=90?'EXCEPTIONAL':value>=80?'STRONG':value>=70?'GOOD':value>=60?'MODERATE':'LOW';
class ScorePolicy{
  constructor({enabled=true,modelVersion='zych-score-v1',caps={momentum:30,volume:25,confirmation:20,context:15,dataQuality:10},momentumFullZ=6,volumeFullRelative=4,volumeFullZ=6,now=Date.now}={}){Object.assign(this,{enabled,modelVersion,caps,momentumFullZ,volumeFullRelative,volumeFullZ,now});this.stats={evaluations:0,successes:0,failures:0,lastScoredAt:null,totalScore:0,minScore:null,maxScore:null,qualityBands:{EXCEPTIONAL:0,STRONG:0,GOOD:0,MODERATE:0,LOW:0},missingFactors:{momentum:0,volume:0,context:0,partialContext:0,staleContext:0}}}
  evaluate({setupType,direction,metrics={},confirmationFactors=[],marketContext=null,sourceCandidates=[]}={}){this.stats.evaluations++;try{const factors=[],penalties=[],missingFactors=[],momentum=this.momentum(metrics),volume=this.volume(metrics),confirmation=this.confirmation(setupType,confirmationFactors),context=this.context(direction,marketContext),quality=this.dataQuality(sourceCandidates);for(const factor of [momentum,volume,confirmation,context,quality]){factors.push(factor);if(!factor.available)missingFactors.push(factor.code)}if(!momentum.available)this.stats.missingFactors.momentum++;if(!volume.available)this.stats.missingFactors.volume++;if(!marketContext){this.stats.missingFactors.context++}else if(context.contextQuality==='PARTIAL')this.stats.missingFactors.partialContext++;else if(context.contextQuality==='STALE')this.stats.missingFactors.staleContext++;const value=Math.round(clamp(factors.reduce((sum,item)=>sum+item.contribution,0),0,100)),qualityBand=band(value),calculatedAt=this.now(),result=freeze({modelVersion:this.modelVersion,value,quality:qualityBand,factors,penalties,missingFactors,contextQuality:context.contextQuality,calculatedAt,disclaimerCode:'RANKING_QUALITY_NOT_PROBABILITY'});this.stats.successes++;this.stats.lastScoredAt=calculatedAt;this.stats.totalScore+=value;this.stats.minScore=this.stats.minScore==null?value:Math.min(this.stats.minScore,value);this.stats.maxScore=this.stats.maxScore==null?value:Math.max(this.stats.maxScore,value);this.stats.qualityBands[qualityBand]++;return result}catch(error){this.stats.failures++;throw error}}
  momentum(metrics){const raw=metrics.momentumDeviationZScore;if(!numeric(raw))return this.factor('MOMENTUM_STRENGTH',0,this.caps.momentum,false,'MISSING');const value=Number(raw);return this.factor('MOMENTUM_STRENGTH',this.caps.momentum*clamp(Math.abs(value)/this.momentumFullZ,0,1),this.caps.momentum,true,'AVAILABLE')}
  volume(metrics){const relativeRaw=metrics.relativeVolume,zRaw=metrics.volumeDeviationZScore;if(!numeric(relativeRaw)||!numeric(zRaw))return this.factor('VOLUME_STRENGTH',0,this.caps.volume,false,'MISSING');const relative=Number(relativeRaw),z=Number(zRaw),relativeCap=this.caps.volume*.48,zCap=this.caps.volume-relativeCap,contribution=relativeCap*clamp(relative/this.volumeFullRelative,0,1)+zCap*clamp(z/this.volumeFullZ,0,1);return this.factor('VOLUME_STRENGTH',contribution,this.caps.volume,true,'AVAILABLE')}
  confirmation(setupType,factors){let contribution=0,code='NO_CONFIRMATION';if(setupType==='MOMENTUM_WITH_VOLUME_CONFIRMATION'&&factors.includes('PRICE_MOMENTUM')&&factors.includes('VOLUME_ANOMALY')){contribution=this.caps.confirmation;code='MULTI_DETECTOR_CONFIRMATION'}else if(setupType==='MOMENTUM'){contribution=this.caps.confirmation*.6;code='MOMENTUM_ONLY'}else if(setupType==='VOLUME_EXPANSION'){contribution=this.caps.confirmation*.5;code='VOLUME_ONLY'}return this.factor(code,contribution,this.caps.confirmation,contribution>0,contribution>0?'AVAILABLE':'MISSING')}
  context(direction,context){const quality=context?.breadth?.dataQuality||'UNAVAILABLE';if(!context||quality==='STALE'||quality==='UNAVAILABLE'||direction==='NONE')return{...this.factor('MARKET_CONTEXT_ALIGNMENT',0,this.caps.context,false,quality),contextQuality:quality};const target=direction==='UP'?'UP':'DOWN',breadthPct=Number(direction==='UP'?context.breadth.pctAssetsUp:context.breadth.pctAssetsDown),scale=quality==='COMPLETE'?1:quality==='PARTIAL'?.5:0;let contribution=(Number.isFinite(breadthPct)?this.caps.context*.4667*clamp(breadthPct/100,0,1):0);if(context.btc?.direction===target)contribution+=this.caps.context*.26665;if(context.eth?.direction===target)contribution+=this.caps.context*.26665;return{...this.factor('MARKET_CONTEXT_ALIGNMENT',contribution*scale,this.caps.context,scale>0,quality),contextQuality:quality}}
  dataQuality(sources){const complete=sources.length>0&&sources.every(item=>item.metadata?.dataQuality==='COMPLETE');return this.factor('SOURCE_DATA_QUALITY',complete?this.caps.dataQuality:0,this.caps.dataQuality,complete,complete?'COMPLETE':'UNHEALTHY_OR_MISSING')}
  factor(code,contribution,maxContribution,available,evidenceQuality){return freeze({code,contribution:Math.round(contribution*1000)/1000,maxContribution,available,evidenceQuality})}
  publicResult(result){return freeze({modelVersion:result.modelVersion,value:result.value,quality:result.quality,factors:result.factors.filter(item=>item.available&&item.contribution>0).map(item=>item.code),missingFactors:[...result.missingFactors],disclaimerCode:result.disclaimerCode})}
  diagnostics(){return{enabled:this.enabled,modelVersion:this.modelVersion,evaluations:this.stats.evaluations,successes:this.stats.successes,failures:this.stats.failures,lastScoredAt:this.stats.lastScoredAt,qualityBands:{...this.stats.qualityBands},averageScore:this.stats.successes?this.stats.totalScore/this.stats.successes:0,minScore:this.stats.minScore,maxScore:this.stats.maxScore,missingFactors:{...this.stats.missingFactors}}}
}
module.exports={ScorePolicy,band,clamp};
