/* ZYCH Markets browser bundle. Keeps direct file:// and HTTP startup equivalent. */
(() => {
  'use strict';

  const DEFAULT_WATCHLIST = ['BTC','ETH','SOL','BNB','XRP','ADA','DOGE'];
  const QUOTE_PRIORITY = ['USDT', 'USDC', 'FDUSD', 'BTC', 'ETH'];
  const POPULAR_ASSETS = ['BTC','ETH','BNB','SOL','XRP','ADA','DOGE','TRX','LINK','AVAX','SUI','DOT','LTC','BCH','UNI','NEAR','AAVE','PEPE','ARB'];
  const STORAGE_KEY = 'zych.watchlist.v1';
  const FAVORITE_HINT_KEY = 'zych.favorite-hint.v1';
  const WORKSPACE_KEY = 'zych.exchange-workspace.v1';
  const ASSETS = {
    BTC:{name:'Bitcoin',icon:'₿',className:'btc'},ETH:{name:'Ethereum',icon:'◆',className:'eth'},SOL:{name:'Solana',icon:'S',className:'sol'},
    BNB:{name:'BNB',icon:'◆',className:'bnb'},XRP:{name:'XRP',icon:'X',className:'xrp'},ADA:{name:'Cardano',icon:'A',className:'ada'},DOGE:{name:'Dogecoin',icon:'Ð',className:'doge'},
    LINK:{name:'Chainlink',icon:'L',className:'generic'},SUI:{name:'Sui',icon:'S',className:'generic'},ARB:{name:'Arbitrum',icon:'A',className:'generic'},PEPE:{name:'Pepe',icon:'P',className:'generic'},AVAX:{name:'Avalanche',icon:'A',className:'generic'},TRX:{name:'TRON',icon:'T',className:'generic'},
    DOT:{name:'Polkadot',icon:'D',className:'generic'},LTC:{name:'Litecoin',icon:'Ł',className:'generic'},BCH:{name:'Bitcoin Cash',icon:'B',className:'generic'},TON:{name:'Toncoin',icon:'T',className:'generic'},SHIB:{name:'Shiba Inu',icon:'S',className:'generic'},UNI:{name:'Uniswap',icon:'U',className:'generic'},NEAR:{name:'NEAR Protocol',icon:'N',className:'generic'},APT:{name:'Aptos',icon:'A',className:'generic'}
  };
  let MARKETS = DEFAULT_WATCHLIST.flatMap(asset => ['binance','bybit'].map(exchange => ({id:`${exchange}:${asset}USDT`,marketId:`${exchange}:${asset}USDT`,asset,symbol:`${asset}USDT`,baseAsset:asset,quoteAsset:'USDT',exchange,enabled:true,status:'TRADING'}))).concat(DEFAULT_WATCHLIST.map(asset=>({id:`okx:${asset}-USDT`,marketId:`okx:${asset}-USDT`,asset,symbol:`${asset}-USDT`,baseAsset:asset,quoteAsset:'USDT',exchange:'okx',enabled:true,status:'live'})));
  const FUTURE_MARKETS = [
    {id:'coinbase:BTCUSD',asset:'BTC',symbol:'BTCUSD',baseAsset:'BTC',quoteAsset:'USD',exchange:'coinbase',enabled:false}
  ];
  const EXCHANGES={binance:{label:'Binance'},bybit:{label:'Bybit'},okx:{label:'OKX'},coinbase:{label:'Coinbase'}};
  const TIMEFRAMES=['1m','5m','15m','30m','1h','4h','1d','1w','1M'];
  let assetIndex=new Map(),universeStatus='loading',catalogLiquidity=new Map(),catalogSnapshots=new Map();
  function rebuildAssetIndex(){assetIndex=new Map();MARKETS.forEach(market=>{if(!assetIndex.has(market.asset))assetIndex.set(market.asset,[]);assetIndex.get(market.asset).push(market)});assetIndex.forEach(markets=>markets.sort((a,b)=>QUOTE_PRIORITY.indexOf(a.quoteAsset)-QUOTE_PRIORITY.indexOf(b.quoteAsset)))}
  rebuildAssetIndex();
  const marketForAssetOnExchange=(asset,exchange,quoteAsset='USDT')=>ZychWorkspace.marketForAsset(assetIndex.get(asset)||[],asset,exchange,quoteAsset);
  const marketsForAsset=asset=>[...(assetIndex.get(asset)||[]),...FUTURE_MARKETS.filter(market=>market.asset===asset)];
  const marketLabel=market=>`${market.baseAsset} / ${market.quoteAsset}`;
  const formatPrice=value=>{const number=Number(value);if(!Number.isFinite(number))return'—';const digits=number>=1?2:number>=.1?4:number>=.01?5:number>=.001?6:8;return number.toLocaleString('en-US',{minimumFractionDigits:digits,maximumFractionDigits:digits})};
  const formatPercent=value=>{const number=Number(value);return Number.isFinite(number)?`${number>=0?'+':'−'}${Math.abs(number).toFixed(2)}%`:'—'};
  const formatCompact=value=>Number.isFinite(Number(value))?new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:2}).format(Number(value)):'—';
  const escapeHtml=value=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const applyDirection=(element,value)=>{element.classList.remove('positive','negative');if(Number.isFinite(Number(value)))element.classList.add(Number(value)>=0?'positive':'negative')};
  const assetMeta=asset=>ASSETS[asset]||{name:asset,icon:asset.slice(0,1),className:'generic'};
  const iconMarkup=(meta,size='tiny')=>`<i class="coin-icon ${escapeHtml(meta.className)} ${escapeHtml(size)}">${escapeHtml(meta.icon)}</i>`;
  function storedWatchlist(exchange){try{const value=JSON.parse(localStorage.getItem(STORAGE_KEY));return ZychWatchlist.migrate(Array.isArray(value)?value:null,{markets:MARKETS,exchange,defaults:DEFAULT_WATCHLIST})}catch{return ZychWatchlist.migrate(null,{markets:MARKETS,exchange,defaults:DEFAULT_WATCHLIST})}}
  function saveWatchlist(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state.watchlist))}catch{}}
  function hasStoredWatchlist(){try{return localStorage.getItem(STORAGE_KEY)!==null}catch{return false}}
  function favoriteHintSeen(){try{return localStorage.getItem(FAVORITE_HINT_KEY)==='seen'}catch{return true}}
  function dismissFavoriteHint(){try{localStorage.setItem(FAVORITE_HINT_KEY,'seen')}catch{}}
  function storedWorkspace(){try{const value=JSON.parse(localStorage.getItem(WORKSPACE_KEY)||'{}');return{exchange:ZychWorkspace.validExchange(value.exchange),marketId:typeof value.marketId==='string'?value.marketId:'',asset:typeof value.asset==='string'&&value.asset?value.asset:'BTC',quoteAsset:typeof value.quoteAsset==='string'&&value.quoteAsset?value.quoteAsset:'USDT',timeframe:TIMEFRAMES.includes(value.timeframe)?value.timeframe:'1h'}}catch{return{exchange:'binance',marketId:'',asset:'BTC',quoteAsset:'USDT',timeframe:'1h'}}}
  const workspacePreference=storedWorkspace(),initialMarket=MARKETS.find(market=>market.id===workspacePreference.marketId&&market.exchange===workspacePreference.exchange)||marketForAssetOnExchange(workspacePreference.asset,workspacePreference.exchange,workspacePreference.quoteAsset)||ZychWorkspace.unavailableMarket(workspacePreference.asset,workspacePreference.exchange,workspacePreference.quoteAsset);

  const state={activeExchange:workspacePreference.exchange,selectedMarket:initialMarket,selectedTimeframe:workspacePreference.timeframe,watchlist:storedWatchlist(workspacePreference.exchange),marketSnapshots:{},connectionStatus:'CONNECTING',loadingState:{universe:true,snapshots:true,chart:true},errorState:{universe:null,snapshots:null,chart:null}};
  const marketForAsset=asset=>marketForAssetOnExchange(asset,state.activeExchange,state.selectedMarket?.quoteAsset||'USDT');
  function saveWorkspace(){try{localStorage.setItem(WORKSPACE_KEY,JSON.stringify(ZychWorkspace.preference(state)))}catch{}}
  const updateSnapshot=(id,patch)=>{state.marketSnapshots={...state.marketSnapshots,[id]:{...(state.marketSnapshots[id]||{}),...patch}}};

  const exchangeAdapters=ZychExchanges.adapters;
  const marketSockets=new Set();
  const updateSocketDiagnostics=()=>{document.documentElement.dataset.marketSockets=String(marketSockets.size)};
  const historyService=new ZychChartHistory.ChartHistoryService({adapters:exchangeAdapters});

  function normalizeUniverse(markets){
    const leveraged=/(UP|DOWN|BULL|BEAR)$/;
    const safeTicker=value=>typeof value==='string'&&/^[A-Z0-9]{1,20}$/.test(value),safeSymbol=value=>typeof value==='string'&&/^[A-Z0-9-]{1,30}$/.test(value);
    MARKETS=markets.filter(row=>row.enabled&&safeSymbol(row.symbol)&&safeTicker(row.baseAsset)&&safeTicker(row.quoteAsset)&&QUOTE_PRIORITY.includes(row.quoteAsset)&&!leveraged.test(row.baseAsset));
    rebuildAssetIndex();
    document.documentElement.dataset.universeMarkets=String(MARKETS.length);document.documentElement.dataset.universeAssets=String(assetIndex.size);
    state.watchlist=ZychWatchlist.migrate(state.watchlist,{markets:MARKETS,exchange:state.activeExchange,defaults:hasStoredWatchlist()?[]:DEFAULT_WATCHLIST});
    const current=state.selectedMarket,resolved=MARKETS.find(market=>market.id===current.id&&market.exchange===state.activeExchange)||marketForAssetOnExchange(current.asset,state.activeExchange,current.quoteAsset);state.selectedMarket=resolved||ZychWorkspace.unavailableMarket(current.asset,state.activeExchange,current.quoteAsset);
  }
  const liquidityForAsset=asset=>catalogLiquidity.get(asset)||0;
  const catalogMetric=(asset,key)=>catalogSnapshots.get(asset)?.[key];
  function rebuildCatalogMetrics(){catalogLiquidity=new Map();catalogSnapshots=new Map();assetIndex.forEach((_markets,asset)=>{const market=marketForAsset(asset),snapshot=market&&state.marketSnapshots[market.id];if(snapshot){catalogLiquidity.set(asset,snapshot.volume||0);catalogSnapshots.set(asset,snapshot)}})}
  function searchUniverse(query,mode='top'){
    const value=query.trim().toUpperCase(),assets=[...assetIndex.keys()];
    const matches=value?assets.filter(asset=>asset.includes(value)||(assetMeta(asset).name||'').toUpperCase().includes(value)||(assetIndex.get(asset)||[]).some(market=>market.symbol.startsWith(value))):assets;
    return matches.sort((a,b)=>{const exact=(b===value)-(a===value);if(exact)return exact;const prefix=(b.startsWith(value)?1:0)-(a.startsWith(value)?1:0);if(prefix)return prefix;if(mode==='volume')return liquidityForAsset(b)-liquidityForAsset(a)||a.localeCompare(b);if(mode==='gainers')return (catalogMetric(b,'changePercent')??-Infinity)-(catalogMetric(a,'changePercent')??-Infinity)||liquidityForAsset(b)-liquidityForAsset(a);if(mode==='losers')return (catalogMetric(a,'changePercent')??Infinity)-(catalogMetric(b,'changePercent')??Infinity)||liquidityForAsset(b)-liquidityForAsset(a);const popularA=POPULAR_ASSETS.indexOf(a),popularB=POPULAR_ASSETS.indexOf(b),popular=(popularA<0?999:popularA)-(popularB<0?999:popularB);if(popular)return popular;return liquidityForAsset(b)-liquidityForAsset(a)||a.localeCompare(b)})
  }

  let activeController=null,activeSocket=null,reconnectTimer=null,generation=0,intentionalClose=false;
  function stopMarket(){intentionalClose=true;activeController?.abort();activeController=null;clearTimeout(reconnectTimer);reconnectTimer=null;if(activeSocket&&activeSocket.readyState<WebSocket.CLOSING)activeSocket.close(1000,'Market changed');activeSocket=null}
  function openLive(context){const{market,timeframe,token,onCandle,onStatus}=context,adapter=exchangeAdapters[market.exchange];intentionalClose=false;let socket=null;socket=adapter.socket(market,timeframe,{open:()=>{marketSockets.add(socket);updateSocketDiagnostics();token===generation&&onStatus('LIVE')},candle:candle=>token===generation&&onCandle(candle),error:()=>token===generation&&onStatus('OFFLINE'),close:()=>{marketSockets.delete(socket);updateSocketDiagnostics();if(intentionalClose||token!==generation)return;onStatus('RECONNECTING');reconnectTimer=setTimeout(()=>token===generation&&openLive(context),2500)}});activeSocket=socket}
  async function selectMarketData(market,timeframe,handlers){
    stopMarket();const token=++generation;activeController=new AbortController();handlers.onStatus('CONNECTING');
    try{const result=await historyService.initial(market,timeframe,activeController.signal);if(token!==generation)return;handlers.onCandles(result.data,result);openLive({market,timeframe,token,onCandle:handlers.onCandle,onStatus:handlers.onStatus})}
    catch(error){if(error.name==='AbortError'||token!==generation)return;handlers.onStatus('OFFLINE');handlers.onError(error)}
  }

  const chartContainer=document.getElementById('chart'),chartState=document.getElementById('chart-state'),chartHistoryState=document.getElementById('chart-history-state');
  const chart=LightweightCharts.createChart(chartContainer,{width:chartContainer.clientWidth,height:chartContainer.clientHeight,layout:{background:{color:'#0d1014'},textColor:'#747d86',attributionLogo:true},grid:{vertLines:{color:'#181d23'},horzLines:{color:'#181d23'}},rightPriceScale:{borderColor:'#252c33',scaleMargins:{top:.08,bottom:.22}},timeScale:{borderColor:'#252c33',timeVisible:true,secondsVisible:false}});
  const themeMarketColor=(property,fallback)=>getComputedStyle(document.documentElement).getPropertyValue(property).trim()||fallback;
  const bullishColor=()=>themeMarketColor('--positive','#2bc477'),bearishColor=()=>themeMarketColor('--negative','#ed515b');
  const candleOptions={upColor:bullishColor(),downColor:bearishColor(),borderUpColor:bullishColor(),borderDownColor:bearishColor(),wickUpColor:bullishColor(),wickDownColor:bearishColor(),priceLineColor:bullishColor()};
  const candles=chart.addSeries?chart.addSeries(LightweightCharts.CandlestickSeries,candleOptions):chart.addCandlestickSeries(candleOptions);
  const volumeOptions={priceFormat:{type:'volume'},priceScaleId:'',lastValueVisible:false,priceLineVisible:false};
  const volumes=chart.addSeries?chart.addSeries(LightweightCharts.HistogramSeries,volumeOptions):chart.addHistogramSeries(volumeOptions);volumes.priceScale().applyOptions({scaleMargins:{top:.82,bottom:0}});
  const volumePoint=candle=>({time:candle.time,value:candle.volume,color:candle.close>=candle.open?'rgba(43,196,119,.34)':'rgba(237,81,91,.32)'});
  const updatePriceDirection=candle=>{if(!candle)return;const direction=Number(candle.close)>=Number(candle.open)?'bullish':'bearish';candles.applyOptions({priceLineColor:direction==='bullish'?bullishColor():bearishColor()});chartContainer.dataset.priceDirection=direction};
  new ResizeObserver(entries=>{const{width,height}=entries[0].contentRect;chart.applyOptions({width,height})}).observe(chartContainer);
  const updateChartDiagnostics=(data,key,pages)=>{chartContainer.dataset.historyKey=key||'';chartContainer.dataset.candleCount=String(data.length);chartContainer.dataset.oldestTime=String(data[0]?.time||'');chartContainer.dataset.newestTime=String(data.at(-1)?.time||'');chartContainer.dataset.historyPages=String(pages||0)};
  const chartApi={
    setData:(data,key,pages)=>{candles.setData(data);volumes.setData(data.map(volumePoint));updatePriceDirection(data.at(-1));const latestFrom=Math.max(0,data.length-180);chart.timeScale().setVisibleLogicalRange({from:latestFrom,to:data.length+5});updateChartDiagnostics(data,key,pages)},
    clear:()=>{candles.setData([]);volumes.setData([]);updateChartDiagnostics([], '', 0)},
    prepend:(data,added,range,key,pages)=>{candles.setData(data);volumes.setData(data.map(volumePoint));updatePriceDirection(data.at(-1));if(range&&added>0)chart.timeScale().setVisibleLogicalRange({from:range.from+added,to:range.to+added});updateChartDiagnostics(data,key,pages)},
    update:candle=>{candles.update(candle);volumes.update(volumePoint(candle));updatePriceDirection(candle);chartContainer.dataset.newestTime=String(candle.time)},
    range:()=>chart.timeScale().getVisibleLogicalRange(),subscribe:handler=>chart.timeScale().subscribeVisibleLogicalRangeChange(handler),
    loading:text=>{chartState.textContent=text;chartState.hidden=false},ready:()=>{chartState.hidden=true}
  };
  let historyContext=null,historyLoading=false,historyStatusTimer=null;
  const setHistoryStatus=(text,status='loading',linger=0)=>{clearTimeout(historyStatusTimer);chartHistoryState.textContent=text;chartHistoryState.dataset.status=status;chartHistoryState.hidden=!text;if(linger)historyStatusTimer=setTimeout(()=>{chartHistoryState.hidden=true},linger)};
  async function loadOlderHistory(){
    const context=historyContext;if(!context||historyLoading||context.endReached||!activeController||activeController.signal.aborted)return;
    historyLoading=true;const range=chartApi.range();setHistoryStatus('Loading history…');
    try{const result=await historyService.older(context.market,context.timeframe,activeController.signal);if(historyContext!==context||context.token!==generation)return;context.endReached=result.endReached;chartApi.prepend(result.data,result.added,range,result.key,result.pages);if(result.endReached)setHistoryStatus('Start of available history','end',2600);else setHistoryStatus('', 'idle')}
    catch(error){if(error.name!=='AbortError'&&historyContext===context)setHistoryStatus('History load failed','error',2600)}
    finally{if(historyContext===context)historyLoading=false}
  }
  chartApi.subscribe(range=>{if(range&&range.from<120)loadOlderHistory()});

  const watchContainer=document.getElementById('watchlist-rows');
  function renderWatchlist(){
    watchContainer.dataset.exchange=state.activeExchange;
    watchContainer.innerHTML=state.watchlist.length?state.watchlist.map(item=>{const market=ZychWatchlist.resolve(item,MARKETS),asset=item.asset,safeKey=escapeHtml(item.key),exchange=EXCHANGES[item.exchange]?.label||item.exchange;return `<div class="watch-row loading" data-watch-key="${safeKey}" data-market-id="${escapeHtml(item.marketId)}" data-exchange="${escapeHtml(item.exchange)}"><button class="watch-row-main" type="button" data-select-watch="${safeKey}" aria-label="Open ${escapeHtml(asset)} on ${escapeHtml(exchange)}"><span>${iconMarkup(assetMeta(asset))}<span class="watch-identity"><b>${escapeHtml(asset)}/${escapeHtml(item.quoteAsset)}</b><small>${escapeHtml(exchange)} · ${escapeHtml(item.marketType||'spot')}</small></span></span><strong>—</strong><em>—</em></button><button class="watch-remove-button" type="button" data-remove-watch="${safeKey}" aria-label="Remove ${escapeHtml(asset)} on ${escapeHtml(exchange)} from Watchlist" title="Remove from Watchlist">×</button></div>`}).join(''):'<div class="watchlist-empty">Watchlist is empty<button type="button" data-open-search>Find an asset</button></div>';
    state.watchlist.forEach(item=>{const market=ZychWatchlist.resolve(item,MARKETS),snapshot=market&&state.marketSnapshots[market.id];if(snapshot)updateWatch(item.key,snapshot)});selectWatch(state.selectedMarket.id);
  }
  const updateWatch=(key,snapshot)=>{const row=[...watchContainer.querySelectorAll('[data-watch-key]')].find(item=>item.dataset.watchKey===key);if(!row||!snapshot)return;row.classList.remove('loading');row.querySelector('strong').textContent=formatPrice(snapshot.lastPrice);const change=row.querySelector('em');change.textContent=formatPercent(snapshot.changePercent);applyDirection(change,snapshot.changePercent)};
  const selectWatch=marketId=>watchContainer.querySelectorAll('[data-market-id]').forEach(row=>row.classList.toggle('active',row.dataset.marketId===marketId));

  const pulseCards=[...document.querySelectorAll('[data-pulse-asset]')];
  const updatePulse=(asset,snapshot)=>{const card=pulseCards.find(item=>item.dataset.pulseAsset===asset);if(!card||!snapshot)return;card.querySelector('strong').textContent=`$${formatPrice(snapshot.lastPrice)}`;const change=card.querySelector('.pulse-copy>span');change.textContent=formatPercent(snapshot.changePercent);applyDirection(change,snapshot.changePercent)};

  const workspaceButton=document.getElementById('active-exchange-selector'),workspaceMenu=document.getElementById('active-exchange-menu');
  function renderActiveExchange(){const label=EXCHANGES[state.activeExchange].label;workspaceButton.querySelector('[data-active-exchange-label]').textContent=label;workspaceButton.querySelector('[data-active-exchange-icon]').textContent=label.slice(0,1).toUpperCase();workspaceMenu.querySelectorAll('[data-active-exchange-option]').forEach(button=>button.classList.toggle('active',button.dataset.activeExchangeOption===state.activeExchange));document.documentElement.dataset.activeExchange=state.activeExchange}
  function resetWorkspaceSurfaces(){renderWatchlist();pulseCards.forEach(card=>{const market=marketForAsset(card.dataset.pulseAsset),snapshot=market&&state.marketSnapshots[market.id],price=card.querySelector('strong'),change=card.querySelector('.pulse-copy>span');price.textContent=snapshot?`$${formatPrice(snapshot.lastPrice)}`:'—';change.textContent=snapshot?formatPercent(snapshot.changePercent):'—';applyDirection(change,snapshot?.changePercent)});rebuildCatalogMetrics()}
  function switchActiveExchange(exchange){const next=ZychWorkspace.validExchange(exchange);workspaceMenu.hidden=true;workspaceButton.setAttribute('aria-expanded','false');if(next===state.activeExchange)return;const market=ZychWorkspace.equivalentMarket(MARKETS,state.selectedMarket,next);if(market){openMarketContext(ZychMarketContext.fromMarket(market,{timeframe:state.selectedTimeframe}));renderActiveExchange();if(!searchResults.hidden)drawSearch();return}state.activeExchange=next;state.selectedMarket=ZychWorkspace.unavailableMarket(state.selectedMarket.asset,next,state.selectedMarket.quoteAsset);saveWorkspace();renderActiveExchange();resetWorkspaceSurfaces();renderMarket();if(!searchResults.hidden)drawSearch();refreshSnapshots();loadMarket()}
  workspaceButton.addEventListener('click',event=>{event.stopPropagation();const open=workspaceMenu.hidden;workspaceMenu.hidden=!open;workspaceButton.setAttribute('aria-expanded',String(open))});workspaceMenu.addEventListener('click',event=>{const option=event.target.closest('[data-active-exchange-option]');if(option)switchActiveExchange(option.dataset.activeExchangeOption)});

  function renderMarket(){
    const market=state.selectedMarket,snapshot=state.marketSnapshots[market.id],meta=assetMeta(market.asset);
    renderActiveExchange();
    document.querySelectorAll('[data-pair-label]').forEach(el=>el.textContent=marketLabel(market));document.querySelectorAll('[data-exchange-label]').forEach(el=>el.textContent=EXCHANGES[market.exchange].label);
    const pairIcon=document.getElementById('toolbar-market-icon');pairIcon.className=`coin-icon ${meta.className} small`;pairIcon.textContent=meta.icon;
    document.getElementById('current-price').textContent=formatPrice(snapshot?.lastPrice);const toolbarChange=document.getElementById('toolbar-change');toolbarChange.innerHTML=`${formatPercent(snapshot?.changePercent)} <small>24h</small>`;applyDirection(toolbarChange,snapshot?.changePercent);document.getElementById('toolbar-high').textContent=formatPrice(snapshot?.high);document.getElementById('toolbar-low').textContent=formatPrice(snapshot?.low);document.getElementById('toolbar-volume').textContent=snapshot?`$${formatCompact(snapshot.volume)}`:'—';
    selectWatch(market.id);document.querySelectorAll('.timeframes button').forEach(button=>button.classList.toggle('active',button.dataset.interval===state.selectedTimeframe));
    const favorite=document.getElementById('favorite-button'),saved=!market.unavailable&&ZychWatchlist.contains(state.watchlist,market);favorite.classList.toggle('active',saved);favorite.textContent=saved?'★':'☆';favorite.setAttribute('aria-pressed',String(saved));favorite.disabled=Boolean(market.unavailable);favorite.setAttribute('aria-label',`${saved?'Remove':'Add'} ${market.asset} ${EXCHANGES[market.exchange].label} ${saved?'from':'to'} Watchlist`);
  }

  const statusElements=[document.getElementById('connection-status'),document.getElementById('market-status')];
  function setConnection(status){state.connectionStatus=status;statusElements.forEach(el=>{el.dataset.status=status.toLowerCase();el.lastChild.textContent=` ${status}`});const exchange=EXCHANGES[state.selectedMarket.exchange].label;document.getElementById('connection-message').textContent=status==='LIVE'?`${exchange} live market data`:status==='OFFLINE'?'Live stream unavailable':`Connecting to ${exchange}`}
  const setOhlc=candle=>document.getElementById('ohlc-status').textContent=`O ${formatPrice(candle.open)}  H ${formatPrice(candle.high)}  L ${formatPrice(candle.low)}  C ${formatPrice(candle.close)}`;
  function renderLiveQuote(market,snapshot){document.getElementById('current-price').textContent=formatPrice(snapshot.lastPrice);updateWatch(ZychWatchlist.identity(market),snapshot);updatePulse(market.asset,snapshot)}
  function liveCandle(market,candle){if(state.selectedMarket.id!==market.id)return;historyService.updateLive(market,state.selectedTimeframe,candle);chartApi.update(candle);setOhlc(candle);updateSnapshot(market.id,{...(state.marketSnapshots[market.id]||{}),lastPrice:candle.close});renderLiveQuote(market,state.marketSnapshots[market.id])}
  function loadMarket(){
    quickMenu.close();closeAlertLineMenu();cancelQuickDrag();renderQuickAlertLines();const market=state.selectedMarket,timeframe=state.selectedTimeframe;historyContext=null;historyLoading=false;setHistoryStatus('');state.loadingState.chart=true;state.errorState.chart=null;chartApi.loading('Loading market data…');document.getElementById('ohlc-status').textContent='Loading market data…';renderMarket();
    if(market.unavailable){stopMarket();generation+=1;chartApi.clear();const message=`${market.asset} is not available on ${EXCHANGES[market.exchange].label}`;chartApi.loading(message);document.getElementById('ohlc-status').textContent=message;setConnection('OFFLINE');state.errorState.chart=message;state.loadingState.chart=false;document.getElementById('retry-button').hidden=true;return}
    selectMarketData(market,timeframe,{onStatus:setConnection,onCandles:(data,result)=>{if(state.selectedMarket.id!==market.id||state.selectedTimeframe!==timeframe)return;if(!data.length){chartApi.loading('No market data');return}historyContext={market,timeframe,token:generation,endReached:result.endReached,key:result.key};chartApi.setData(data,result.key,result.pages);chartApi.ready();setOhlc(data.at(-1));updateSnapshot(market.id,{...(state.marketSnapshots[market.id]||{}),lastPrice:data.at(-1).close});updateWatch(ZychWatchlist.identity(market),state.marketSnapshots[market.id]);updatePulse(market.asset,state.marketSnapshots[market.id]);renderMarket();state.loadingState.chart=false;document.getElementById('retry-button').hidden=true},onCandle:candle=>liveCandle(market,candle),onError:error=>{const message=error.name==='TimeoutError'?'Market request timed out':'Market data unavailable';state.errorState.chart=message;chartApi.loading(message);document.getElementById('ohlc-status').textContent=message;document.getElementById('retry-button').hidden=false}})
  }
  function selectAsset(asset){const market=marketForAsset(asset);if(market)return openMarketContext(ZychMarketContext.fromMarket(market));state.selectedMarket=ZychWorkspace.unavailableMarket(asset,state.activeExchange,state.selectedMarket.quoteAsset);saveWorkspace();renderMarket();refreshSnapshots();loadMarket();return false}
  function openMarketContext(context,{closePanel=false}={}){const normalized=ZychMarketContext.create(context);if(!normalized)return false;const market=MARKETS.find(item=>item.enabled&&item.exchange===normalized.exchange&&item.symbol===normalized.symbol);if(!market)return false;state.activeExchange=market.exchange;state.selectedMarket=market;if(normalized.timeframe){const interval=normalized.timeframe==='24h'?'1d':normalized.timeframe;if(TIMEFRAMES.includes(interval))state.selectedTimeframe=interval}state.marketContext={...normalized,eventTimestamp:normalized.eventTimestamp};saveWorkspace();resetWorkspaceSurfaces();renderMarket();refreshSnapshots();loadMarket();if(closePanel)closeAlertsPanel();return true}
  function selectMarketId(id){const market=MARKETS.find(item=>item.id===id&&item.enabled);if(market)openMarketContext(ZychMarketContext.fromMarket(market))}
  function toggleWatchlist(market){if(!market||market.unavailable)return;state.watchlist=ZychWatchlist.toggle(state.watchlist,market);saveWatchlist();renderWatchlist();renderMarket();if(!searchResults.hidden)drawSearch();refreshSnapshots()}
  watchContainer.addEventListener('click',event=>{if(event.target.closest('[data-open-search]')){openSearch();return}const remove=event.target.closest('[data-remove-watch]');if(remove){event.stopPropagation();const item=state.watchlist.find(row=>row.key===remove.dataset.removeWatch),market=item&&ZychWatchlist.resolve(item,MARKETS);if(market)toggleWatchlist(market);return}const select=event.target.closest('[data-select-watch]');if(select){const item=state.watchlist.find(row=>row.key===select.dataset.selectWatch),market=item&&ZychWatchlist.resolve(item,MARKETS);if(market)selectMarketId(market.id)}});pulseCards.forEach(card=>card.addEventListener('click',()=>selectAsset(card.dataset.pulseAsset)));
  document.querySelectorAll('.timeframes button').forEach(button=>button.addEventListener('click',()=>{if(TIMEFRAMES.includes(button.dataset.interval)&&button.dataset.interval!==state.selectedTimeframe){state.selectedTimeframe=button.dataset.interval;saveWorkspace();loadMarket()}}));
  document.getElementById('favorite-button').addEventListener('click',()=>toggleWatchlist(state.selectedMarket));

  const searchInput=document.getElementById('coin-search'),searchResults=document.getElementById('search-results'),searchShell=document.querySelector('.search-shell');let searchMatches=[],searchIndex=-1,searchTimer=null,searchMode='top';
  const closeSearch=()=>{searchResults.hidden=true;searchShell.classList.remove('open');searchIndex=-1};
  function openSearch(){searchShell.classList.add('open');searchInput.focus();drawSearch()}
  function drawSearch(){
    if(universeStatus==='loading'){searchResults.innerHTML='<div class="universe-state">Loading market universe…</div>';searchResults.hidden=false;return}
    if(universeStatus==='error'&&!assetIndex.size){searchResults.innerHTML='<div class="universe-state">Market catalog unavailable<button class="catalog-retry-button" type="button" data-retry-universe>Retry</button></div>';searchResults.hidden=false;return}
    searchMatches=searchUniverse(searchInput.value,searchMode);searchIndex=searchMatches.length?0:-1;
    const tabs=`<div class="market-browser-tabs" role="tablist" aria-label="Market sorting">${[['top','Top'],['volume','Volume'],['gainers','Gainers'],['losers','Losers']].map(([mode,label])=>`<button type="button" role="tab" data-search-mode="${mode}" aria-selected="${searchMode===mode}" class="${searchMode===mode?'active':''}">${label}</button>`).join('')}</div>`;
    const hint=!favoriteHintSeen()?'<div class="favorite-hint">☆ Add to Watchlist</div>':'';
    const rows=searchMatches.length?searchMatches.map((asset,index)=>{const market=marketForAsset(asset),available=marketsForAsset(asset).filter(item=>item.enabled).map(item=>EXCHANGES[item.exchange].label).join(' · '),saved=market&&ZychWatchlist.contains(state.watchlist,market),meta=assetMeta(asset),snapshot=market&&state.marketSnapshots[market.id],change=snapshot?.changePercent,direction=Number.isFinite(change)?(change>=0?'positive':'negative'):'',safeAsset=escapeHtml(asset),marketCopy=market?`${market.baseAsset}/${market.quoteAsset} · ${EXCHANGES[state.activeExchange].label}`:`Unavailable on ${EXCHANGES[state.activeExchange].label}`;return `<div class="search-asset ${index===searchIndex?'active':''}" data-result-index="${index}" data-volume="${snapshot?.volume??''}" data-change="${Number.isFinite(change)?change:''}"><button class="dropdown-item market-asset-button" type="button" data-select-asset="${safeAsset}">${iconMarkup(meta,'tiny')}<span class="search-identity"><strong>${safeAsset}</strong>${meta.name&&meta.name.toUpperCase()!==asset?`<small>${escapeHtml(meta.name)}</small>`:''}<small class="search-market">${escapeHtml(marketCopy)}${market?'':` · Available: ${escapeHtml(available)}`}</small></span><span class="market-result-data"><strong>${snapshot?`$${formatPrice(snapshot.lastPrice)}`:'—'}</strong><em class="${direction}">${formatPercent(change)}</em></span></button><button class="search-watch-button ${saved?'active':''}" type="button" data-toggle-watch="${safeAsset}" aria-label="${saved?'Remove from':'Add to'} Watchlist" title="${saved?'Remove from':'Add to'} Watchlist">${saved?'★':'☆'}</button></div>`}).join(''):'<div class="dropdown-empty">No assets found</div>';
    searchResults.innerHTML=`${tabs}${hint}<div class="market-browser-list">${rows}</div>`;searchResults.hidden=false;
  }
  function scheduleSearch(){clearTimeout(searchTimer);searchTimer=setTimeout(drawSearch,100)}
  function setSearchIndex(index){searchIndex=index;searchResults.querySelectorAll('.search-asset').forEach((item,itemIndex)=>item.classList.toggle('active',itemIndex===searchIndex));searchResults.querySelector(`[data-result-index="${searchIndex}"]`)?.scrollIntoView({block:'nearest'})}
  searchInput.addEventListener('input',scheduleSearch);searchInput.addEventListener('focus',drawSearch);searchInput.addEventListener('keydown',event=>{if(event.key==='Escape'){closeSearch();searchInput.blur();return}if(event.key==='ArrowDown'&&searchMatches.length){event.preventDefault();setSearchIndex((searchIndex+1)%searchMatches.length)}if(event.key==='ArrowUp'&&searchMatches.length){event.preventDefault();setSearchIndex((searchIndex-1+searchMatches.length)%searchMatches.length)}if(event.key==='Enter'&&searchMatches[searchIndex]){event.preventDefault();selectAsset(searchMatches[searchIndex]);searchInput.value='';closeSearch()}});
  searchResults.addEventListener('click',event=>{const retry=event.target.closest('[data-retry-universe]');if(retry){event.stopPropagation();loadUniverse();return}const mode=event.target.closest('[data-search-mode]');if(mode){event.stopPropagation();searchMode=mode.dataset.searchMode;drawSearch();return}const toggle=event.target.closest('[data-toggle-watch]');if(toggle){event.stopPropagation();dismissFavoriteHint();toggleWatchlist(marketForAsset(toggle.dataset.toggleWatch));drawSearch();return}const option=event.target.closest('[data-select-asset]');if(option){selectAsset(option.dataset.selectAsset);searchInput.value='';closeSearch()}});
  document.getElementById('mobile-search-button').addEventListener('click',event=>{event.stopPropagation();openSearch()});document.getElementById('add-watchlist-button').addEventListener('click',event=>{event.stopPropagation();openSearch()});document.addEventListener('keydown',event=>{if(event.key==='/'&&document.activeElement!==searchInput){event.preventDefault();openSearch()}});document.addEventListener('click',event=>{if(!event.target.closest('.search-shell')&&!event.target.closest('.global-exchange-shell')){closeSearch();workspaceMenu.hidden=true;workspaceButton.setAttribute('aria-expanded','false')}});

  const alertStorage=new ZychAlerts.AlertStorage(),hubActions=new ZychQuickAlerts.ActionCoordinator(),hubOverrides=new Map();let alertTab='all';
  const alertDialogBackdrop=document.getElementById('alert-dialog-backdrop'),alertForm=document.getElementById('alert-form'),alertFormError=document.getElementById('alert-form-error'),alertsPanel=document.getElementById('alerts-panel'),alertsPanelBackdrop=document.getElementById('alerts-panel-backdrop'),alertsList=document.getElementById('alerts-list'),alertCounter=document.getElementById('alerts-counter'),alertMonitorStatus=document.getElementById('alert-monitor-status'),toastRegion=document.getElementById('toast-region'),soundSelect=document.getElementById('alert-sound-select'),soundVolume=document.getElementById('alert-sound-volume'),soundToggle=document.getElementById('alert-sound-toggle'),soundTest=document.getElementById('alert-sound-test'),soundState=document.getElementById('alert-sound-state');
  const alertTypeInputs=[...alertForm.elements['alert-type']],alertFieldsets={price:document.getElementById('alert-price-fields'),movement:document.getElementById('alert-movement-fields'),volume:document.getElementById('alert-volume-fields')};
  const formatAlertTime=value=>new Date(value).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
  function alertDescription(alert){const c=alert.condition;if(c.type==='price')return `Price ${c.operator} $${formatPrice(c.value)}`;if(c.type==='movement')return `${c.direction==='up'?'+':'−'}${c.percent}% within ${c.window}`;return `Volume ≥ ${c.multiplier}x average · ${c.timeframe}`}
  function eventDescription(event){if(event.alertType==='price')return `Price crossed ${event.condition.operator} $${formatPrice(event.threshold)} · $${formatPrice(event.currentPrice)}`;if(event.alertType==='movement')return `${event.percentMove>=0?'+':''}${Number(event.percentMove).toFixed(2)}% in ${event.window}`;return `Volume ${Number(event.multiplier).toFixed(2)}x average`}
  function updateAlertCounter(){const count=alertEngine.activeCount();alertCounter.textContent=String(count);alertCounter.hidden=count===0}
  function renderAlertsPanel(){
    document.querySelectorAll('[data-alert-tab]').forEach(button=>button.classList.toggle('active',button.dataset.alertTab===alertTab));
    if(alertTab==='triggered'){const events=alertEngine.events();alertsList.innerHTML=events.length?events.map(event=>`<article class="alert-row" data-alert-context="${escapeHtml(event.marketId)}" data-alert-timeframe="${escapeHtml(event.timeframe||'')}"><div class="alert-row-top"><div><strong>${escapeHtml(event.asset)}</strong><p>${escapeHtml(eventDescription(event))}</p><small>${escapeHtml(event.exchange)} · ${formatAlertTime(event.triggeredAt)}</small></div><div class="alert-row-actions"><button class="delete-alert" type="button" data-alert-action="dismiss-event" data-event-id="${escapeHtml(event.id)}">Delete</button></div></div></article>`).join(''):'<div class="alerts-empty">No triggered alerts</div>';return}
    const source=alertEngine.list().map(alert=>hubOverrides.has(alert.id)?{...alert,status:hubOverrides.get(alert.id)}:alert).filter(alert=>alert.status!==null),alerts=ZychAlertHub.visibleAlerts(source,alertTab);source.forEach(alert=>hubActions.register(alert.id,alert.status));hubActions.removeMissing(alertEngine.list().map(alert=>alert.id));alertsList.innerHTML=alerts.length?alerts.map(alert=>{const context=ZychAlertHub.openContext(alert);return `<article class="alert-row ${alert.status==='paused'?'paused':''}" data-alert-id="${escapeHtml(alert.id)}" data-alert-market="${escapeHtml(context.marketId)}"><div class="alert-row-top"><div class="alert-row-identity"><div class="alert-row-heading"><strong>${escapeHtml(context.symbol)}</strong><span class="alert-status-badge ${alert.status==='paused'?'paused':''}">${alert.status.toUpperCase()}</span></div><p>${escapeHtml(alertDescription(alert))}</p><small>${escapeHtml(ZychAlertHub.marketText(alert))} · ${escapeHtml(alert.mode)}</small></div><div class="alert-row-actions"><button class="open-alert" type="button" data-alert-open="${escapeHtml(context.marketId)}" data-alert-timeframe="${escapeHtml(context.timeframe)}">Open</button><button type="button" data-alert-action="${alert.status==='active'?'pause':'resume'}" data-alert-id="${escapeHtml(alert.id)}">${alert.status==='active'?'Pause':'Resume'}</button><button class="delete-alert" type="button" data-alert-action="delete" data-alert-id="${escapeHtml(alert.id)}">Delete</button></div></div></article>`}).join(''):'<div class="alerts-empty">No alerts yet<small>Create a Quick Alert from the chart.</small></div>'
  }
  function openAlertContext(marketId,timeframe){const market=MARKETS.find(item=>item.id===marketId||`${item.exchange}:spot:${item.symbol}`===marketId);return market&&openMarketContext(ZychMarketContext.fromMarket(market,{timeframe}),{closePanel:true})}
  function renderSoundState(current){soundSelect.value=current.soundId;soundVolume.value=String(current.volume);soundToggle.textContent=current.enabled?'ON':'OFF';soundToggle.classList.toggle('active',current.enabled);soundToggle.setAttribute('aria-pressed',String(current.enabled));soundToggle.setAttribute('aria-label',`Turn alert sound ${current.enabled?'off':'on'}`);soundToggle.dataset.playCount=String(current.playCount);soundState.textContent=current.enabled&&!current.unlocked?'Tap to enable audio':''}
  const alertSound=new ZychNotifications.AlertSoundManager({onState:renderSoundState});renderSoundState(alertSound.state());
  const notificationCenter=new ZychNotifications.NotificationCenter({region:toastRegion,sound:alertSound,describe:eventDescription,formatTime:formatAlertTime,onOpen:event=>openAlertContext(event.marketId,event.timeframe)});
  const browserNotifier=new ZychNotifications.BrowserNotifier({notificationCenter});
  const pushManager=new ZychNotifications.PushManagerController({button:document.getElementById('push-notifications-toggle')});pushManager.init();document.getElementById('push-notifications-toggle').addEventListener('click',()=>pushManager.toggle());
  const quickAlertElement=document.getElementById('quick-alert-menu'),quickMenu=new ZychQuickAlerts.MenuController(quickAlertElement),alertLineMenu=document.getElementById('alert-line-menu'),quickPriceLines=new Map(),quickUpdates=new ZychQuickAlerts.UpdateCoordinator(),quickActions=new ZychQuickAlerts.ActionCoordinator();let activeQuickDrag=null,selectedAlertLineId=null;
  const quickLineOptions=record=>record.alert.status==='paused'?{color:themeMarketColor('--text-muted','#77828b'),lineWidth:1,lineStyle:LightweightCharts.LineStyle?.Dashed??2,axisLabelVisible:true,title:'Ⅱ'}:{color:themeMarketColor('--warning','#d9943e'),lineWidth:1,lineStyle:LightweightCharts.LineStyle?.Dashed??2,axisLabelVisible:true,title:'♢'};
  function closeAlertLineMenu(){selectedAlertLineId=null;alertLineMenu.hidden=true;alertLineMenu.replaceChildren()}
  function renderQuickAlertLines(){closeAlertLineMenu();quickPriceLines.forEach(record=>candles.removePriceLine(record.line));quickPriceLines.clear();const alerts=ZychQuickAlerts.matchingAlerts(alertEngine.list(),state.selectedMarket.id);alerts.forEach(alert=>{const price=Number(alert.condition.value),record={id:alert.id,alert:{...alert},line:null,price};record.line=candles.createPriceLine({price,...quickLineOptions(record)});quickPriceLines.set(alert.id,record);quickUpdates.register(alert.id,price);quickActions.register(alert.id,alert.status)});quickUpdates.removeMissing(alerts.map(alert=>alert.id));quickActions.removeMissing(alerts.map(alert=>alert.id));chartContainer.dataset.alertLineCount=String(quickPriceLines.size);chartContainer.dataset.alertLineMarket=state.selectedMarket.id}
  const quickLineAt=y=>ZychQuickAlerts.closestLine([...quickPriceLines.values()],y,price=>candles.priceToCoordinate(price),10);
  function applyQuickPrice(record,price){record.price=Number(price);record.line.applyOptions({price:record.price});chartContainer.dataset.dragPrice=String(record.price)}
  function applyQuickStatus(record,status){if(status===null){try{candles.removePriceLine(record.line)}catch{}quickPriceLines.delete(record.id);closeAlertLineMenu();chartContainer.dataset.alertLineCount=String(quickPriceLines.size);return}record.alert={...record.alert,status};record.line.applyOptions(quickLineOptions(record));if(selectedAlertLineId===record.id)openAlertLineMenu(record,Number(alertLineMenu.style.left.replace('px','')),Number(alertLineMenu.style.top.replace('px','')))}
  function openAlertLineMenu(record,x,y){quickMenu.close();selectedAlertLineId=record.id;const action=record.alert.status==='paused'?'resume':'pause',label=action==='resume'?'Resume':'Pause';alertLineMenu.innerHTML=`<button type="button" role="menuitem" data-alert-line-action="${action}" data-alert-id="${escapeHtml(record.id)}">${label}</button><button type="button" role="menuitem" data-alert-line-action="delete" data-alert-id="${escapeHtml(record.id)}">Delete</button>`;alertLineMenu.style.left=`${Math.max(0,Number(x)||0)}px`;alertLineMenu.style.top=`${Math.max(0,Number(y)||0)}px`;alertLineMenu.hidden=false}
  function cancelQuickDrag(){if(!activeQuickDrag)return;const record=activeQuickDrag.record,confirmed=quickUpdates.confirmed(record.id);if(Number.isFinite(confirmed))applyQuickPrice(record,confirmed);try{chartContainer.releasePointerCapture(activeQuickDrag.pointerId)}catch{}activeQuickDrag=null;chart.applyOptions({handleScroll:true,handleScale:true});chartContainer.classList.remove('alert-line-dragging','alert-line-hover')}
  function finishQuickDrag(event){if(!activeQuickDrag||event.pointerId!==activeQuickDrag.pointerId)return;const drag=activeQuickDrag,record=drag.record,price=ZychQuickAlerts.coordinateToPrice(candles,event.clientY-chartContainer.getBoundingClientRect().top);try{chartContainer.releasePointerCapture(event.pointerId)}catch{}activeQuickDrag=null;chart.applyOptions({handleScroll:true,handleScale:true});chartContainer.classList.remove('alert-line-dragging','alert-line-hover');if(!drag.moved){applyQuickPrice(record,quickUpdates.confirmed(record.id));const stage=chartContainer.parentElement.getBoundingClientRect();return openAlertLineMenu(record,Math.min(event.clientX-stage.left,stage.width-126),Math.min(event.clientY-stage.top,stage.height-72))}if(!price)return applyQuickPrice(record,quickUpdates.confirmed(record.id));applyQuickPrice(record,price);quickUpdates.commit(record.id,price,{update:(id,value)=>{chartContainer.dataset.alertUpdateRequests=String(Number(chartContainer.dataset.alertUpdateRequests||0)+1);return alertEngine.updatePrice(id,value)},apply:value=>applyQuickPrice(record,value),success:()=>{setHistoryStatus('Alert price updated','ready',1800);alertEngine.sync({notify:false}).catch(()=>{})},failure:()=>{setHistoryStatus('Alert update failed','error',2400);alertEngine.sync({notify:false}).catch(()=>{})}}).catch(()=>{})}
  const alertEngine=new ZychAlerts.ServerAlertClient({legacyStorage:alertStorage,notifier:browserNotifier,onChange:()=>{updateAlertCounter();renderAlertsPanel();renderQuickAlertLines()},onStatus:status=>{alertMonitorStatus.dataset.status=status.toLowerCase();alertMonitorStatus.lastChild.textContent=` ${status==='IDLE'?'Idle':status==='LIVE'?'Monitoring live':status[0]+status.slice(1).toLowerCase()}`}});
  chartContainer.addEventListener('contextmenu',event=>{if(matchMedia('(max-width:680px)').matches)return;event.preventDefault();const rect=chartContainer.getBoundingClientRect(),stage=chartContainer.parentElement.getBoundingClientRect(),record=quickLineAt(event.clientY-rect.top);quickMenu.close();closeAlertLineMenu();if(record)return openAlertLineMenu(record,Math.min(event.clientX-stage.left,stage.width-126),Math.min(event.clientY-stage.top,stage.height-72));const price=ZychQuickAlerts.coordinateToPrice(candles,event.clientY-rect.top);if(price)quickMenu.open({x:Math.min(event.clientX-stage.left,stage.width-190),y:Math.min(event.clientY-stage.top,stage.height-40),price,label:formatPrice(price)})});
  chartContainer.addEventListener('pointerdown',event=>{if(event.button!==0||matchMedia('(max-width:680px)').matches)return;quickMenu.close();const record=quickLineAt(event.clientY-chartContainer.getBoundingClientRect().top);if(!record){closeAlertLineMenu();return}event.preventDefault();event.stopPropagation();closeAlertLineMenu();activeQuickDrag={record,pointerId:event.pointerId,startX:event.clientX,startY:event.clientY,moved:false};chartContainer.setPointerCapture(event.pointerId);chart.applyOptions({handleScroll:false,handleScale:false})},true);
  chartContainer.addEventListener('pointermove',event=>{const y=event.clientY-chartContainer.getBoundingClientRect().top;if(activeQuickDrag){event.preventDefault();if(!activeQuickDrag.moved&&!ZychQuickAlerts.exceedsDragThreshold({x:activeQuickDrag.startX,y:activeQuickDrag.startY},event.clientX,event.clientY))return;activeQuickDrag.moved=true;chartContainer.classList.add('alert-line-dragging');const price=ZychQuickAlerts.coordinateToPrice(candles,y);if(price)applyQuickPrice(activeQuickDrag.record,price);return}chartContainer.classList.toggle('alert-line-hover',Boolean(quickLineAt(y)))});
  chartContainer.addEventListener('pointerup',finishQuickDrag);chartContainer.addEventListener('pointercancel',cancelQuickDrag);chartContainer.addEventListener('pointerleave',()=>{if(!activeQuickDrag)chartContainer.classList.remove('alert-line-hover')});
  chartContainer.addEventListener('wheel',()=>{quickMenu.close();closeAlertLineMenu()},{capture:true,passive:true});
  quickAlertElement.addEventListener('click',async event=>{if(!event.target.closest('[data-quick-alert-action]')||!quickMenu.payload)return;const market=state.selectedMarket,current=Number(state.marketSnapshots[market.id]?.lastPrice),price=quickMenu.payload.price;quickMenu.close();if(!Number.isFinite(current))return setHistoryStatus('Current price unavailable','error',2200);const result=await alertEngine.create(ZychQuickAlerts.definitionFor(market,price,current));setHistoryStatus(result.error?'Alert creation failed':'Alert created',result.error?'error':'ready',2200)});
  alertLineMenu.addEventListener('click',event=>{const button=event.target.closest('[data-alert-line-action]');if(!button)return;const record=quickPriceLines.get(button.dataset.alertId);if(!record)return closeAlertLineMenu();const action=button.dataset.alertLineAction,target=action==='pause'?'paused':action==='resume'?'active':null;closeAlertLineMenu();quickActions.commit(record.id,target,{update:(id,status)=>{chartContainer.dataset.alertActionRequests=String(Number(chartContainer.dataset.alertActionRequests||0)+1);return status===null?alertEngine.deleteAlert(id):alertEngine.updateStatus(id,status)},apply:status=>applyQuickStatus(record,status),optimistic:target!==null,success:()=>{setHistoryStatus(target===null?'Alert deleted':target==='paused'?'Alert paused':'Alert resumed','ready',1800);alertEngine.sync({notify:false}).catch(()=>{})},failure:()=>{setHistoryStatus('Alert action failed','error',2400);alertEngine.sync({notify:false}).catch(()=>{})}}).catch(()=>{})});
  document.addEventListener('pointerdown',event=>{if(!event.target.closest('#quick-alert-menu'))quickMenu.close();if(!event.target.closest('#alert-line-menu')&&!event.target.closest('#chart'))closeAlertLineMenu()});document.addEventListener('keydown',event=>{if(event.key==='Escape'){quickMenu.close();closeAlertLineMenu()}});
  function suggestedPrice(){const price=Number(state.marketSnapshots[state.selectedMarket.id]?.lastPrice);if(!Number.isFinite(price)||price<=0)return'';const raw=price*1.01,power=10**Math.max(-8,Math.floor(Math.log10(raw))-2);return String(Math.ceil(raw/power)*power)}
  function openAlertDialog(){alertSound.unlock();const market=state.selectedMarket;document.getElementById('alert-market-label').textContent=`${marketLabel(market)} · ${EXCHANGES[market.exchange].label}`;alertForm.reset();alertForm.elements['price-value'].value=suggestedPrice();alertForm.elements['movement-percent'].value='3';alertForm.elements['volume-multiplier'].value='2';alertFormError.textContent='';updateAlertType();alertDialogBackdrop.hidden=false;setTimeout(()=>alertForm.querySelector('input:not([type="radio"]),select')?.focus(),0)}
  function closeAlertDialog(){alertDialogBackdrop.hidden=true}
  function updateAlertType(){const type=alertForm.elements['alert-type'].value;Object.entries(alertFieldsets).forEach(([name,element])=>element.hidden=name!==type)}
  function openAlertsPanel(){alertSound.unlock();alertsPanel.classList.add('open');alertsPanel.setAttribute('aria-hidden','false');alertsPanelBackdrop.hidden=false;renderAlertsPanel()}
  function closeAlertsPanel(){alertsPanel.classList.remove('open');alertsPanel.setAttribute('aria-hidden','true');alertsPanelBackdrop.hidden=true}
  alertTypeInputs.forEach(input=>input.addEventListener('change',updateAlertType));
  alertForm.addEventListener('submit',async event=>{event.preventDefault();const type=alertForm.elements['alert-type'].value,mode=alertForm.elements['alert-mode'].value,market=state.selectedMarket;let condition,error='';if(type==='price'){const value=Number(alertForm.elements['price-value'].value);if(!(value>0))error='Enter a price greater than 0.';condition={type:'price',operator:alertForm.elements['price-operator'].value,value}}else if(type==='movement'){const percent=Number(alertForm.elements['movement-percent'].value);if(!(percent>0))error='Enter a movement greater than 0%.';condition={type:'movement',direction:alertForm.elements['movement-direction'].value,percent,window:alertForm.elements['movement-window'].value}}else{const multiplier=Number(alertForm.elements['volume-multiplier'].value);if(!(multiplier>1))error='Choose a multiplier greater than 1x.';condition={type:'volume',multiplier,timeframe:alertForm.elements['volume-timeframe'].value,averageWindow:20}}if(error){alertFormError.textContent=error;return}const result=await alertEngine.create({marketId:market.id,asset:market.asset,baseAsset:market.asset,symbol:market.symbol,exchange:market.exchange,quoteAsset:market.quoteAsset,condition,mode});if(result.error){alertFormError.textContent=result.error;return}closeAlertDialog();openAlertsPanel()});
  document.getElementById('create-alert-button').addEventListener('click',openAlertDialog);document.getElementById('alerts-button').addEventListener('click',openAlertsPanel);document.getElementById('mobile-alerts-button').addEventListener('click',openAlertsPanel);document.querySelector('[data-close-alert-dialog]').addEventListener('click',closeAlertDialog);alertDialogBackdrop.addEventListener('click',event=>{if(event.target===alertDialogBackdrop)closeAlertDialog()});document.querySelector('[data-close-alerts-panel]').addEventListener('click',closeAlertsPanel);alertsPanelBackdrop.addEventListener('click',closeAlertsPanel);
  soundSelect.addEventListener('change',()=>alertSound.setSound(soundSelect.value));soundVolume.addEventListener('change',()=>alertSound.setVolume(soundVolume.value));soundToggle.addEventListener('click',()=>alertSound.setEnabled(!alertSound.enabled));soundTest.addEventListener('click',()=>alertSound.preview(soundSelect.value));
  document.querySelector('.alerts-tabs').addEventListener('click',event=>{const button=event.target.closest('[data-alert-tab]');if(button){alertTab=button.dataset.alertTab;renderAlertsPanel()}});alertsList.addEventListener('click',async event=>{const open=event.target.closest('[data-alert-open]');if(open){openAlertContext(open.dataset.alertOpen,open.dataset.alertTimeframe);return}const action=event.target.closest('[data-alert-action]');if(action){event.stopPropagation();if(action.dataset.alertAction==='dismiss-event'){try{await alertEngine.removeEvent(action.dataset.eventId)}catch{alertMonitorStatus.dataset.status='offline';alertMonitorStatus.lastChild.textContent=' Backend offline'}return}const id=action.dataset.alertId,target=action.dataset.alertAction==='pause'?'paused':action.dataset.alertAction==='resume'?'active':null;hubActions.commit(id,target,{optimistic:target!==null,update:(alertId,status)=>{alertsPanel.dataset.actionRequests=String(Number(alertsPanel.dataset.actionRequests||0)+1);return status===null?alertEngine.deleteAlert(alertId):alertEngine.updateStatus(alertId,status)},apply:status=>{hubOverrides.set(id,status);renderAlertsPanel()},success:()=>{alertEngine.sync({notify:false}).then(()=>{hubOverrides.delete(id);renderAlertsPanel()}).catch(()=>{})},failure:()=>{alertMonitorStatus.dataset.status='offline';alertMonitorStatus.lastChild.textContent=' Backend offline';alertEngine.sync({notify:false}).then(()=>{hubOverrides.delete(id);renderAlertsPanel()}).catch(()=>{})}}).catch(()=>{});return}const row=event.target.closest('[data-alert-context]');if(row)openAlertContext(row.dataset.alertContext,row.dataset.alertTimeframe)});
  updateAlertCounter();renderAlertsPanel();alertEngine.start();

  let snapshotController=null,universeController=null;
  async function refreshSnapshots(){
    snapshotController?.abort();snapshotController=new AbortController();
    const browseAssets=[state.selectedMarket.asset,'BTC','ETH','SOL'],savedMarkets=state.watchlist.map(item=>ZychWatchlist.resolve(item,MARKETS)).filter(Boolean),requestedMarkets=[...new Map(savedMarkets.concat(browseAssets.map(asset=>marketForAsset(asset)).filter(Boolean),state.selectedMarket.unavailable?[]:[state.selectedMarket]).map(market=>[market.id,market])).values()];
    try{const request=snapshotController,groups=Object.groupBy(requestedMarkets,market=>market.exchange),results=await Promise.all(Object.entries(groups).map(async([exchange,markets])=>exchangeAdapters[exchange].snapshots(markets,request.signal)));if(request!==snapshotController)return;const data=Object.assign({},...results);requestedMarkets.forEach(market=>{const snapshot=data[market.id];if(!snapshot)return;state.marketSnapshots[market.id]=snapshot;const key=ZychWatchlist.identity(market);if(ZychWatchlist.contains(state.watchlist,market))updateWatch(key,snapshot);if(market.id===marketForAsset(market.asset)?.id)updatePulse(market.asset,snapshot)});renderMarket()}catch(error){if(error.name!=='AbortError')document.getElementById('retry-button').hidden=false}
  }
  async function loadUniverse(){
    universeController?.abort();universeController=new AbortController();universeStatus='loading';state.loadingState.universe=true;
    try{const loaded=await Promise.allSettled(Object.values(exchangeAdapters).map(async adapter=>({exchange:adapter.id,markets:await adapter.discover(universeController.signal),tickers:await adapter.allSnapshots(universeController.signal).catch(()=>[])}))),successful=loaded.filter(item=>item.status==='fulfilled').map(item=>item.value);if(!successful.length)throw new Error('No exchange catalogs');const previousMarketId=state.selectedMarket.id;normalizeUniverse(successful.flatMap(item=>item.markets));successful.flatMap(item=>item.tickers).forEach(row=>{const market=MARKETS.find(item=>item.id===row.marketId);if(market)state.marketSnapshots[market.id]=row});rebuildCatalogMetrics();document.documentElement.dataset.usdtAssets=String(MARKETS.filter(market=>market.quoteAsset==='USDT').length);document.documentElement.dataset.exchanges=successful.map(item=>item.exchange).join(',');universeStatus='ready';state.loadingState.universe=false;state.errorState.universe=null;saveWatchlist();saveWorkspace();resetWorkspaceSurfaces();renderMarket();if(!searchResults.hidden)drawSearch();if(state.selectedMarket.id!==previousMarketId)loadMarket();const resolved=await ZychMarketContext.resolveLocation(location.search).catch(()=>null);if(resolved?.context)openMarketContext(resolved.context);await refreshSnapshots()}
    catch(error){if(error.name==='AbortError')return;universeStatus='error';state.loadingState.universe=false;state.errorState.universe='Market universe unavailable';if(!searchResults.hidden)drawSearch()}
  }
  document.getElementById('retry-button').addEventListener('click',()=>{refreshSnapshots();loadMarket();if(universeStatus==='error')loadUniverse()});const snapshotTimer=setInterval(refreshSnapshots,60000);window.addEventListener('beforeunload',()=>{clearInterval(snapshotTimer);clearTimeout(searchTimer);clearTimeout(historyStatusTimer);snapshotController?.abort();universeController?.abort();stopMarket();alertEngine.stop()});
  renderWatchlist();renderMarket();refreshSnapshots();loadMarket();loadUniverse();
})();
