/* ZYCH Markets browser bundle. Keeps direct file:// and HTTP startup equivalent. */
(() => {
  'use strict';

  const DEFAULT_WATCHLIST = ['BTC','ETH','SOL','BNB','XRP','ADA','DOGE'];
  const QUOTE_PRIORITY = ['USDT', 'USDC', 'FDUSD', 'BTC', 'ETH'];
  const POPULAR_ASSETS = ['BTC','ETH','BNB','SOL','XRP','ADA','DOGE','TRX','LINK','AVAX','SUI','DOT','LTC','BCH','UNI','NEAR','AAVE','PEPE','ARB'];
  const STORAGE_KEY = 'zych.watchlist.v1';
  const FAVORITE_HINT_KEY = 'zych.favorite-hint.v1';
  const WORKSPACE_KEY = 'zych.exchange-workspace.v1';
  const ASSETS = {
    BTC:{name:'Bitcoin',icon:'₿',className:'btc'},ETH:{name:'Ethereum',icon:'◆',className:'eth'},SOL:{name:'Solana',icon:'S',className:'sol'},
    BNB:{name:'BNB',icon:'◆',className:'bnb'},XRP:{name:'XRP',icon:'X',className:'xrp'},ADA:{name:'Cardano',icon:'A',className:'ada'},DOGE:{name:'Dogecoin',icon:'Ð',className:'doge'},
    LINK:{name:'Chainlink',icon:'L',className:'generic'},SUI:{name:'Sui',icon:'S',className:'generic'},ARB:{name:'Arbitrum',icon:'A',className:'generic'},PEPE:{name:'Pepe',icon:'P',className:'generic'},AVAX:{name:'Avalanche',icon:'A',className:'generic'},TRX:{name:'TRON',icon:'T',className:'generic'},
    DOT:{name:'Polkadot',icon:'D',className:'generic'},LTC:{name:'Litecoin',icon:'Ł',className:'generic'},BCH:{name:'Bitcoin Cash',icon:'B',className:'generic'},TON:{name:'Toncoin',icon:'T',className:'generic'},SHIB:{name:'Shiba Inu',icon:'S',className:'generic'},UNI:{name:'Uniswap',icon:'U',className:'generic'},NEAR:{name:'NEAR Protocol',icon:'N',className:'generic'},APT:{name:'Aptos',icon:'A',className:'generic'}
  };
  let MARKETS = DEFAULT_WATCHLIST.flatMap(asset => ['binance','bybit'].map(exchange => ZychInstruments.normalize({exchange,marketType:'spot',symbol:`${asset}USDT`,baseAsset:asset,quoteAsset:'USDT',enabled:true,status:'TRADING'}))).concat(DEFAULT_WATCHLIST.map(asset=>ZychInstruments.normalize({exchange:'okx',marketType:'spot',symbol:`${asset}-USDT`,baseAsset:asset,quoteAsset:'USDT',enabled:true,status:'live'})));
  const EXCHANGES={binance:{label:'Binance'},bybit:{label:'Bybit'},okx:{label:'OKX'}};
  const TIMEFRAMES=['1m','5m','15m','30m','1h','4h','1d','1w','1M'];
  let assetIndex=new Map(),universeStatus='loading',catalogLiquidity=new Map(),catalogSnapshots=new Map();
  function rebuildAssetIndex(){assetIndex=new Map();MARKETS.forEach(market=>{if(!assetIndex.has(market.asset))assetIndex.set(market.asset,[]);assetIndex.get(market.asset).push(market)});assetIndex.forEach(markets=>markets.sort((a,b)=>QUOTE_PRIORITY.indexOf(a.quoteAsset)-QUOTE_PRIORITY.indexOf(b.quoteAsset)))}
  rebuildAssetIndex();
  const marketForAssetOnExchange=(asset,exchange,quoteAsset='USDT')=>ZychWorkspace.marketForAsset(assetIndex.get(asset)||[],asset,exchange,quoteAsset);
  const marketsForAsset=asset=>[...(assetIndex.get(asset)||[])];
  const marketLabel=market=>`${market.baseAsset} / ${market.quoteAsset}`;
  const formatPrice=value=>{const number=Number(value);if(!Number.isFinite(number))return'—';const digits=number>=1?2:number>=.1?4:number>=.01?5:number>=.001?6:8;return number.toLocaleString(ZychI18n.locale(),{minimumFractionDigits:digits,maximumFractionDigits:digits})};
  const formatPercent=value=>{if(value===null||value===undefined||typeof value==='string'&&!value.trim())return'—';const number=Number(value);return Number.isFinite(number)?`${number>=0?'+':'−'}${Math.abs(number).toFixed(2)}%`:'—'};
  const formatCompact=value=>Number.isFinite(Number(value))?new Intl.NumberFormat(ZychI18n.locale(),{notation:'compact',maximumFractionDigits:2}).format(Number(value)):'—';
  const escapeHtml=value=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const applyDirection=(element,value)=>{element.classList.remove('positive','negative');if(Number.isFinite(Number(value)))element.classList.add(Number(value)>=0?'positive':'negative')};
  const assetMeta=asset=>ASSETS[asset]||{name:asset,icon:asset.slice(0,1),className:'generic'};
  const iconMarkup=(meta,size='tiny')=>`<i class="coin-icon ${escapeHtml(meta.className)} ${escapeHtml(size)}">${escapeHtml(meta.icon)}</i>`;
  function storedWatchlist(exchange){try{const value=JSON.parse(localStorage.getItem(STORAGE_KEY));return ZychWatchlist.migrate(Array.isArray(value)?value:null,{markets:MARKETS,exchange,defaults:DEFAULT_WATCHLIST})}catch{return ZychWatchlist.migrate(null,{markets:MARKETS,exchange,defaults:DEFAULT_WATCHLIST})}}
  function saveWatchlist(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state.watchlist))}catch{}}
  function hasStoredWatchlist(){try{return localStorage.getItem(STORAGE_KEY)!==null}catch{return false}}
  function favoriteHintSeen(){try{return localStorage.getItem(FAVORITE_HINT_KEY)==='seen'}catch{return true}}
  function dismissFavoriteHint(){try{localStorage.setItem(FAVORITE_HINT_KEY,'seen')}catch{}}
  function storedWorkspace(){try{const value=JSON.parse(localStorage.getItem(WORKSPACE_KEY)||'{}');return{exchange:ZychWorkspace.validExchange(value.exchange),marketId:typeof value.marketId==='string'?value.marketId:'',asset:typeof value.asset==='string'&&value.asset?value.asset:'BTC',quoteAsset:typeof value.quoteAsset==='string'&&value.quoteAsset?value.quoteAsset:'USDT',timeframe:TIMEFRAMES.includes(value.timeframe)?value.timeframe:'1h'}}catch{return{exchange:'binance',marketId:'',asset:'BTC',quoteAsset:'USDT',timeframe:'1h'}}}
  const workspacePreference=storedWorkspace(),initialMarket=MARKETS.find(market=>market.id===workspacePreference.marketId&&market.exchange===workspacePreference.exchange)||marketForAssetOnExchange(workspacePreference.asset,workspacePreference.exchange,workspacePreference.quoteAsset)||ZychWorkspace.unavailableMarket(workspacePreference.asset,workspacePreference.exchange,workspacePreference.quoteAsset);

  const state={activeExchange:workspacePreference.exchange,selectedMarket:initialMarket,selectedTimeframe:workspacePreference.timeframe,watchlist:storedWatchlist(workspacePreference.exchange),marketSnapshots:{},connectionStatus:'CONNECTING',loadingState:{universe:true,snapshots:true,chart:true},errorState:{universe:null,snapshots:null,chart:null}};
  const marketForAsset=asset=>marketForAssetOnExchange(asset,state.activeExchange,state.selectedMarket?.quoteAsset||'USDT');
  function saveWorkspace(){try{localStorage.setItem(WORKSPACE_KEY,JSON.stringify(ZychWorkspace.preference(state)))}catch{}}
  const updateSnapshot=(id,patch)=>{state.marketSnapshots={...state.marketSnapshots,[id]:{...(state.marketSnapshots[id]||{}),...patch}}};

  const exchangeAdapters=ZychExchanges.adapters;
  ZychI18n.apply();
  const marketSockets=new Set();
  const updateSocketDiagnostics=()=>{document.documentElement.dataset.marketSockets=String(marketSockets.size)};
  const historyService=new ZychChartHistory.ChartHistoryService({adapters:exchangeAdapters});

  function normalizeUniverse(markets){
    const leveraged=/(UP|DOWN|BULL|BEAR)$/;
    const safeTicker=value=>typeof value==='string'&&/^[A-Z0-9]{1,20}$/.test(value),safeSymbol=value=>typeof value==='string'&&/^[A-Z0-9-]{1,30}$/.test(value);
    MARKETS=markets.map(row=>ZychInstruments.normalize(row)).filter(row=>row&&row.enabled&&safeSymbol(row.symbol)&&safeTicker(row.baseAsset)&&safeTicker(row.quoteAsset)&&QUOTE_PRIORITY.includes(row.quoteAsset)&&!leveraged.test(row.baseAsset));
    rebuildAssetIndex();
    document.documentElement.dataset.universeMarkets=String(MARKETS.length);document.documentElement.dataset.universeAssets=String(assetIndex.size);
    state.watchlist=ZychWatchlist.migrate(state.watchlist,{markets:MARKETS,exchange:state.activeExchange,defaults:hasStoredWatchlist()?[]:DEFAULT_WATCHLIST});
    const current=state.selectedMarket,resolved=MARKETS.find(market=>market.id===current.id&&market.exchange===state.activeExchange)||marketForAssetOnExchange(current.asset,state.activeExchange,current.quoteAsset);state.selectedMarket=resolved||ZychWorkspace.unavailableMarket(current.asset,state.activeExchange,current.quoteAsset);
  }
  const liquidityForAsset=asset=>catalogLiquidity.get(asset)||0;
  const catalogMetric=(asset,key)=>catalogSnapshots.get(asset)?.[key];
  function rebuildCatalogMetrics(){catalogLiquidity=new Map();catalogSnapshots=new Map();assetIndex.forEach((_markets,asset)=>{const market=marketForAsset(asset),snapshot=market&&state.marketSnapshots[market.id];if(snapshot){catalogLiquidity.set(asset,snapshot.volume||0);catalogSnapshots.set(asset,snapshot)}})}
  function searchUniverse(query,mode='top'){
    const value=query.trim().toUpperCase(),assets=[...assetIndex.keys()];
    const matches=value?assets.filter(asset=>asset.includes(value)||(assetMeta(asset).name||'').toUpperCase().includes(value)||(assetIndex.get(asset)||[]).some(market=>market.symbol.startsWith(value))):assets;
    return matches.sort((a,b)=>{const exact=(b===value)-(a===value);if(exact)return exact;const prefix=(b.startsWith(value)?1:0)-(a.startsWith(value)?1:0);if(prefix)return prefix;if(mode==='volume')return liquidityForAsset(b)-liquidityForAsset(a)||a.localeCompare(b);if(mode==='gainers')return (catalogMetric(b,'changePercent')??-Infinity)-(catalogMetric(a,'changePercent')??-Infinity)||liquidityForAsset(b)-liquidityForAsset(a);if(mode==='losers')return (catalogMetric(a,'changePercent')??Infinity)-(catalogMetric(b,'changePercent')??Infinity)||liquidityForAsset(b)-liquidityForAsset(a);const popularA=POPULAR_ASSETS.indexOf(a),popularB=POPULAR_ASSETS.indexOf(b),popular=(popularA<0?999:popularA)-(popularB<0?999:popularB);if(popular)return popular;return liquidityForAsset(b)-liquidityForAsset(a)||a.localeCompare(b)})
  }

  let activeController=null,activeSocket=null,reconnectTimer=null,generation=0,intentionalClose=false;
  function stopMarket(){intentionalClose=true;activeController?.abort();activeController=null;clearTimeout(reconnectTimer);reconnectTimer=null;if(activeSocket&&activeSocket.readyState<WebSocket.CLOSING)activeSocket.close(1000,'Market changed');activeSocket=null}
  function openLive(context){const{market,timeframe,token,onCandle,onStatus}=context,adapter=exchangeAdapters[market.exchange];intentionalClose=false;let socket=null;socket=adapter.socket(market,timeframe,{open:()=>{marketSockets.add(socket);updateSocketDiagnostics();token===generation&&onStatus('LIVE')},candle:candle=>token===generation&&onCandle(candle),error:()=>token===generation&&onStatus('OFFLINE'),close:()=>{marketSockets.delete(socket);updateSocketDiagnostics();if(intentionalClose||token!==generation)return;onStatus('RECONNECTING');reconnectTimer=setTimeout(()=>token===generation&&openLive(context),2500)}});activeSocket=socket}
  async function selectMarketData(market,timeframe,handlers){
    stopMarket();const token=++generation;activeController=new AbortController();handlers.onStatus('CONNECTING');
    try{const result=await historyService.initial(market,timeframe,activeController.signal);if(token!==generation)return;handlers.onCandles(result.data,result);openLive({market,timeframe,token,onCandle:handlers.onCandle,onStatus:handlers.onStatus})}
    catch(error){if(error.name==='AbortError'||token!==generation)return;handlers.onStatus('OFFLINE');handlers.onError(error)}
  }

  const chartContainer=document.getElementById('chart'),chartState=document.getElementById('chart-state'),chartHistoryState=document.getElementById('chart-history-state');
  const chart=LightweightCharts.createChart(chartContainer,{width:chartContainer.clientWidth,height:chartContainer.clientHeight,layout:{background:{color:'#0d1014'},textColor:'#747d86',attributionLogo:true},grid:{vertLines:{color:'#181d23'},horzLines:{color:'#181d23'}},rightPriceScale:{borderColor:'#252c33',scaleMargins:{top:.08,bottom:.22}},timeScale:{borderColor:'#252c33',timeVisible:true,secondsVisible:false}});
  const themeMarketColor=(property,fallback)=>getComputedStyle(document.documentElement).getPropertyValue(property).trim()||fallback;
  const bullishColor=()=>themeMarketColor('--positive','#2bc477'),bearishColor=()=>themeMarketColor('--negative','#ed515b');
  const candleOptions={upColor:bullishColor(),downColor:bearishColor(),borderUpColor:bullishColor(),borderDownColor:bearishColor(),wickUpColor:bullishColor(),wickDownColor:bearishColor(),priceLineColor:bullishColor()};
  const candles=chart.addSeries?chart.addSeries(LightweightCharts.CandlestickSeries,candleOptions):chart.addCandlestickSeries(candleOptions);
  const volumeOptions={priceFormat:{type:'volume'},priceScaleId:'',lastValueVisible:false,priceLineVisible:false};
  const volumes=chart.addSeries?chart.addSeries(LightweightCharts.HistogramSeries,volumeOptions):chart.addHistogramSeries(volumeOptions);volumes.priceScale().applyOptions({scaleMargins:{top:.82,bottom:0}});
  const volumePoint=candle=>({time:candle.time,value:candle.volume,color:candle.close>=candle.open?'rgba(43,196,119,.34)':'rgba(237,81,91,.32)'});
  const updatePriceDirection=candle=>{if(!candle)return;const direction=Number(candle.close)>=Number(candle.open)?'bullish':'bearish';candles.applyOptions({priceLineColor:direction==='bullish'?bullishColor():bearishColor()});chartContainer.dataset.priceDirection=direction};
  new ResizeObserver(entries=>{const{width,height}=entries[0].contentRect;chart.applyOptions({width,height})}).observe(chartContainer);
  const updateChartDiagnostics=(data,key,pages)=>{chartContainer.dataset.historyKey=key||'';chartContainer.dataset.candleCount=String(data.length);chartContainer.dataset.oldestTime=String(data[0]?.time||'');chartContainer.dataset.newestTime=String(data.at(-1)?.time||'');chartContainer.dataset.historyPages=String(pages||0)};
  const chartApi={
    setData:(data,key,pages)=>{candles.setData(data);volumes.setData(data.map(volumePoint));updatePriceDirection(data.at(-1));const latestFrom=Math.max(0,data.length-180);chart.timeScale().setVisibleLogicalRange({from:latestFrom,to:data.length+5});updateChartDiagnostics(data,key,pages)},
    clear:()=>{candles.setData([]);volumes.setData([]);updateChartDiagnostics([], '', 0)},
    prepend:(data,added,range,key,pages)=>{candles.setData(data);volumes.setData(data.map(volumePoint));updatePriceDirection(data.at(-1));if(range&&added>0)chart.timeScale().setVisibleLogicalRange({from:range.from+added,to:range.to+added});updateChartDiagnostics(data,key,pages)},
    update:candle=>{candles.update(candle);volumes.update(volumePoint(candle));updatePriceDirection(candle);chartContainer.dataset.newestTime=String(candle.time)},
    range:()=>chart.timeScale().getVisibleLogicalRange(),subscribe:handler=>chart.timeScale().subscribeVisibleLogicalRangeChange(handler),
    loading:text=>{chartState.textContent=text;chartState.hidden=false},ready:()=>{chartState.hidden=true}
  };
  let historyContext=null,historyLoading=false,historyStatusTimer=null;
  const setHistoryStatus=(text,status='loading',linger=0)=>{clearTimeout(historyStatusTimer);chartHistoryState.textContent=text;chartHistoryState.dataset.status=status;chartHistoryState.hidden=!text;if(linger)historyStatusTimer=setTimeout(()=>{chartHistoryState.hidden=true},linger)};
  async function loadOlderHistory(){
    const context=historyContext;if(!context||historyLoading||context.endReached||!activeController||activeController.signal.aborted)return;
    historyLoading=true;const range=chartApi.range();setHistoryStatus('Loading history…');
    try{const result=await historyService.older(context.market,context.timeframe,activeController.signal);if(historyContext!==context||context.token!==generation)return;context.endReached=result.endReached;chartApi.prepend(result.data,result.added,range,result.key,result.pages);if(result.endReached)setHistoryStatus('Start of available history','end',2600);else setHistoryStatus('', 'idle')}
    catch(error){if(error.name!=='AbortError'&&historyContext===context)setHistoryStatus('History load failed','error',2600)}
    finally{if(historyContext===context)historyLoading=false}
  }
  chartApi.subscribe(range=>{if(range&&range.from<120)loadOlderHistory()});

  const watchContainer=document.getElementById('watchlist-rows'),watchTileContainer=document.getElementById('watchlist-tile-view'),watchTableView=document.getElementById('watchlist-table-view');
  const watchUiState={filter:'all',exchange:'all',sort:'default',view:'table'};let watchRadarState=null;
  const watchItems=()=>state.watchlist.map(item=>({item,market:ZychWatchlist.resolve(item,MARKETS)})).filter(entry=>entry.market).filter(entry=>watchUiState.filter==='all'||entry.market.marketType===watchUiState.filter).filter(entry=>watchUiState.exchange==='all'||entry.market.exchange===watchUiState.exchange).sort((a,b)=>{if(watchUiState.sort==='default')return 0;const av=Number(state.marketSnapshots[a.market.id]?.changePercent),bv=Number(state.marketSnapshots[b.market.id]?.changePercent),safeA=Number.isFinite(av)?av:(watchUiState.sort==='change-desc'?-Infinity:Infinity),safeB=Number.isFinite(bv)?bv:(watchUiState.sort==='change-desc'?-Infinity:Infinity);return watchUiState.sort==='change-desc'?safeB-safeA:safeA-safeB});
  const watchSummary=()=>{const snapshots=state.watchlist.map(item=>ZychWatchlist.resolve(item,MARKETS)).filter(Boolean).map(market=>state.marketSnapshots[market.id]).filter(snapshot=>Number.isFinite(Number(snapshot?.changePercent))),gainers=snapshots.filter(snapshot=>Number(snapshot.changePercent)>0).length,losers=snapshots.filter(snapshot=>Number(snapshot.changePercent)<0).length;return{verified:snapshots.length,gainers,losers}};
  function renderWatchSummary(){const summary=watchSummary(),ratio=count=>summary.verified?`${count} (${(count/summary.verified*100).toFixed(0)}%)`:'—',total=document.getElementById('watchlist-total'),gainers=document.getElementById('watchlist-gainers'),losers=document.getElementById('watchlist-losers'),snapshots=state.watchlist.map(item=>ZychWatchlist.resolve(item,MARKETS)).filter(Boolean).map(market=>state.marketSnapshots[market.id]).filter(Boolean),timestamps=snapshots.map(snapshot=>Number(snapshot.snapshotTimestamp)).filter(Number.isFinite),updated=timestamps.length?Math.max(...timestamps):null,radarCount=document.getElementById('watchlist-radar-events'),radarStatus=document.getElementById('watchlist-radar-status');total.textContent=String(state.watchlist.length);gainers.textContent=ratio(summary.gainers);losers.textContent=ratio(summary.losers);applyDirection(gainers,summary.verified?1:null);applyDirection(losers,summary.verified?-1:null);document.getElementById('watchlist-updated').textContent=updated?radarTime(updated):'—';const radarAvailable=Boolean(watchRadarState?.lastSuccessfulFetch);radarCount.textContent=radarAvailable?String(watchRadarState.events.length):'—';radarStatus.textContent=radarAvailable?ZychRadarEvent.status(watchRadarState).label:ZychI18n.t('common.unavailable')}
  const watchRadarEvent=market=>watchRadarState?.events.filter(event=>event.marketId===market.id).sort((a,b)=>b.eventTimestamp-a.eventTimestamp)[0]||null;
  const watchRowMarkup=({item,market})=>{const snapshot=state.marketSnapshots[market.id],radarEvent=watchRadarEvent(market),meta=assetMeta(market.asset),safeKey=escapeHtml(item.key),safeMarket=escapeHtml(market.id),exchange=EXCHANGES[market.exchange]?.label||market.exchange,type=ZychI18n.t(`market.${market.marketType||'spot'}`),change=snapshot?.changePercent,direction=Number.isFinite(Number(change))?(Number(change)>=0?'positive':'negative'):'',high=Number.isFinite(Number(snapshot?.high))?formatPrice(snapshot.high):'—',low=Number.isFinite(Number(snapshot?.low))?formatPrice(snapshot.low):'—',volume=Number.isFinite(Number(snapshot?.volume))?formatCompact(snapshot.volume):'—',score=Number.isFinite(radarEvent?.score)?String(radarEvent.score):'—',scoreState=radarEvent?radarEvent.interpretationLabel||radarEvent.setupType:ZychI18n.t('watchlist.noEvent');return `<div class="watchlist-data-row ${snapshot?'':'loading'}" role="row" tabindex="0" data-watch-key="${safeKey}" data-market-id="${safeMarket}"><button class="watchlist-favorite" type="button" data-remove-watch="${safeKey}" aria-label="${escapeHtml(ZychI18n.t('watchlist.remove'))}">★</button><span class="watchlist-symbol">${iconMarkup(meta)}<span><b>${escapeHtml(market.displaySymbol)}</b><small>${escapeHtml(meta.name)}</small></span></span><span class="watchlist-exchange">${escapeHtml(exchange)}</span><span class="watchlist-market-type">${escapeHtml(type)}</span><span class="watchlist-score"><i>${escapeHtml(score)}</i><small>${escapeHtml(scoreState)}</small></span><span class="watchlist-price">${snapshot?formatPrice(snapshot.lastPrice):'—'}</span><span class="watchlist-change ${direction}">${formatPercent(change)}<small>${escapeHtml(ZychI18n.t('watchlist.sparklineUnavailable'))}</small></span><span class="watchlist-range">${high}<small>${low}</small></span><span class="watchlist-volume">${volume}</span><span class="watchlist-unavailable" title="Source not connected">—<small>Not connected</small></span><span class="watchlist-unavailable" title="Source not connected">—<small>Not connected</small></span><span class="watchlist-row-actions"><button type="button" data-watch-chart="${safeMarket}" aria-label="${escapeHtml(ZychI18n.t('watchlist.openChart'))}">▥</button><button type="button" data-watch-alert="${safeMarket}" aria-label="${escapeHtml(ZychI18n.t('watchlist.quickAlert'))}">♢</button><button type="button" disabled title="More actions are not available" aria-label="${escapeHtml(ZychI18n.t('watchlist.more'))}">⋮</button></span></div>`};
  const watchTileMarkup=({item,market})=>{const snapshot=state.marketSnapshots[market.id],radarEvent=watchRadarEvent(market),meta=assetMeta(market.asset),change=snapshot?.changePercent,direction=Number.isFinite(Number(change))?(Number(change)>=0?'positive':'negative'):'',exchange=EXCHANGES[market.exchange]?.label||market.exchange,score=Number.isFinite(radarEvent?.score)?String(radarEvent.score):'—',eventLabel=radarEvent?radarEvent.interpretationLabel||radarEvent.setupType:ZychI18n.t('watchlist.noEvent');return `<article class="watchlist-tile" tabindex="0" data-market-id="${escapeHtml(market.id)}" data-watch-key="${escapeHtml(item.key)}"><header class="watchlist-tile-top">${iconMarkup(meta)}<span class="watchlist-tile-identity"><b>${escapeHtml(market.displaySymbol)}</b><small>${escapeHtml(exchange)}</small></span><span class="watchlist-tile-score"><i>${escapeHtml(score)}</i></span></header><div class="watchlist-sparkline-unavailable"><span>${escapeHtml(ZychI18n.t('watchlist.sparklineUnavailable'))}</span></div><footer class="watchlist-tile-market"><div class="watchlist-tile-price"><strong>${snapshot?formatPrice(snapshot.lastPrice):'—'}</strong><span class="${direction}">${formatPercent(change)}</span></div><div class="watchlist-tile-event"><small>Radar</small><b>${escapeHtml(eventLabel)}</b></div></footer></article>`};
  function renderWatchlist(){
    const entries=watchItems(),empty=`<div class="watchlist-empty-state"><div>${escapeHtml(ZychI18n.t('watchlist.empty'))}<br><button type="button" data-open-search>${escapeHtml(ZychI18n.t('watchlist.find'))}</button></div></div>`;
    watchContainer.dataset.exchange=watchUiState.exchange;watchContainer.innerHTML=entries.length?entries.map(watchRowMarkup).join(''):empty;watchTileContainer.innerHTML=entries.length?entries.map(watchTileMarkup).join(''):empty;
    watchTableView.hidden=false;document.querySelectorAll('[data-watch-view]').forEach(button=>button.classList.toggle('active',button.dataset.watchView==='table'));document.querySelectorAll('[data-watch-filter]').forEach(button=>button.classList.toggle('active',button.dataset.watchFilter===watchUiState.filter));
    document.querySelectorAll('[data-watch-count]').forEach(node=>node.textContent=String(state.watchlist.length));document.querySelectorAll('[data-watch-spot-count]').forEach(node=>node.textContent=String(state.watchlist.filter(item=>(item.marketType||'spot')==='spot').length));document.getElementById('watchlist-showing').textContent=ZychI18n.t('watchlist.showing').replace('{shown}',String(entries.length)).replace('{total}',String(state.watchlist.length));renderWatchSummary();selectWatch(state.selectedMarket.id);const radarCount=document.getElementById('radar-watchlist-count');if(radarCount)radarCount.textContent=String(state.watchlist.length);
  }
  const updateWatch=(key,snapshot)=>{if(!snapshot)return;renderWatchlist()};
  const selectWatch=marketId=>document.querySelectorAll('#watchlist-workspace [data-market-id]').forEach(row=>row.classList.toggle('active',row.dataset.marketId===marketId));

  const pulseCards=[...document.querySelectorAll('[data-pulse-asset]')],radarCards=[...document.querySelectorAll('[data-radar-asset]')];
  const updatePulse=(asset,snapshot)=>{const card=pulseCards.find(item=>item.dataset.pulseAsset===asset);if(card&&snapshot){card.querySelector('strong').textContent=`$${formatPrice(snapshot.lastPrice)}`;const change=card.querySelector('.pulse-copy>span');change.textContent=formatPercent(snapshot.changePercent);applyDirection(change,snapshot.changePercent)}const radar=radarCards.find(item=>item.dataset.radarAsset===asset);if(radar&&snapshot){radar.querySelector('strong').textContent=`$${formatPrice(snapshot.lastPrice)}`;const change=radar.querySelector('em');change.textContent=formatPercent(snapshot.changePercent);applyDirection(change,snapshot.changePercent)}};

  const workspaceButton=document.getElementById('active-exchange-selector'),workspaceMenu=document.getElementById('active-exchange-menu');
  function renderActiveExchange(){workspaceMenu.querySelectorAll('[data-active-exchange-option]').forEach(button=>button.classList.toggle('active',button.dataset.activeExchangeOption===state.activeExchange));const label=document.getElementById('active-exchange-button-label');if(label)label.textContent=EXCHANGES[state.activeExchange]?.label||state.activeExchange;document.documentElement.dataset.activeExchange=state.activeExchange}
  function resetWorkspaceSurfaces(){renderWatchlist();pulseCards.forEach(card=>{const market=marketForAsset(card.dataset.pulseAsset),snapshot=market&&state.marketSnapshots[market.id],price=card.querySelector('strong'),change=card.querySelector('.pulse-copy>span');price.textContent=snapshot?`$${formatPrice(snapshot.lastPrice)}`:'—';change.textContent=snapshot?formatPercent(snapshot.changePercent):'—';applyDirection(change,snapshot?.changePercent)});rebuildCatalogMetrics();renderMarketsDashboard()}
  const marketsUi={query:'',quote:'all',sort:'volume-desc',limit:25};
  const marketsElements={pulse:document.getElementById('markets-pulse'),totalVolume:document.getElementById('markets-total-volume'),gainers:document.getElementById('markets-gainers'),losers:document.getElementById('markets-losers'),volume:document.getElementById('markets-volume'),heatmap:document.getElementById('markets-heatmap'),rows:document.getElementById('markets-rows'),count:document.getElementById('markets-count'),showing:document.getElementById('markets-showing'),loadMore:document.getElementById('markets-load-more'),status:document.getElementById('markets-data-status'),exchange:document.getElementById('markets-active-exchange'),updated:document.getElementById('markets-last-update')};
  const marketsItems=()=>MARKETS.filter(market=>market.enabled&&market.exchange===state.activeExchange&&market.marketType==='spot').map(market=>ZychMarketsData.item(market,state.marketSnapshots[market.id],ZychWatchlist.contains(state.watchlist,market)));
  const marketsState=items=>{if(universeStatus==='loading')return{code:'loading',label:'Loading'};if(universeStatus==='error'||!items.length)return{code:'unavailable',label:'Unavailable'};const available=items.filter(item=>item.price!==null&&item.snapshotTimestamp!==null).length;return available===items.length?{code:'current',label:'Current'}:available?{code:'partial',label:'Partial'}:{code:'unavailable',label:'Unavailable'}};
  const marketsEmpty=message=>`<div class="markets-empty">${escapeHtml(message)}</div>`;
  const marketsMiniRows=items=>items.length?items.map((item,index)=>`<button type="button" data-markets-open="${escapeHtml(item.marketId)}"><span>${index+1}</span><b>${escapeHtml(item.displaySymbol)}</b><em>${item.price===null?'—':formatPrice(item.price)}</em><strong class="${item.change24h===null?'':item.change24h>=0?'positive':'negative'}">${formatPercent(item.change24h)}</strong><small>${item.quoteVolume24h===null?'—':formatCompact(item.quoteVolume24h)}</small></button>`).join(''):marketsEmpty('No verified 24h metrics');
  function renderMarketsDashboard(){
    if(!marketsElements.pulse)return;const items=marketsItems(),quality=marketsState(items),snapshots=items.map(item=>item.snapshotTimestamp).filter(Number.isFinite),updated=snapshots.length?Math.max(...snapshots):null,breadth=ZychMarketsData.breadth(items),volumeValues=items.map(item=>item.quoteVolume24h).filter(Number.isFinite),totalVolume=items.length&&volumeValues.length===items.length?volumeValues.reduce((sum,value)=>sum+value,0):null,gaugeCard=label=>`<article class="markets-pulse-card markets-source-missing markets-gauge-slot"><b>${label}</b><i class="unavailable-gauge" aria-hidden="true"><span>—</span></i><em>SOURCE NOT CONNECTED</em></article>`,plainCard=label=>`<article class="markets-pulse-card markets-source-missing"><span><b>${label}</b><strong>—</strong><em>SOURCE NOT CONNECTED</em></span></article>`,breadthMarkup=`<article class="markets-pulse-card markets-breadth markets-real-card"><span><b>Market Breadth <small>(24h)</small></b><strong>${breadth.total?`<i class="positive">${Math.round(breadth.risingPct)}% <small>Rising</small></i><i class="negative">${Math.round(breadth.fallingPct)}% <small>Falling</small></i>`:'—'}</strong><em>${breadth.total?`${breadth.rising} rising · ${breadth.falling} falling · ${breadth.total} verified`:'Awaiting verified metrics'}</em></span><div><i style="width:${breadth.risingPct??0}%"></i></div></article>`;
    marketsElements.pulse.innerHTML=plainCard('Total Crypto Cap')+plainCard('BTC Dominance')+breadthMarkup+gaugeCard('Fear & Greed Index')+gaugeCard('Altseason Index')+plainCard('Market Mode');if(marketsElements.totalVolume)marketsElements.totalVolume.textContent=totalVolume===null?'—':formatCompact(totalVolume);marketsElements.gainers.innerHTML=marketsMiniRows(ZychMarketsData.rank(items,'change24h','desc',5).filter(item=>item.change24h>0));marketsElements.losers.innerHTML=marketsMiniRows(ZychMarketsData.rank(items,'change24h','asc',5).filter(item=>item.change24h<0));marketsElements.volume.innerHTML=marketsMiniRows(ZychMarketsData.rank(items,'quoteVolume24h','desc',5));
    const heat=ZychMarketsData.rank(items,'quoteVolume24h','desc',12),volumeLogs=heat.map(item=>Math.log1p(Math.max(0,item.quoteVolume24h))),minimumLog=volumeLogs.length?Math.min(...volumeLogs):0,maximumLog=volumeLogs.length?Math.max(...volumeLogs):0,logRange=maximumLog-minimumLog;marketsElements.heatmap.innerHTML=heat.length?heat.map((item,index)=>{const scale=logRange?(volumeLogs[index]-minimumLog)/logRange:.5,columns=4+Math.round(scale*8),rows=scale>=.72?2:1,tone=item.change24h===null?'neutral':item.change24h>=0?'up':'down';return`<button type="button" class="${tone} heat-size-${columns}${rows===2?' heat-tall':''}" data-markets-open="${escapeHtml(item.marketId)}"><b>${escapeHtml(item.baseAsset)}</b><span>${formatPercent(item.change24h)}</span></button>`}).join(''):marketsEmpty('No verified volume data');
    let filtered=items;if(marketsUi.query)filtered=ZychInstruments.search(filtered,marketsUi.query,{limit:500}).map(found=>items.find(item=>item.marketId===found.id)).filter(Boolean);if(marketsUi.quote!=='all')filtered=filtered.filter(item=>item.quoteAsset===marketsUi.quote);if(marketsUi.sort==='symbol-asc')filtered.sort((a,b)=>a.displaySymbol.localeCompare(b.displaySymbol)||a.marketId.localeCompare(b.marketId));else{const[key,direction]=marketsUi.sort.split('-');filtered.sort(ZychMarketsData.compareNumber(key==='volume'?'quoteVolume24h':key==='change'?'change24h':key,direction))}
    const visible=filtered.slice(0,marketsUi.limit);marketsElements.rows.innerHTML=visible.length?visible.map(item=>`<div class="markets-data-row" role="row" data-market-id="${escapeHtml(item.marketId)}"><span><b>${escapeHtml(item.displaySymbol)}</b><small>${escapeHtml(item.nativeSymbol)}</small></span><span>Spot</span><span>${item.price===null?'—':formatPrice(item.price)}</span><span class="${item.change24h===null?'':item.change24h>=0?'positive':'negative'}">${formatPercent(item.change24h)}</span><span>${item.quoteVolume24h===null?'—':formatCompact(item.quoteVolume24h)}</span><button type="button" class="markets-watch ${item.watchlisted?'active':''}" data-markets-watch="${escapeHtml(item.marketId)}" aria-label="${item.watchlisted?'Remove from':'Add to'} Watchlist">${item.watchlisted?'★':'☆'}</button><button type="button" class="markets-open" data-markets-open="${escapeHtml(item.marketId)}">Open</button></div>`).join(''):marketsEmpty(marketsUi.query?'No matching markets':'No markets available');
    marketsElements.count.textContent=`${filtered.length} matching · ${items.length} total real Spot markets`;marketsElements.showing.textContent=`Showing ${visible.length} of ${filtered.length}`;marketsElements.loadMore.hidden=visible.length>=filtered.length;marketsElements.status.dataset.status=quality.code;marketsElements.status.innerHTML=`<i></i> ${quality.label}`;marketsElements.exchange.textContent=EXCHANGES[state.activeExchange]?.label||state.activeExchange;marketsElements.updated.textContent=updated?new Date(updated).toLocaleTimeString(ZychI18n.locale(),{hour:'2-digit',minute:'2-digit',second:'2-digit'}):'—';
  }
  document.getElementById('markets-search')?.addEventListener('input',event=>{marketsUi.query=event.target.value.trim();marketsUi.limit=25;renderMarketsDashboard()});document.getElementById('markets-quote-filter')?.addEventListener('change',event=>{marketsUi.quote=event.target.value;marketsUi.limit=25;renderMarketsDashboard()});document.getElementById('markets-sort')?.addEventListener('change',event=>{marketsUi.sort=event.target.value;marketsUi.limit=25;renderMarketsDashboard()});marketsElements.loadMore?.addEventListener('click',()=>{marketsUi.limit+=25;renderMarketsDashboard()});document.getElementById('markets')?.addEventListener('click',event=>{const watch=event.target.closest('[data-markets-watch]');if(watch){event.stopPropagation();toggleWatchlist(MARKETS.find(item=>item.id===watch.dataset.marketsWatch));return}const open=event.target.closest('[data-markets-open]');if(open)selectMarketId(open.dataset.marketsOpen)});
  function switchActiveExchange(exchange){const next=ZychWorkspace.validExchange(exchange);workspaceMenu.hidden=true;workspaceButton.setAttribute('aria-expanded','false');if(next===state.activeExchange)return;const market=ZychWorkspace.equivalentMarket(MARKETS,state.selectedMarket,next);if(market){openMarketContext(ZychMarketContext.fromMarket(market,{timeframe:state.selectedTimeframe}),{preserveView:true});renderActiveExchange();if(!searchResults.hidden)drawSearch();return}state.activeExchange=next;state.selectedMarket=ZychWorkspace.unavailableMarket(state.selectedMarket.asset,next,state.selectedMarket.quoteAsset);saveWorkspace();renderActiveExchange();resetWorkspaceSurfaces();renderMarket();if(!searchResults.hidden)drawSearch();refreshSnapshots();loadMarket()}
  workspaceButton.addEventListener('click',event=>{event.stopPropagation();const open=workspaceMenu.hidden;workspaceMenu.hidden=!open;workspaceButton.setAttribute('aria-expanded',String(open))});workspaceMenu.addEventListener('click',event=>{const option=event.target.closest('[data-active-exchange-option]');if(option)switchActiveExchange(option.dataset.activeExchangeOption)});

  const chartRelatedMarkets=document.getElementById('chart-related-markets'),chartNotes=document.getElementById('chart-notes'),chartNotesState=document.getElementById('chart-notes-state');
  function storedChartNotes(){try{const value=JSON.parse(localStorage.getItem(ZychChartTerminal.notesStorageKey)||'{}');return value&&typeof value==='object'?value:{}}catch{return{}}}
  function loadChartNote(){chartNotes.value=storedChartNotes()[state.selectedMarket.id]||'';chartNotesState.textContent=''}
  function saveChartNote(){const notes=storedChartNotes(),value=chartNotes.value.trimEnd();if(value)notes[state.selectedMarket.id]=value;else delete notes[state.selectedMarket.id];try{localStorage.setItem(ZychChartTerminal.notesStorageKey,JSON.stringify(notes));chartNotesState.textContent=ZychI18n.t('chart.notesSaved');setTimeout(()=>{chartNotesState.textContent=''},1500)}catch{}}
  function renderRelatedMarkets(){const related=ZychChartTerminal.relatedMarkets(MARKETS,state.selectedMarket,6);chartRelatedMarkets.innerHTML=related.length?related.map(market=>{const snapshot=state.marketSnapshots[market.id],change=Number(snapshot?.changePercent),direction=Number.isFinite(change)?change>=0?'positive':'negative':'';return `<button class="chart-related-market" type="button" data-related-market="${escapeHtml(market.id)}"><span>${escapeHtml(market.displaySymbol)}</span>${snapshot?`<small>${formatPrice(snapshot.lastPrice)}</small><em class="${direction}">${formatPercent(change)}</em>`:'<small class="chart-related-unavailable" title="Source not connected">Source not connected</small><em>—</em>'}</button>`}).join(''):`<div class="chart-bottom-empty">${escapeHtml(ZychI18n.t('chart.relatedUnavailable'))}</div>`}

  function renderMarket(){
    const market=state.selectedMarket,snapshot=state.marketSnapshots[market.id],meta=assetMeta(market.asset);
    renderActiveExchange();
    document.querySelectorAll('[data-pair-label]').forEach(el=>el.textContent=marketLabel(market));document.querySelectorAll('[data-exchange-label]').forEach(el=>el.textContent=EXCHANGES[market.exchange].label);
    const pairIcon=document.getElementById('toolbar-market-icon');pairIcon.className=`coin-icon ${meta.className} small`;pairIcon.textContent=meta.icon;
    document.getElementById('current-price').textContent=formatPrice(snapshot?.lastPrice);const toolbarChange=document.getElementById('toolbar-change');toolbarChange.innerHTML=`${formatPercent(snapshot?.changePercent)} <small>24h</small>`;applyDirection(toolbarChange,snapshot?.changePercent);document.getElementById('toolbar-high').textContent=formatPrice(snapshot?.high);document.getElementById('toolbar-low').textContent=formatPrice(snapshot?.low);document.getElementById('toolbar-volume').textContent=snapshot?`$${formatCompact(snapshot.volume)}`:'—';
    document.getElementById('chart-pair-label').textContent=marketLabel(market);document.getElementById('chart-timeframe-label').textContent=state.selectedTimeframe.toUpperCase();document.getElementById('chart-exchange-label').textContent=EXCHANGES[market.exchange]?.label||market.exchange;document.getElementById('chart-info-exchange').textContent=EXCHANGES[market.exchange]?.label||market.exchange;document.getElementById('chart-info-type').textContent=ZychI18n.t(`market.${market.marketType||'spot'}`);document.getElementById('chart-info-base').textContent=market.baseAsset;document.getElementById('chart-info-quote').textContent=market.quoteAsset;document.getElementById('chart-info-symbol').textContent=market.symbol;renderRelatedMarkets();
    selectWatch(market.id);document.querySelectorAll('.timeframes button').forEach(button=>button.classList.toggle('active',button.dataset.interval===state.selectedTimeframe));
    const favorite=document.getElementById('favorite-button'),saved=!market.unavailable&&ZychWatchlist.contains(state.watchlist,market);favorite.classList.toggle('active',saved);favorite.textContent=saved?'★':'☆';favorite.setAttribute('aria-pressed',String(saved));favorite.disabled=Boolean(market.unavailable);favorite.setAttribute('aria-label',`${saved?'Remove':'Add'} ${market.asset} ${EXCHANGES[market.exchange].label} ${saved?'from':'to'} Watchlist`);
  }

  const statusElements=[document.getElementById('connection-status'),document.getElementById('market-status')];
  function setConnection(status){state.connectionStatus=status;const key={CONNECTING:'connecting',LIVE:'live',OFFLINE:'offline',RECONNECTING:'reconnecting'}[status]||'offline';statusElements.forEach(el=>{el.dataset.status=status.toLowerCase();el.lastChild.textContent=` ${ZychI18n.t(`connection.${key}`)}`});const exchange=EXCHANGES[state.selectedMarket.exchange].label;document.getElementById('connection-message').textContent=status==='LIVE'?`${exchange} ${ZychI18n.t('connection.liveData')}`:status==='OFFLINE'?ZychI18n.t('connection.streamUnavailable'):`${ZychI18n.t('connection.connectingTo')} ${exchange}`}
  const setOhlc=candle=>document.getElementById('ohlc-status').textContent=`O ${formatPrice(candle.open)}  H ${formatPrice(candle.high)}  L ${formatPrice(candle.low)}  C ${formatPrice(candle.close)}`;
  function renderLiveQuote(market,snapshot){document.getElementById('current-price').textContent=formatPrice(snapshot.lastPrice);updateWatch(ZychWatchlist.identity(market),snapshot);updatePulse(market.asset,snapshot)}
  function liveCandle(market,candle){if(state.selectedMarket.id!==market.id)return;historyService.updateLive(market,state.selectedTimeframe,candle);chartApi.update(candle);setOhlc(candle);updateSnapshot(market.id,{...(state.marketSnapshots[market.id]||{}),lastPrice:candle.close});renderLiveQuote(market,state.marketSnapshots[market.id]);renderAlertOverlays()}
  function loadMarket(){
    quickMenu.close();closeAlertLineMenu();cancelQuickDrag();renderQuickAlertLines();const market=state.selectedMarket,timeframe=state.selectedTimeframe;historyContext=null;historyLoading=false;setHistoryStatus('');state.loadingState.chart=true;state.errorState.chart=null;chartApi.loading(ZychI18n.t('connection.loading'));document.getElementById('ohlc-status').textContent=ZychI18n.t('connection.loading');renderMarket();
    if(market.unavailable){stopMarket();generation+=1;chartApi.clear();const message=`${market.asset} is not available on ${EXCHANGES[market.exchange].label}`;chartApi.loading(message);document.getElementById('ohlc-status').textContent=message;setConnection('OFFLINE');state.errorState.chart=message;state.loadingState.chart=false;document.getElementById('retry-button').hidden=true;return}
    selectMarketData(market,timeframe,{onStatus:setConnection,onCandles:(data,result)=>{if(state.selectedMarket.id!==market.id||state.selectedTimeframe!==timeframe)return;if(!data.length){chartApi.loading('No market data');return}historyContext={market,timeframe,token:generation,endReached:result.endReached,key:result.key};chartApi.setData(data,result.key,result.pages);chartApi.ready();setOhlc(data.at(-1));updateSnapshot(market.id,{...(state.marketSnapshots[market.id]||{}),lastPrice:data.at(-1).close});updateWatch(ZychWatchlist.identity(market),state.marketSnapshots[market.id]);updatePulse(market.asset,state.marketSnapshots[market.id]);renderMarket();state.loadingState.chart=false;document.getElementById('retry-button').hidden=true},onCandle:candle=>liveCandle(market,candle),onError:error=>{const message=error.name==='TimeoutError'?'Market request timed out':'Market data unavailable';state.errorState.chart=message;chartApi.loading(message);document.getElementById('ohlc-status').textContent=message;document.getElementById('retry-button').hidden=false}})
  }
  function selectAsset(asset){const market=marketForAsset(asset);if(market)return openMarketContext(ZychMarketContext.fromMarket(market));state.selectedMarket=ZychWorkspace.unavailableMarket(asset,state.activeExchange,state.selectedMarket.quoteAsset);saveWorkspace();loadChartNote();renderMarket();refreshSnapshots();loadMarket();return false}
  function openMarketContext(context,{closePanel=false,preserveView=false}={}){const normalized=ZychMarketContext.create(context);if(!normalized)return false;const market=MARKETS.find(item=>item.enabled&&item.exchange===normalized.exchange&&item.marketType===normalized.marketType&&item.symbol===normalized.symbol);if(!market)return false;state.activeExchange=market.exchange;state.selectedMarket=market;if(normalized.timeframe){const interval=normalized.timeframe==='24h'?'1d':normalized.timeframe;if(TIMEFRAMES.includes(interval))state.selectedTimeframe=interval}state.marketContext={...normalized,eventTimestamp:normalized.eventTimestamp};saveWorkspace();loadChartNote();resetWorkspaceSurfaces();renderMarket();if(!preserveView)setWorkspaceView('chart');refreshSnapshots();loadMarket();if(closePanel)closeAlertsPanel();return true}
  function selectMarketId(id){const market=MARKETS.find(item=>item.id===id&&item.enabled);if(market)openMarketContext(ZychMarketContext.fromMarket(market))}
  function toggleWatchlist(market){if(!market||market.unavailable)return;state.watchlist=ZychWatchlist.toggle(state.watchlist,market);saveWatchlist();renderWatchlist();renderMarket();renderMarketsDashboard();if(!searchResults.hidden)drawSearch();refreshSnapshots()}
  const watchlistWorkspace=document.getElementById('watchlist-workspace');
  function selectWatchForAlert(market){if(!market)return;state.activeExchange=market.exchange;state.selectedMarket=market;saveWorkspace();renderMarket();refreshSnapshots();openAlertDialog()}
  watchlistWorkspace.addEventListener('click',event=>{if(event.target.closest('[data-open-search]')){openSearch();return}const remove=event.target.closest('[data-remove-watch]');if(remove){event.stopPropagation();const item=state.watchlist.find(row=>row.key===remove.dataset.removeWatch),market=item&&ZychWatchlist.resolve(item,MARKETS);if(market)toggleWatchlist(market);return}const chartAction=event.target.closest('[data-watch-chart]');if(chartAction){event.stopPropagation();selectMarketId(chartAction.dataset.watchChart);return}const alertAction=event.target.closest('[data-watch-alert]');if(alertAction){event.stopPropagation();selectWatchForAlert(MARKETS.find(item=>item.id===alertAction.dataset.watchAlert));return}const row=event.target.closest('.watchlist-data-row,.watchlist-tile');if(row)selectMarketId(row.dataset.marketId)});
  watchlistWorkspace.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&event.target.matches('.watchlist-data-row,.watchlist-tile')){event.preventDefault();selectMarketId(event.target.dataset.marketId)}});
  document.querySelector('.watchlist-filter-tabs').addEventListener('click',event=>{const button=event.target.closest('[data-watch-filter]');if(!button||button.disabled)return;watchUiState.filter=button.dataset.watchFilter;renderWatchlist()});
  document.getElementById('watchlist-exchange-filter').addEventListener('change',event=>{watchUiState.exchange=event.target.value;renderWatchlist()});document.getElementById('watchlist-sort').addEventListener('change',event=>{watchUiState.sort=event.target.value;renderWatchlist()});
  const watchImportBackdrop=document.getElementById('watchlist-import-backdrop');document.getElementById('watchlist-import-button').addEventListener('click',()=>{watchImportBackdrop.hidden=false});document.querySelector('[data-close-watchlist-import]').addEventListener('click',()=>{watchImportBackdrop.hidden=true});watchImportBackdrop.addEventListener('click',event=>{if(event.target===watchImportBackdrop)watchImportBackdrop.hidden=true});
  pulseCards.forEach(card=>card.addEventListener('click',()=>selectAsset(card.dataset.pulseAsset)));radarCards.forEach(card=>card.addEventListener('click',()=>selectAsset(card.dataset.radarAsset)));
  document.querySelectorAll('.timeframes button').forEach(button=>button.addEventListener('click',()=>{if(TIMEFRAMES.includes(button.dataset.interval)&&button.dataset.interval!==state.selectedTimeframe){state.selectedTimeframe=button.dataset.interval;saveWorkspace();loadMarket()}}));
  document.getElementById('favorite-button').addEventListener('click',()=>toggleWatchlist(state.selectedMarket));
  let chartHotkeyBuffer='',chartHotkeyTimer=null;document.addEventListener('keydown',event=>{if(document.documentElement.dataset.workspaceView!=='chart'||event.ctrlKey||event.metaKey||event.altKey||ZychChartTerminal.isEditable(event.target))return;if(/^\d$/.test(event.key)){chartHotkeyBuffer+=event.key;clearTimeout(chartHotkeyTimer);chartHotkeyTimer=setTimeout(()=>{chartHotkeyBuffer=''},1300);return}if(event.key==='Enter'&&chartHotkeyBuffer){const interval=ZychChartTerminal.hotkeyInterval(chartHotkeyBuffer);chartHotkeyBuffer='';clearTimeout(chartHotkeyTimer);if(interval&&interval!==state.selectedTimeframe){state.selectedTimeframe=interval;saveWorkspace();loadMarket()}}});
  const chartTerminal=document.getElementById('terminal'),chartBottomToggle=document.getElementById('chart-bottom-toggle');chartTerminal.classList.add('chart-terminal');function setChartBottom(collapsed,persist=true){chartTerminal.classList.toggle('bottom-collapsed',collapsed);chartBottomToggle.setAttribute('aria-expanded',String(!collapsed));chartBottomToggle.querySelector('span').textContent=ZychI18n.t(collapsed?'chart.showBottom':'chart.hideBottom');if(persist)try{sessionStorage.setItem(ZychChartTerminal.panelStorageKey,collapsed?'collapsed':'open')}catch{}requestAnimationFrame(()=>chart.applyOptions({width:chartContainer.clientWidth,height:chartContainer.clientHeight}))}let chartBottomPreference=null;try{chartBottomPreference=sessionStorage.getItem(ZychChartTerminal.panelStorageKey)}catch{}setChartBottom(ZychChartTerminal.bottomPanelCollapsed(chartBottomPreference,window.innerHeight),false);chartBottomToggle.addEventListener('click',()=>setChartBottom(!chartTerminal.classList.contains('bottom-collapsed')));chartNotes.addEventListener('input',saveChartNote);loadChartNote();document.getElementById('chart-fullscreen').addEventListener('click',()=>{if(document.fullscreenElement)document.exitFullscreen?.();else chartTerminal.requestFullscreen?.()});

  const searchInput=document.getElementById('coin-search'),searchResults=document.getElementById('search-results'),searchShell=document.querySelector('.search-shell');let searchMatches=[],searchIndex=-1,searchTimer=null;
  const closeSearch=()=>{searchResults.hidden=true;searchShell.classList.remove('open');searchIndex=-1};
  function openSearch(){searchShell.classList.add('open');searchInput.focus();drawSearch()}
  function drawSearch(){
    if(universeStatus==='loading'){searchResults.innerHTML=`<div class="universe-state">${escapeHtml(ZychI18n.t('search.loading'))}</div>`;searchResults.hidden=false;return}
    if(universeStatus==='error'&&!assetIndex.size){searchResults.innerHTML=`<div class="universe-state">${escapeHtml(ZychI18n.t('search.unavailable'))}<button class="catalog-retry-button" type="button" data-retry-universe>${escapeHtml(ZychI18n.t('common.retry'))}</button></div>`;searchResults.hidden=false;return}
    const query=searchInput.value.trim();searchMatches=ZychInstruments.search(MARKETS,query);searchIndex=searchMatches.length?0:-1;
    if(!query){searchResults.innerHTML=`<div class="dropdown-empty">${escapeHtml(ZychI18n.t('search.empty'))}</div>`;searchResults.hidden=false;return}
    const rowMarkup=(market,index)=>{const saved=ZychWatchlist.contains(state.watchlist,market),meta=assetMeta(market.baseAsset),snapshot=state.marketSnapshots[market.id],change=snapshot?.changePercent,direction=Number.isFinite(change)?(change>=0?'positive':'negative'):'',type=ZychI18n.t(`market.${market.marketType}`);return `<div class="search-asset ${index===searchIndex?'active':''}" data-result-index="${index}"><button class="dropdown-item market-asset-button" type="button" data-select-instrument="${escapeHtml(market.id)}">${iconMarkup(meta,'tiny')}<span class="search-identity"><strong>${escapeHtml(market.displaySymbol)}</strong><small class="search-market">${escapeHtml(EXCHANGES[market.exchange].label)} · ${escapeHtml(type)}</small></span><span class="market-result-data"><strong>${snapshot?`$${formatPrice(snapshot.lastPrice)}`:'—'}</strong><em class="${direction}">${formatPercent(change)}</em></span></button><button class="search-watch-button ${saved?'active':''}" type="button" data-toggle-instrument="${escapeHtml(market.id)}" aria-label="${saved?'Remove from':'Add to'} Watchlist">${saved?'★':'☆'}</button></div>`},indexed=searchMatches.map((market,index)=>({market,index})),top=indexed.filter(item=>item.market.baseAsset===query.toUpperCase()&&item.market.quoteAsset==='USDT'),other=indexed.filter(item=>!top.includes(item)),section=(label,items)=>items.length?`<div class="search-group-label">${escapeHtml(label)}</div>${items.map(item=>rowMarkup(item.market,item.index)).join('')}`:'';const rows=searchMatches.length?`${section(ZychI18n.t('search.topMatches'),top)}${section(ZychI18n.t('search.otherMarkets'),other)}`:`<div class="dropdown-empty">${escapeHtml(ZychI18n.t('search.noResults'))}</div>`;
    searchResults.innerHTML=`<div class="market-browser-list">${rows}</div>`;searchResults.hidden=false;
  }
  function scheduleSearch(){clearTimeout(searchTimer);searchTimer=setTimeout(drawSearch,100)}
  function setSearchIndex(index){searchIndex=index;searchResults.querySelectorAll('.search-asset').forEach((item,itemIndex)=>item.classList.toggle('active',itemIndex===searchIndex));searchResults.querySelector(`[data-result-index="${searchIndex}"]`)?.scrollIntoView({block:'nearest'})}
  searchInput.addEventListener('input',scheduleSearch);searchInput.addEventListener('focus',drawSearch);searchInput.addEventListener('keydown',event=>{if(event.key==='Escape'){searchInput.value='';closeSearch();searchInput.blur();return}if(event.key==='ArrowDown'&&searchMatches.length){event.preventDefault();setSearchIndex((searchIndex+1)%searchMatches.length)}if(event.key==='ArrowUp'&&searchMatches.length){event.preventDefault();setSearchIndex((searchIndex-1+searchMatches.length)%searchMatches.length)}if(event.key==='Enter'&&searchMatches[searchIndex]){event.preventDefault();selectMarketId(searchMatches[searchIndex].id);searchInput.value='';closeSearch()}});
  searchResults.addEventListener('click',event=>{const retry=event.target.closest('[data-retry-universe]');if(retry){event.stopPropagation();loadUniverse();return}const toggle=event.target.closest('[data-toggle-instrument]');if(toggle){event.stopPropagation();dismissFavoriteHint();toggleWatchlist(MARKETS.find(item=>item.id===toggle.dataset.toggleInstrument));drawSearch();return}const option=event.target.closest('[data-select-instrument]');if(option){selectMarketId(option.dataset.selectInstrument);searchInput.value='';closeSearch()}});
  document.getElementById('mobile-search-button').addEventListener('click',event=>{event.stopPropagation();openSearch()});document.getElementById('add-watchlist-button').addEventListener('click',event=>{event.stopPropagation();openSearch()});document.addEventListener('keydown',event=>{if(event.key==='/'&&document.activeElement!==searchInput){event.preventDefault();openSearch()}});document.addEventListener('click',event=>{if(!event.target.closest('.search-shell')&&!event.target.closest('.global-exchange-shell')){closeSearch();workspaceMenu.hidden=true;workspaceButton.setAttribute('aria-expanded','false')}});

  const languageButton=document.getElementById('language-button'),languageMenu=document.getElementById('language-menu'),languageOptions=[...languageMenu.querySelectorAll('[data-language]')],terminal=document.getElementById('terminal'),radarPage=document.getElementById('radar'),marketsPage=document.getElementById('markets'),watchlistPage=document.getElementById('watchlist-workspace');function renderLanguageButton(){languageButton.firstChild.textContent=ZychI18n.locale()==='ru-RU'?'RU ':'EN ';languageOptions.forEach(option=>option.classList.toggle('active',option.dataset.language===ZychI18n.preference()))}function setWorkspaceView(view){terminal.hidden=view!=='chart';watchlistPage.hidden=view!=='watchlist';radarPage.hidden=view!=='radar';marketsPage.hidden=view!=='markets';document.querySelectorAll('[data-workspace-view]').forEach(item=>item.classList.toggle('active',item.dataset.workspaceView===view))}renderLanguageButton();languageButton.addEventListener('click',event=>{event.stopPropagation();languageMenu.hidden=!languageMenu.hidden;languageButton.setAttribute('aria-expanded',String(!languageMenu.hidden))});languageMenu.addEventListener('click',event=>{event.stopPropagation();const option=event.target.closest('[data-language]');if(option){ZychI18n.setPreference(option.dataset.language);languageMenu.hidden=true;languageButton.setAttribute('aria-expanded','false')}});window.addEventListener('zych:languagechange',()=>{renderLanguageButton();renderWatchlist();renderMarket();setConnection(state.connectionStatus);if(state.loadingState.chart){chartApi.loading(ZychI18n.t('connection.loading'));document.getElementById('ohlc-status').textContent=ZychI18n.t('connection.loading')}if(!searchResults.hidden)drawSearch()});document.querySelectorAll('[data-workspace-view]').forEach(control=>control.addEventListener('click',()=>setWorkspaceView(control.dataset.workspaceView)));document.addEventListener('click',event=>{if(!event.target.closest('.language-shell')){languageMenu.hidden=true;languageButton.setAttribute('aria-expanded','false')}});

  setWorkspaceView=function(view){const next=['radar','watchlist','chart','markets'].includes(view)?view:'radar';terminal.hidden=next!=='chart';watchlistPage.hidden=next!=='watchlist';radarPage.hidden=next!=='radar';marketsPage.hidden=next!=='markets';document.documentElement.dataset.workspaceView=next;document.querySelectorAll('[data-workspace-view]').forEach(item=>{const active=item.dataset.workspaceView===next;item.classList.toggle('active',active);if(active)item.setAttribute('aria-current','page');else item.removeAttribute('aria-current')});if(location.hash!==`#${next}`)history.replaceState(null,'',`#${next}`)};
  setWorkspaceView(location.hash.slice(1)||'radar');

  const radarFilterTabs=document.querySelector('.radar-filter-tabs'),radarExchangeFilter=document.getElementById('radar-exchange-filter'),radarRows=document.getElementById('radar-opportunity-rows'),radarRecent=document.getElementById('radar-recent-events');
  const radarTime=value=>Number.isFinite(Number(value))?new Date(Number(value)).toLocaleTimeString(ZychI18n.locale(),{hour:'2-digit',minute:'2-digit',second:'2-digit'}):'—';
  const radarEmpty=(title,detail)=>`<span class="empty-state-icon">⌁</span><strong>${escapeHtml(title)}</strong><p>${escapeHtml(detail)}</p>`;
  function radarRow(event,index){const reason=event.interpretationLabel||event.setupType||'—',move=event.eventChangePct==null?'—':formatPercent(event.eventChangePct),relative=event.relativeVolume==null?'—':`${Number(event.relativeVolume).toFixed(2)}×`,score=event.score==null?'—':String(event.score),direction=event.direction==='UP'?'positive':event.direction==='DOWN'?'negative':'';return `<div class="radar-event-row selectable" role="button" tabindex="0" data-radar-event-id="${escapeHtml(event.eventId)}" aria-label="Open ${escapeHtml(event.symbol)} on ${escapeHtml(EXCHANGES[event.exchange]?.label||event.exchange)} chart"><span>${index+1}</span><span class="radar-event-symbol"><b>${escapeHtml(event.baseAsset||event.symbol)}</b><small>${escapeHtml(event.timeframe||'—')}</small></span><span>${escapeHtml(EXCHANGES[event.exchange]?.label||event.exchange)}</span><span><b>${escapeHtml(reason)}</b><small>${escapeHtml(event.interpretationSummary||event.setupType||'—')}</small></span><span>${escapeHtml(score)}</span><span class="${direction}">${escapeHtml(move)}</span><span>${escapeHtml(relative)}</span><span>${escapeHtml(radarTime(event.observedAt))}</span></div>`}
  function radarRecentRow(event){const score=event.score==null?'—':event.score;return `<article class="radar-recent-row selectable" role="button" tabindex="0" data-radar-event-id="${escapeHtml(event.eventId)}" aria-label="Open ${escapeHtml(event.symbol)} on ${escapeHtml(EXCHANGES[event.exchange]?.label||event.exchange)} chart"><div><strong>${escapeHtml(event.baseAsset||event.symbol)} · ${escapeHtml(event.timeframe||'—')}</strong><p>${escapeHtml(event.interpretationLabel||event.setupType||'Radar event')}</p><small>${escapeHtml(EXCHANGES[event.exchange]?.label||event.exchange)} · ${escapeHtml(radarTime(event.observedAt))}</small></div><b>${escapeHtml(score)}</b></article>`}
  function renderRadar(state){watchRadarState=state;const condition=ZychRadarEvent.status(state),visible=ZychRadarEvent.filter(state.events,state.filters),opportunities=[...visible].sort((a,b)=>(b.score??-1)-(a.score??-1)||b.eventTimestamp-a.eventTimestamp),scores=state.events.map(event=>event.score).filter(Number.isFinite),meta=state.meta||{},coverage=meta.coverage||{},expected=coverage.expectedExchanges?.length||0,healthy=coverage.healthyExchanges?.length||0,lastUpdate=meta.lastHealthyProcessingTimestamp;radarFilterTabs?.querySelectorAll('[data-radar-filter]').forEach(button=>button.classList.toggle('active',button.dataset.radarFilter===state.filters.anomaly));if(radarExchangeFilter)radarExchangeFilter.value=state.filters.exchange;
    const lifecycleCode=condition.code.toLowerCase(),radarPage=document.getElementById('radar'),dataState=document.getElementById('radar-data-state'),engine=document.getElementById('radar-engine-status');radarPage.dataset.radarStatus=lifecycleCode;dataState.dataset.status=lifecycleCode;dataState.lastElementChild.textContent=condition.label;engine.dataset.status=lifecycleCode;engine.lastElementChild.textContent=condition.label;document.getElementById('radar-engine-description').textContent=condition.code==='EMPTY'?'Radar processing is healthy; no event currently meets qualification rules.':condition.code==='PARTIAL'?'Radar is processing with partial exchange availability.':condition.code==='STALE'?'The last verified snapshot is retained, but fresh Radar data is unavailable.':condition.code==='OFFLINE'?'The Radar backend is unavailable.':'Verified backend Radar events are connected.';document.getElementById('radar-engine-detail').textContent=state.error?state.error:`${healthy} of ${expected||healthy} exchanges healthy`;
    document.getElementById('radar-fetched-count').textContent=state.lastSuccessfulFetch?String(state.events.length):'—';document.getElementById('radar-visible-count').textContent=state.lastSuccessfulFetch?String(visible.length):'—';document.getElementById('radar-high-score').textContent=scores.length?String(Math.max(...scores)):'—';document.getElementById('radar-quality').textContent=condition.label;document.getElementById('radar-coverage').textContent=expected?`${healthy}/${expected} exchanges healthy`:'Coverage unavailable';document.getElementById('radar-strip-fetched').textContent=state.lastSuccessfulFetch?String(state.events.length):'—';document.getElementById('radar-strip-visible').textContent=state.lastSuccessfulFetch?String(visible.length):'—';document.getElementById('radar-last-update').textContent=lastUpdate?radarTime(lastUpdate):'—';document.getElementById('radar-auto-refresh').textContent=state.error?'Retrying every 10 seconds':'10 seconds';document.getElementById('radar-recent-count').textContent=state.lastSuccessfulFetch?String(state.events.length):'—';document.getElementById('radar-feed-footer').textContent=condition.label;
    const noRows=condition.code==='LOADING'?['Loading verified Radar events','Waiting for the authoritative event feed.']:condition.code==='WARMING_UP'?['Radar is warming up','Qualified events will appear after continuous market state is ready.']:condition.code==='EMPTY'?['No qualified events yet','Radar processing is healthy; no event currently meets qualification rules.']:condition.code==='OFFLINE'?['Radar unavailable','No market opportunities are being fabricated.']:!state.events.length&&condition.code==='PARTIAL'?['No qualified events in the partial snapshot','Some exchanges are currently unavailable.']:!state.events.length&&condition.code==='STALE'?['No cached qualified events','Fresh Radar data is currently unavailable.']:!state.events.length&&condition.code==='DEGRADED'?['No qualified events in the degraded snapshot','Radar processing is degraded.']:visible.length?null:['No events match these filters','Change the supported event or exchange filter.'];radarRows.classList.toggle('radar-empty-state',Boolean(noRows));radarRows.classList.toggle('radar-event-list',!noRows);radarRows.innerHTML=noRows?radarEmpty(...noRows):opportunities.map(radarRow).join('');const recentRows=state.events.slice(0,6);radarRecent.classList.toggle('recent-events-empty',!recentRows.length);radarRecent.classList.toggle('radar-recent-list',Boolean(recentRows.length));radarRecent.innerHTML=recentRows.length?recentRows.map(radarRecentRow).join(''):radarEmpty(noRows?.[0]||condition.label,noRows?.[1]||'No verified events are available.');renderWatchlist();
  }
  const radarFeed=new ZychRadarEvent.Feed({intervalMs:10000,onChange:renderRadar}),radarNavigationStatus=document.getElementById('radar-navigation-status');function selectRadarEvent(eventId){const event=radarFeed.state.events.find(item=>item.eventId===eventId),selection=ZychRadarEvent.resolveSelection(event,MARKETS,{supportedTimeframes:TIMEFRAMES,currentTimeframe:state.selectedTimeframe});if(selection.error){radarNavigationStatus.hidden=false;radarNavigationStatus.textContent=selection.error==='MARKET_NOT_FOUND'?'Exact Radar market is unavailable in the Chart universe.':'Radar event link is invalid.';return false}if(!openMarketContext(selection.context)){radarNavigationStatus.hidden=false;radarNavigationStatus.textContent='Unable to open the exact Radar market.';return false}radarNavigationStatus.hidden=true;radarNavigationStatus.textContent='';return true}function handleRadarSelection(event){const row=event.target.closest('[data-radar-event-id]');if(!row||event.type==='keydown'&&!['Enter',' '].includes(event.key))return;if(event.type==='keydown')event.preventDefault();selectRadarEvent(row.dataset.radarEventId)}radarRows.addEventListener('click',handleRadarSelection);radarRows.addEventListener('keydown',handleRadarSelection);radarRecent.addEventListener('click',handleRadarSelection);radarRecent.addEventListener('keydown',handleRadarSelection);radarFilterTabs?.addEventListener('click',event=>{const button=event.target.closest('[data-radar-filter]');if(button&&!button.disabled)radarFeed.setFilters({anomaly:button.dataset.radarFilter})});radarExchangeFilter?.addEventListener('change',()=>radarFeed.setFilters({exchange:radarExchangeFilter.value}));renderRadar(radarFeed.state);radarFeed.start();

  const alertStorage=new ZychAlerts.AlertStorage(),hubActions=new ZychQuickAlerts.ActionCoordinator(),hubOverrides=new Map();let alertTab='all';
  const alertDialogBackdrop=document.getElementById('alert-dialog-backdrop'),alertForm=document.getElementById('alert-form'),alertFormError=document.getElementById('alert-form-error'),alertsPanel=document.getElementById('alerts-panel'),alertsPanelBackdrop=document.getElementById('alerts-panel-backdrop'),alertsList=document.getElementById('alerts-list'),alertCounter=document.getElementById('alerts-counter'),alertMonitorStatus=document.getElementById('alert-monitor-status'),toastRegion=document.getElementById('toast-region'),soundSelect=document.getElementById('alert-sound-select'),soundVolume=document.getElementById('alert-sound-volume'),soundToggle=document.getElementById('alert-sound-toggle'),soundTest=document.getElementById('alert-sound-test'),soundState=document.getElementById('alert-sound-state');
  const alertTypeInputs=[...alertForm.elements['alert-type']],alertFieldsets={price:document.getElementById('alert-price-fields'),movement:document.getElementById('alert-movement-fields'),volume:document.getElementById('alert-volume-fields')};
  const formatAlertTime=value=>new Date(value).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
  function alertDescription(alert){const c=alert.condition;if(c.type==='price')return `Price ${c.operator} $${formatPrice(c.value)}`;if(c.type==='movement')return `${c.direction==='up'?'+':'−'}${c.percent}% within ${c.window}`;return `Volume ≥ ${c.multiplier}x average · ${c.timeframe}`}
  function eventDescription(event){if(event.alertType==='price')return `Price crossed ${event.condition.operator} $${formatPrice(event.threshold)} · $${formatPrice(event.currentPrice)}`;if(event.alertType==='movement')return `${event.percentMove>=0?'+':''}${Number(event.percentMove).toFixed(2)}% in ${event.window}`;return `Volume ${Number(event.multiplier).toFixed(2)}x average`}
  function updateAlertCounter(){const count=alertEngine.activeCount();alertCounter.textContent=String(count);alertCounter.hidden=count===0;const radarCount=document.getElementById('radar-alert-count');if(radarCount)radarCount.textContent=String(count);const watchCount=document.getElementById('watchlist-alerts');if(watchCount)watchCount.textContent=String(count)}
  function renderAlertsPanel(){
    document.querySelectorAll('[data-alert-tab]').forEach(button=>button.classList.toggle('active',button.dataset.alertTab===alertTab));
    if(alertTab==='triggered'){const events=alertEngine.events();alertsList.innerHTML=events.length?events.map(event=>`<article class="alert-row" data-alert-context="${escapeHtml(event.marketId)}" data-alert-timeframe="${escapeHtml(event.timeframe||'')}"><div class="alert-row-top"><div><strong>${escapeHtml(event.asset)}</strong><p>${escapeHtml(eventDescription(event))}</p><small>${escapeHtml(event.exchange)} · ${formatAlertTime(event.triggeredAt)}</small></div><div class="alert-row-actions"><button class="delete-alert" type="button" data-alert-action="dismiss-event" data-event-id="${escapeHtml(event.id)}">Delete</button></div></div></article>`).join(''):'<div class="alerts-empty">No triggered alerts</div>';return}
    const source=alertEngine.list().map(alert=>hubOverrides.has(alert.id)?{...alert,status:hubOverrides.get(alert.id)}:alert).filter(alert=>alert.status!==null),alerts=ZychAlertHub.visibleAlerts(source,alertTab);source.forEach(alert=>hubActions.register(alert.id,alert.status));hubActions.removeMissing(alertEngine.list().map(alert=>alert.id));alertsList.innerHTML=alerts.length?alerts.map(alert=>{const context=ZychAlertHub.openContext(alert);return `<article class="alert-row ${alert.status==='paused'?'paused':''}" data-alert-id="${escapeHtml(alert.id)}" data-alert-market="${escapeHtml(context.marketId)}"><div class="alert-row-top"><div class="alert-row-identity"><div class="alert-row-heading"><strong>${escapeHtml(context.symbol)}</strong><span class="alert-status-badge ${alert.status==='paused'?'paused':''}">${alert.status.toUpperCase()}</span></div><p>${escapeHtml(alertDescription(alert))}</p><small>${escapeHtml(ZychAlertHub.marketText(alert))} · ${escapeHtml(alert.mode)}</small></div><div class="alert-row-actions"><button class="open-alert" type="button" data-alert-open="${escapeHtml(context.marketId)}" data-alert-timeframe="${escapeHtml(context.timeframe)}">Open</button><button type="button" data-alert-action="${alert.status==='active'?'pause':'resume'}" data-alert-id="${escapeHtml(alert.id)}">${alert.status==='active'?'Pause':'Resume'}</button><button class="delete-alert" type="button" data-alert-action="delete" data-alert-id="${escapeHtml(alert.id)}">Delete</button></div></div></article>`}).join(''):'<div class="alerts-empty">No alerts yet<small>Create a Quick Alert from the chart.</small></div>'
  }
  function openAlertContext(marketId,timeframe){const market=MARKETS.find(item=>item.id===marketId||`${item.exchange}:spot:${item.symbol}`===marketId);return market&&openMarketContext(ZychMarketContext.fromMarket(market,{timeframe}),{closePanel:true})}
  function renderSoundState(current){soundSelect.value=current.soundId;soundVolume.value=String(current.volume);soundToggle.textContent=current.enabled?'ON':'OFF';soundToggle.classList.toggle('active',current.enabled);soundToggle.setAttribute('aria-pressed',String(current.enabled));soundToggle.setAttribute('aria-label',`Turn alert sound ${current.enabled?'off':'on'}`);soundToggle.dataset.playCount=String(current.playCount);soundToggle.dataset.contextState=current.contextState;soundToggle.dataset.audioError=current.lastError;soundState.textContent=current.enabled&&!current.unlocked?'Tap to enable audio':''}
  const alertSound=new ZychNotifications.AlertSoundManager({onState:renderSoundState});renderSoundState(alertSound.state());
  const notificationCenter=new ZychNotifications.NotificationCenter({region:toastRegion,sound:alertSound,describe:eventDescription,formatTime:formatAlertTime,onOpen:event=>openAlertContext(event.marketId,event.timeframe)});
  const browserNotifier=new ZychNotifications.BrowserNotifier({notificationCenter});
  const pushManager=new ZychNotifications.PushManagerController({button:document.getElementById('push-notifications-toggle')});pushManager.init();document.getElementById('push-notifications-toggle').addEventListener('click',()=>pushManager.toggle());
  const quickAlertElement=document.getElementById('quick-alert-menu'),quickMenu=new ZychQuickAlerts.MenuController(quickAlertElement),alertLineMenu=document.getElementById('alert-line-menu'),alertOverlay=document.getElementById('chart-alert-overlays'),quickPriceLines=new Map(),quickUpdates=new ZychQuickAlerts.UpdateCoordinator(),quickActions=new ZychQuickAlerts.ActionCoordinator();let activeQuickDrag=null,selectedAlertLineId=null;
  const quickLineOptions=record=>record.alert.status==='paused'?{color:themeMarketColor('--text-muted','#77828b'),lineWidth:1,lineStyle:LightweightCharts.LineStyle?.Dashed??2,axisLabelVisible:true,title:'PAUSED'}:{color:themeMarketColor('--warning','#d9943e'),lineWidth:1,lineStyle:LightweightCharts.LineStyle?.Dashed??2,axisLabelVisible:true,title:'ALERT'};
  function closeAlertLineMenu(){selectedAlertLineId=null;alertLineMenu.hidden=true;alertLineMenu.replaceChildren()}
  function renderAlertOverlays(){const current=Number(state.marketSnapshots[state.selectedMarket.id]?.lastPrice);alertOverlay.innerHTML=[...quickPriceLines.values()].map(record=>{const y=candles.priceToCoordinate(record.price),paused=record.alert.status==='paused',distance=ZychChartTerminal.alertDistance(current,record.price);if(!Number.isFinite(y)||!paused&&!distance)return'';const label=paused?`Paused · ${formatPrice(record.price)}`:`Active · ${distance.percent>=0?'+':''}${distance.percent.toFixed(2)}% · ${formatPrice(distance.absolute)}`;return `<div class="chart-alert-badge ${paused?'paused':''}" style="top:${Math.max(12,Math.min(chartContainer.clientHeight-12,y))}px" data-alert-badge="${escapeHtml(record.id)}"><span>${label}</span><button type="button" data-chart-alert-delete="${escapeHtml(record.id)}" aria-label="Delete alert">×</button></div>`}).join('')}
  function renderQuickAlertLines(){closeAlertLineMenu();quickPriceLines.forEach(record=>candles.removePriceLine(record.line));quickPriceLines.clear();const alerts=ZychQuickAlerts.matchingAlerts(alertEngine.list(),state.selectedMarket.id);alerts.forEach(alert=>{const price=Number(alert.condition.value),record={id:alert.id,alert:{...alert},line:null,price};record.line=candles.createPriceLine({price,...quickLineOptions(record)});quickPriceLines.set(alert.id,record);quickUpdates.register(alert.id,price);quickActions.register(alert.id,alert.status)});quickUpdates.removeMissing(alerts.map(alert=>alert.id));quickActions.removeMissing(alerts.map(alert=>alert.id));chartContainer.dataset.alertLineCount=String(quickPriceLines.size);chartContainer.dataset.alertLineMarket=state.selectedMarket.id;renderAlertOverlays()}
  const quickLineAt=y=>ZychQuickAlerts.closestLine([...quickPriceLines.values()],y,price=>candles.priceToCoordinate(price),10);
  function applyQuickPrice(record,price){record.price=Number(price);record.line.applyOptions({price:record.price});chartContainer.dataset.dragPrice=String(record.price);renderAlertOverlays()}
  function applyQuickStatus(record,status){if(status===null){try{candles.removePriceLine(record.line)}catch{}quickPriceLines.delete(record.id);closeAlertLineMenu();chartContainer.dataset.alertLineCount=String(quickPriceLines.size);renderAlertOverlays();return}record.alert={...record.alert,status};record.line.applyOptions(quickLineOptions(record));renderAlertOverlays();if(selectedAlertLineId===record.id)openAlertLineMenu(record,Number(alertLineMenu.style.left.replace('px','')),Number(alertLineMenu.style.top.replace('px','')))}
  function openAlertLineMenu(record,x,y){quickMenu.close();selectedAlertLineId=record.id;const action=record.alert.status==='paused'?'resume':'pause',label=action==='resume'?'Resume':'Pause';alertLineMenu.innerHTML=`<button type="button" role="menuitem" data-alert-line-action="${action}" data-alert-id="${escapeHtml(record.id)}">${label}</button><button type="button" role="menuitem" data-alert-line-action="delete" data-alert-id="${escapeHtml(record.id)}">Delete</button>`;alertLineMenu.style.left=`${Math.max(0,Number(x)||0)}px`;alertLineMenu.style.top=`${Math.max(0,Number(y)||0)}px`;alertLineMenu.hidden=false}
  function cancelQuickDrag(){if(!activeQuickDrag)return;const record=activeQuickDrag.record,confirmed=quickUpdates.confirmed(record.id);if(Number.isFinite(confirmed))applyQuickPrice(record,confirmed);try{chartContainer.releasePointerCapture(activeQuickDrag.pointerId)}catch{}activeQuickDrag=null;chart.applyOptions({handleScroll:true,handleScale:true});chartContainer.classList.remove('alert-line-dragging','alert-line-hover')}
  function finishQuickDrag(event){if(!activeQuickDrag||event.pointerId!==activeQuickDrag.pointerId)return;const drag=activeQuickDrag,record=drag.record,price=ZychQuickAlerts.coordinateToPrice(candles,event.clientY-chartContainer.getBoundingClientRect().top);try{chartContainer.releasePointerCapture(event.pointerId)}catch{}activeQuickDrag=null;chart.applyOptions({handleScroll:true,handleScale:true});chartContainer.classList.remove('alert-line-dragging','alert-line-hover');if(!drag.moved){applyQuickPrice(record,quickUpdates.confirmed(record.id));const stage=chartContainer.parentElement.getBoundingClientRect();return openAlertLineMenu(record,Math.min(event.clientX-stage.left,stage.width-126),Math.min(event.clientY-stage.top,stage.height-72))}if(!price)return applyQuickPrice(record,quickUpdates.confirmed(record.id));applyQuickPrice(record,price);quickUpdates.commit(record.id,price,{update:(id,value)=>{chartContainer.dataset.alertUpdateRequests=String(Number(chartContainer.dataset.alertUpdateRequests||0)+1);return alertEngine.updatePrice(id,value)},apply:value=>applyQuickPrice(record,value),success:()=>{setHistoryStatus('Alert price updated','ready',1800);alertEngine.sync({notify:false}).catch(()=>{})},failure:()=>{setHistoryStatus('Alert update failed','error',2400);alertEngine.sync({notify:false}).catch(()=>{})}}).catch(()=>{})}
  function renderChartAlerts(){const alerts=ZychQuickAlerts.matchingAlerts(alertEngine.list(),state.selectedMarket.id),events=alertEngine.events().filter(event=>event.marketId===state.selectedMarket.id).slice(0,4),open=document.getElementById('chart-open-alerts'),recent=document.getElementById('chart-recent-alerts');document.getElementById('chart-open-alert-count').textContent=String(alerts.length);open.innerHTML=alerts.length?alerts.slice(0,4).map(alert=>{const paused=alert.status==='paused',action=paused?'resume':'pause';return `<div class="chart-bottom-row ${paused?'paused':''}"><span>${escapeHtml(alertDescription(alert))}</span><small class="alert-status-badge ${paused?'paused':''}">${paused?'Paused':'Active'}</small><span class="chart-bottom-actions"><button type="button" data-chart-alert-action="${action}" data-alert-id="${escapeHtml(alert.id)}">${paused?'Resume':'Pause'}</button><button type="button" data-chart-alert-delete="${escapeHtml(alert.id)}" aria-label="Delete alert">×</button></span></div>`}).join(''):`<div class="chart-bottom-empty">${escapeHtml(ZychI18n.t('chart.noOpenAlerts'))}</div>`;recent.innerHTML=events.length?events.map(event=>`<div class="chart-bottom-row"><span>${escapeHtml(eventDescription(event))}</span><small>${escapeHtml(formatAlertTime(event.triggeredAt))}</small></div>`).join(''):`<div class="chart-bottom-empty">${escapeHtml(ZychI18n.t('chart.noRecentAlerts'))}</div>`}
  const alertEngine=new ZychAlerts.ServerAlertClient({legacyStorage:alertStorage,notifier:browserNotifier,onChange:()=>{updateAlertCounter();renderAlertsPanel();renderQuickAlertLines();renderChartAlerts()},onStatus:status=>{alertMonitorStatus.dataset.status=status.toLowerCase();const labels={IDLE:'Alert engine idle',LIVE:'Monitoring live',RECONNECTING:'Feed reconnecting',STALE:'Market feed stale',OFFLINE:'Alert service offline',CONNECTING:'Checking alert service'};alertMonitorStatus.lastChild.textContent=` ${labels[status]||status}`}});
  chartContainer.addEventListener('contextmenu',event=>{if(matchMedia('(max-width:680px)').matches)return;event.preventDefault();const rect=chartContainer.getBoundingClientRect(),stage=chartContainer.parentElement.getBoundingClientRect(),record=quickLineAt(event.clientY-rect.top);quickMenu.close();closeAlertLineMenu();if(record)return openAlertLineMenu(record,Math.min(event.clientX-stage.left,stage.width-126),Math.min(event.clientY-stage.top,stage.height-72));const price=ZychQuickAlerts.coordinateToPrice(candles,event.clientY-rect.top);if(price)quickMenu.open({x:Math.min(event.clientX-stage.left,stage.width-190),y:Math.min(event.clientY-stage.top,stage.height-40),price,label:formatPrice(price)})});
  chartContainer.addEventListener('pointerdown',event=>{if(event.button!==0||matchMedia('(max-width:680px)').matches)return;quickMenu.close();const record=quickLineAt(event.clientY-chartContainer.getBoundingClientRect().top);if(!record){closeAlertLineMenu();return}event.preventDefault();event.stopPropagation();closeAlertLineMenu();activeQuickDrag={record,pointerId:event.pointerId,startX:event.clientX,startY:event.clientY,moved:false};chartContainer.setPointerCapture(event.pointerId);chart.applyOptions({handleScroll:false,handleScale:false})},true);
  chartContainer.addEventListener('pointermove',event=>{const y=event.clientY-chartContainer.getBoundingClientRect().top;if(activeQuickDrag){event.preventDefault();if(!activeQuickDrag.moved&&!ZychQuickAlerts.exceedsDragThreshold({x:activeQuickDrag.startX,y:activeQuickDrag.startY},event.clientX,event.clientY))return;activeQuickDrag.moved=true;chartContainer.classList.add('alert-line-dragging');const price=ZychQuickAlerts.coordinateToPrice(candles,y);if(price)applyQuickPrice(activeQuickDrag.record,price);return}chartContainer.classList.toggle('alert-line-hover',Boolean(quickLineAt(y)))});
  chartContainer.addEventListener('pointerup',finishQuickDrag);chartContainer.addEventListener('pointercancel',cancelQuickDrag);chartContainer.addEventListener('pointerleave',()=>{if(!activeQuickDrag)chartContainer.classList.remove('alert-line-hover')});
  chartContainer.addEventListener('wheel',()=>{quickMenu.close();closeAlertLineMenu()},{capture:true,passive:true});
  quickAlertElement.addEventListener('click',async event=>{if(!event.target.closest('[data-quick-alert-action]')||!quickMenu.payload)return;const market=state.selectedMarket,current=Number(state.marketSnapshots[market.id]?.lastPrice),price=quickMenu.payload.price;quickMenu.close();if(!Number.isFinite(current))return setHistoryStatus('Current price unavailable','error',2200);const result=await alertEngine.create(ZychQuickAlerts.definitionFor(market,price,current));setHistoryStatus(result.error?'Alert creation failed':result.warning?.message||'Alert created',result.error?'error':result.warning?'warning':'ready',result.warning?6500:2200)});
  alertLineMenu.addEventListener('click',event=>{const button=event.target.closest('[data-alert-line-action]');if(!button)return;const record=quickPriceLines.get(button.dataset.alertId);if(!record)return closeAlertLineMenu();const action=button.dataset.alertLineAction,target=action==='pause'?'paused':action==='resume'?'active':null;closeAlertLineMenu();quickActions.commit(record.id,target,{update:(id,status)=>{chartContainer.dataset.alertActionRequests=String(Number(chartContainer.dataset.alertActionRequests||0)+1);return status===null?alertEngine.deleteAlert(id):alertEngine.updateStatus(id,status)},apply:status=>applyQuickStatus(record,status),optimistic:target!==null,success:()=>{setHistoryStatus(target===null?'Alert deleted':target==='paused'?'Alert paused':'Alert resumed','ready',1800);alertEngine.sync({notify:false}).catch(()=>{})},failure:()=>{setHistoryStatus('Alert action failed','error',2400);alertEngine.sync({notify:false}).catch(()=>{})}}).catch(()=>{})});
  document.getElementById('terminal').addEventListener('click',event=>{const action=event.target.closest('[data-chart-alert-action]');if(action){action.disabled=true;const target=action.dataset.chartAlertAction==='pause'?'paused':'active';alertEngine.updateStatus(action.dataset.alertId,target).then(()=>alertEngine.sync({notify:false})).catch(()=>{action.disabled=false;setHistoryStatus('Alert action failed','error',2200)});return}const remove=event.target.closest('[data-chart-alert-delete]');if(remove){alertEngine.deleteAlert(remove.dataset.chartAlertDelete).then(()=>alertEngine.sync({notify:false})).catch(()=>setHistoryStatus('Alert delete failed','error',2200));return}const related=event.target.closest('[data-related-market]');if(related){const market=MARKETS.find(item=>item.id===related.dataset.relatedMarket);if(market)openMarketContext(ZychMarketContext.fromMarket(market,{timeframe:state.selectedTimeframe}))}});
  document.addEventListener('pointerdown',event=>{if(!event.target.closest('#quick-alert-menu'))quickMenu.close();if(!event.target.closest('#alert-line-menu')&&!event.target.closest('#chart'))closeAlertLineMenu()});document.addEventListener('keydown',event=>{if(event.key==='Escape'){quickMenu.close();closeAlertLineMenu()}});
  function suggestedPrice(){const price=Number(state.marketSnapshots[state.selectedMarket.id]?.lastPrice);if(!Number.isFinite(price)||price<=0)return'';const raw=price*1.01,power=10**Math.max(-8,Math.floor(Math.log10(raw))-2);return String(Math.ceil(raw/power)*power)}
  function openAlertDialog(){alertSound.unlock();const market=state.selectedMarket;document.getElementById('alert-market-label').textContent=`${marketLabel(market)} · ${EXCHANGES[market.exchange].label}`;alertForm.reset();alertForm.elements['price-value'].value=suggestedPrice();alertForm.elements['movement-percent'].value='3';alertForm.elements['volume-multiplier'].value='2';alertFormError.textContent='';updateAlertType();alertDialogBackdrop.hidden=false;setTimeout(()=>alertForm.querySelector('input:not([type="radio"]),select')?.focus(),0)}
  function closeAlertDialog(){alertDialogBackdrop.hidden=true}
  function updateAlertType(){const type=alertForm.elements['alert-type'].value;Object.entries(alertFieldsets).forEach(([name,element])=>element.hidden=name!==type)}
  function openAlertsPanel(){alertSound.unlock();alertsPanel.classList.add('open');alertsPanel.setAttribute('aria-hidden','false');alertsPanelBackdrop.hidden=false;renderAlertsPanel()}
  function closeAlertsPanel(){alertsPanel.classList.remove('open');alertsPanel.setAttribute('aria-hidden','true');alertsPanelBackdrop.hidden=true}
  alertTypeInputs.forEach(input=>input.addEventListener('change',updateAlertType));
  alertForm.addEventListener('submit',async event=>{event.preventDefault();const type=alertForm.elements['alert-type'].value,mode=alertForm.elements['alert-mode'].value,market=state.selectedMarket;let condition,error='';if(type==='price'){const value=Number(alertForm.elements['price-value'].value);if(!(value>0))error='Enter a price greater than 0.';condition={type:'price',operator:alertForm.elements['price-operator'].value,value}}else if(type==='movement'){const percent=Number(alertForm.elements['movement-percent'].value);if(!(percent>0))error='Enter a movement greater than 0%.';condition={type:'movement',direction:alertForm.elements['movement-direction'].value,percent,window:alertForm.elements['movement-window'].value}}else{const multiplier=Number(alertForm.elements['volume-multiplier'].value);if(!(multiplier>1))error='Choose a multiplier greater than 1x.';condition={type:'volume',multiplier,timeframe:alertForm.elements['volume-timeframe'].value,averageWindow:20}}if(error){alertFormError.textContent=error;return}const result=await alertEngine.create({marketId:market.id,marketType:market.marketType||'spot',asset:market.asset,baseAsset:market.asset,symbol:market.symbol,exchange:market.exchange,quoteAsset:market.quoteAsset,condition,mode});if(result.error){alertFormError.textContent=result.errorCode==='NETWORK_UNAVAILABLE'?ZychI18n.t('alert.serviceUnavailable'):result.error;return}closeAlertDialog();openAlertsPanel();if(result.warning)setHistoryStatus(result.warning.message,'warning',6500)});
  document.getElementById('create-alert-button').addEventListener('click',openAlertDialog);document.getElementById('radar-quick-alert')?.addEventListener('click',openAlertDialog);document.getElementById('alerts-button').addEventListener('click',openAlertsPanel);document.getElementById('mobile-alerts-button')?.addEventListener('click',openAlertsPanel);document.querySelector('[data-close-alert-dialog]').addEventListener('click',closeAlertDialog);alertDialogBackdrop.addEventListener('click',event=>{if(event.target===alertDialogBackdrop)closeAlertDialog()});document.querySelector('[data-close-alerts-panel]').addEventListener('click',closeAlertsPanel);alertsPanelBackdrop.addEventListener('click',closeAlertsPanel);
  soundSelect.addEventListener('change',()=>alertSound.setSound(soundSelect.value));soundVolume.addEventListener('change',()=>alertSound.setVolume(soundVolume.value));soundToggle.addEventListener('click',()=>alertSound.setEnabled(!alertSound.enabled));soundTest.addEventListener('click',()=>alertSound.preview(soundSelect.value));
  document.querySelector('.alerts-tabs').addEventListener('click',event=>{const button=event.target.closest('[data-alert-tab]');if(button){alertTab=button.dataset.alertTab;renderAlertsPanel()}});alertsList.addEventListener('click',async event=>{const open=event.target.closest('[data-alert-open]');if(open){openAlertContext(open.dataset.alertOpen,open.dataset.alertTimeframe);return}const action=event.target.closest('[data-alert-action]');if(action){event.stopPropagation();if(action.dataset.alertAction==='dismiss-event'){try{await alertEngine.removeEvent(action.dataset.eventId)}catch{alertMonitorStatus.dataset.status='offline';alertMonitorStatus.lastChild.textContent=' Backend offline'}return}const id=action.dataset.alertId,target=action.dataset.alertAction==='pause'?'paused':action.dataset.alertAction==='resume'?'active':null;hubActions.commit(id,target,{optimistic:target!==null,update:(alertId,status)=>{alertsPanel.dataset.actionRequests=String(Number(alertsPanel.dataset.actionRequests||0)+1);return status===null?alertEngine.deleteAlert(alertId):alertEngine.updateStatus(alertId,status)},apply:status=>{hubOverrides.set(id,status);renderAlertsPanel()},success:()=>{alertEngine.sync({notify:false}).then(()=>{hubOverrides.delete(id);renderAlertsPanel()}).catch(()=>{})},failure:()=>{alertMonitorStatus.dataset.status='offline';alertMonitorStatus.lastChild.textContent=' Backend offline';alertEngine.sync({notify:false}).then(()=>{hubOverrides.delete(id);renderAlertsPanel()}).catch(()=>{})}}).catch(()=>{});return}const row=event.target.closest('[data-alert-context]');if(row)openAlertContext(row.dataset.alertContext,row.dataset.alertTimeframe)});
  updateAlertCounter();renderAlertsPanel();renderChartAlerts();alertEngine.start();

  let snapshotController=null,universeController=null;
  async function refreshSnapshots(){
    snapshotController?.abort();snapshotController=new AbortController();
    const browseAssets=[state.selectedMarket.asset,'BTC','ETH','SOL'],savedMarkets=state.watchlist.map(item=>ZychWatchlist.resolve(item,MARKETS)).filter(Boolean),requestedMarkets=[...new Map(savedMarkets.concat(browseAssets.map(asset=>marketForAsset(asset)).filter(Boolean),state.selectedMarket.unavailable?[]:[state.selectedMarket]).map(market=>[market.id,market])).values()];
    try{const request=snapshotController,groups=Object.groupBy(requestedMarkets,market=>market.exchange),results=await Promise.all(Object.entries(groups).map(async([exchange,markets])=>exchangeAdapters[exchange].snapshots(markets,request.signal)));if(request!==snapshotController)return;const data=Object.assign({},...results);requestedMarkets.forEach(market=>{const snapshot=data[market.id];if(!snapshot)return;state.marketSnapshots[market.id]=snapshot;const key=ZychWatchlist.identity(market);if(ZychWatchlist.contains(state.watchlist,market))updateWatch(key,snapshot);if(market.id===marketForAsset(market.asset)?.id)updatePulse(market.asset,snapshot)});renderMarket();renderMarketsDashboard()}catch(error){if(error.name!=='AbortError'){document.getElementById('retry-button').hidden=false;renderMarketsDashboard()}}
  }
  async function loadUniverse(){
    universeController?.abort();universeController=new AbortController();universeStatus='loading';state.loadingState.universe=true;
    try{const loaded=await Promise.allSettled(Object.values(exchangeAdapters).map(async adapter=>({exchange:adapter.id,markets:await adapter.discover(universeController.signal),tickers:await adapter.allSnapshots(universeController.signal).catch(()=>[])}))),successful=loaded.filter(item=>item.status==='fulfilled').map(item=>item.value);if(!successful.length)throw new Error('No exchange catalogs');const previousMarketId=state.selectedMarket.id;normalizeUniverse(successful.flatMap(item=>item.markets));successful.flatMap(item=>item.tickers).forEach(row=>{const market=MARKETS.find(item=>item.id===row.marketId);if(market)state.marketSnapshots[market.id]=row});rebuildCatalogMetrics();document.documentElement.dataset.usdtAssets=String(MARKETS.filter(market=>market.quoteAsset==='USDT').length);document.documentElement.dataset.exchanges=successful.map(item=>item.exchange).join(',');universeStatus='ready';state.loadingState.universe=false;state.errorState.universe=null;saveWatchlist();saveWorkspace();resetWorkspaceSurfaces();renderMarket();if(!searchResults.hidden)drawSearch();if(state.selectedMarket.id!==previousMarketId)loadMarket();const resolved=await ZychMarketContext.resolveLocation(location.search).catch(()=>null);if(resolved?.context)openMarketContext(resolved.context);await refreshSnapshots()}
    catch(error){if(error.name==='AbortError')return;universeStatus='error';state.loadingState.universe=false;state.errorState.universe='Market universe unavailable';if(!searchResults.hidden)drawSearch();renderMarketsDashboard()}
  }
  document.getElementById('retry-button').addEventListener('click',()=>{refreshSnapshots();loadMarket();if(universeStatus==='error')loadUniverse()});const snapshotTimer=setInterval(refreshSnapshots,60000);window.addEventListener('beforeunload',()=>{clearInterval(snapshotTimer);clearTimeout(searchTimer);clearTimeout(historyStatusTimer);snapshotController?.abort();universeController?.abort();radarFeed.stop();stopMarket();alertEngine.stop()});
  renderWatchlist();renderMarket();renderMarketsDashboard();refreshSnapshots();loadMarket();loadUniverse();
})();
