'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const core=require('../js/alerts/alert-core.js');
const {JsonStorageAdapter}=require('../server/storage/json-storage.js');
const {ServerAlertRunner}=require('../server/alert-runner.js');
const {createHttpServer}=require('../server/http-server.js');
const {ServerAlertClient}=require('../js/alerts/server-alert-client.js');
const hub=require('../js/alerts/alert-hub.js');
const silent={debug(){},info(){},warn(){},error(){}};

test('real HTTP alert path persists, consumes controlled feed crossing, and reaches frontend hub state',async t=>{
  const directory=await fs.mkdtemp(path.join(os.tmpdir(),'zych-alert-e2e-')),storage=new JsonStorageAdapter({directory,core,logger:silent});await storage.init();
  class ControlledTransport{constructor(){this.handlers={};this.status='idle'}async start(alerts,handlers){this.alerts=alerts;this.handlers=handlers;this.status=alerts.length?'live':'idle';if(alerts.length)handlers.onStatus?.('live')}emit(event){this.handlers.onEvent?.(event)}async stop(){this.status='idle'}diagnostics(){return{status:this.status,connections:this.alerts?.length?1:0,subscriptions:this.alerts?.length||0,exchanges:{binance:{status:this.status,connections:this.alerts?.length?1:0,subscriptions:this.alerts?.length||0}}}}}
  const transport=new ControlledTransport(),runner=new ServerAlertRunner({core,storage,transport,notifier:{notify:async()=>{}},logger:silent,now:()=>Date.now()});await runner.start();
  const config={root:path.resolve(__dirname,'..'),production:false,allowedOrigins:[],vapidPublicKey:''},http=createHttpServer({runner,storage,notifier:{status:()=>({pushEnabled:false,pushSubscriptionsCount:0})},config,logger:silent}),server=http.server;await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  t.after(async()=>{await new Promise(resolve=>server.close(resolve));await runner.stop();await fs.rm(directory,{recursive:true,force:true})});
  const base=`http://127.0.0.1:${server.address().port}/api`,statuses=[],client=new ServerAlertClient({baseUrl:base,onStatus:value=>statuses.push(value)});
  const rejected=await fetch(`${base}/alerts`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({marketId:'evil:spot:BTCUSDT',exchange:'evil',marketType:'spot',symbol:'BTCUSDT',baseAsset:'BTC',quoteAsset:'USDT',condition:{type:'price',operator:'above',value:100},mode:'once'})});assert.equal(rejected.status,422);assert.equal((await rejected.json()).error.code,'INVALID_ALERT');
  const created=await client.create({marketId:'binance:BTCUSDT',exchange:'binance',symbol:'BTCUSDT',baseAsset:'BTC',quoteAsset:'USDT',condition:{type:'price',operator:'above',value:100},mode:'once'});
  assert.equal(created.alert.marketId,'binance:spot:BTCUSDT');assert.equal(JSON.parse(await fs.readFile(path.join(directory,'alerts-state.json'),'utf8')).alerts[0].marketId,'binance:spot:BTCUSDT');assert.equal(statuses.at(-1),'UNKNOWN');
  transport.emit({marketId:'binance:spot:BTCUSDT',exchange:'binance',marketType:'spot',symbol:'BTCUSDT',eventType:'ticker',price:99,timestamp:1});await runner.queue;
  transport.emit({marketId:'binance:spot:BTCUSDT',exchange:'binance',marketType:'spot',symbol:'BTCUSDT',eventType:'ticker',price:101,timestamp:2});await runner.queue;await client.sync({notify:false});
  assert.equal(client.events().length,1);assert.equal(client.events()[0].marketId,'binance:spot:BTCUSDT');assert.equal(hub.openContext(client.events()[0]).marketId,'binance:spot:BTCUSDT');assert.equal(client.list()[0].status,'triggered');
  const recross=await client.create({marketId:'binance:BTCUSDT',exchange:'binance',symbol:'BTCUSDT',baseAsset:'BTC',quoteAsset:'USDT',condition:{type:'price',operator:'above',value:90},mode:'once'});assert.equal(recross.warning.code,'WAITING_FOR_RECROSS');assert.match(recross.warning.message,/future directional recross/);
});

test('legacy persisted alert and trigger identities migrate without data loss',async()=>{const directory=await fs.mkdtemp(path.join(os.tmpdir(),'zych-alert-migrate-')),file=path.join(directory,'alerts-state.json');await fs.writeFile(file,JSON.stringify({alerts:[{id:'a',marketId:'binance:BTCUSDT',exchange:'binance',symbol:'BTCUSDT',baseAsset:'BTC',quoteAsset:'USDT',condition:{type:'price',operator:'above',value:100},status:'active',mode:'once',createdAt:1}],history:[{id:'t',alertId:'a',marketId:'binance:BTCUSDT',exchange:'binance',symbol:'BTCUSDT',triggeredAt:2}]}));const storage=new JsonStorageAdapter({directory,core,logger:silent});await storage.init();assert.equal(storage.loadAlerts()[0].marketId,'binance:spot:BTCUSDT');assert.equal(storage.loadTriggerHistory()[0].marketId,'binance:spot:BTCUSDT');await fs.rm(directory,{recursive:true,force:true})});

test('new alerts accept supported exchanges, reject unknown exchanges, and retain legacy unknown records',async()=>{for(const [exchange,symbol] of [['binance','BTCUSDT'],['bybit','BTCUSDT'],['okx','BTC-USDT']])assert.ok(core.createAlert({marketId:`${exchange}:spot:${symbol}`,exchange,marketType:'spot',symbol,baseAsset:'BTC',quoteAsset:'USDT',condition:{type:'price',operator:'above',value:100}},{id:exchange,now:1}));assert.equal(core.createAlert({marketId:'evil:spot:BTCUSDT',exchange:'evil',marketType:'spot',symbol:'BTCUSDT',baseAsset:'BTC',quoteAsset:'USDT',condition:{type:'price',operator:'above',value:100}},{id:'evil',now:1}),null);const directory=await fs.mkdtemp(path.join(os.tmpdir(),'zych-alert-legacy-exchange-')),file=path.join(directory,'alerts-state.json'),legacy={id:'legacy',marketId:'legacy:BTCUSDT',exchange:'legacy',symbol:'BTCUSDT',baseAsset:'BTC',quoteAsset:'USDT',condition:{type:'price',operator:'above',value:100},status:'paused',mode:'once',createdAt:1};await fs.writeFile(file,JSON.stringify({alerts:[legacy],history:[]}));const storage=new JsonStorageAdapter({directory,core,logger:silent});await storage.init();assert.equal(storage.loadAlerts()[0].exchange,'legacy');assert.equal(storage.loadAlerts()[0].marketId,'legacy:spot:BTCUSDT');await fs.rm(directory,{recursive:true,force:true})});
