'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{gzipSync}=require('node:zlib');
const fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const {BingxMarketTransport,decodeFrame,intervalMap}=require('../server/transports/bingx-market-transport');
const {MultiExchangeMarketTransport}=require('../server/transports/multi-exchange-market-transport');
const {ServerAlertRunner}=require('../server/alert-runner');
const {JsonStorageAdapter}=require('../server/storage/json-storage');
const core=require('../js/alerts/alert-core'),hub=require('../js/alerts/alert-hub'),quick=require('../js/alerts/quick-chart-alerts');
const silent={info(){},warn(){},error(){},debug(){}};
const definition=(operator='above',mode='once')=>({marketId:'bingx:spot:BTC-USDT',exchange:'bingx',marketType:'spot',symbol:'BTC-USDT',baseAsset:'BTC',quoteAsset:'USDT',condition:{type:'price',operator,value:100},mode,cooldownMs:5000});
const alert=()=>core.createAlert(definition(),{id:'test',now:1});
class Socket{
  static all=[];
  constructor(url){this.url=url;this.readyState=0;this.listeners={};this.sent=[];Socket.all.push(this)}
  addEventListener(name,fn){(this.listeners[name]??=[]).push(fn)}
  emit(name,data={}){if(name==='open')this.readyState=1;for(const fn of this.listeners[name]||[])fn(data)}
  send(data){this.sent.push(data)}
  close(){this.readyState=3}
}
const drain=async transport=>{await transport.context?.queue;};
async function frame(transport,socket,value){socket.emit('message',{data:gzipSync(typeof value==='string'?value:JSON.stringify(value))});await drain(transport)}
async function acknowledge(transport,socket){for(const value of socket.sent.filter(v=>v.startsWith('{'))){const request=JSON.parse(value);await frame(transport,socket,{id:request.id,code:0,msg:'SUCCESS'})}}
const price=(value,time=1000)=>({code:0,dataType:'BTC-USDT@lastPrice',timestamp:time,data:{s:'BTC-USDT',c:String(value)}});
async function setup(t,options={},alerts=[alert()]){const events=[],transport=new BingxMarketTransport({WebSocketImpl:Socket,reconnectBaseMs:10,reconnectMaxMs:10,...options});await transport.start(alerts,{onEvent:e=>events.push(e)});t.after(()=>transport.stop());const socket=Socket.all.at(-1);socket.emit('open');return{transport,socket,events}}
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));

test('BingX GZIP decodes buffers, ArrayBuffer, Blob, plain text and rejects malformed/oversized frames',async()=>{const bytes=gzipSync('{"ping":"x"}');assert.equal(await decodeFrame(bytes),'{"ping":"x"}');assert.equal(await decodeFrame(new Blob([bytes])),'{"ping":"x"}');assert.equal(await decodeFrame(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)),'{"ping":"x"}');assert.equal(await decodeFrame('Ping'),'Ping');await assert.rejects(decodeFrame(Buffer.from('bad')));await assert.rejects(decodeFrame('x'.repeat(1024*1024+1)));await assert.rejects(decodeFrame(gzipSync('x'.repeat(1024*1024+1))))});
test('BingX socket-open and heartbeat never acknowledge subscriptions; UUID positive ACK gates price',async t=>{const {transport,socket,events}=await setup(t);assert.equal(transport.diagnostics().status,'subscribing');const request=JSON.parse(socket.sent[0]);assert.match(request.id,/^[\da-f]{8}-[\da-f-]{27}$/);await frame(transport,socket,{ping:'abc',time:'123'});assert.equal(socket.sent.at(-1),'Pong');assert.equal(transport.diagnostics().acknowledgedSubscriptions,0);await frame(transport,socket,price(101));assert.equal(events.length,0);await acknowledge(transport,socket);await frame(transport,socket,price(101));assert.equal(events.length,1);assert.equal(events[0].marketId,'bingx:spot:BTC-USDT');assert.equal(events[0].symbol,'BTC-USDT');assert.equal(events[0].timestamp,1000);assert.equal(transport.diagnostics().status,'live');assert.equal(transport.diagnostics().pongCount,1)});
test('BingX all distinct topics require explicit ACK, with no duplicate subscription',async t=>{const movement={...alert(),type:'movement',condition:{type:'movement',window:'5m',direction:'up',percent:1}};const {transport,socket}=await setup(t,{},[alert(),alert(),movement]);assert.equal(socket.sent.length,2);const requests=socket.sent.map(JSON.parse);await frame(transport,socket,{id:requests[0].id,code:0});assert.equal(transport.diagnostics().status,'subscribing');assert.equal(transport.diagnostics().pendingAcknowledgements,1);await frame(transport,socket,{id:requests[1].id,code:0});assert.equal(transport.diagnostics().acknowledgedSubscriptions,2)});
test('BingX negative ACK is not LIVE',async t=>{const {transport,socket}=await setup(t);await frame(transport,socket,{id:JSON.parse(socket.sent[0]).id,code:100001});assert.equal(transport.diagnostics().status,'reconnecting');assert.equal(transport.diagnostics().lastError.code,'SUBSCRIBE_REJECTED');assert.equal(transport.diagnostics().activeSockets,0)});
test('BingX missing ACK times out even with heartbeat',async t=>{const {transport,socket}=await setup(t,{ackTimeoutMs:15,reconnectBaseMs:1000});await frame(transport,socket,{ping:'x'});await wait(35);assert.equal(transport.diagnostics().lastError.code,'ACK_TIMEOUT');assert.equal(transport.diagnostics().acknowledged,false)});
test('BingX heartbeat timeout reconnects; stale data cannot be kept LIVE by heartbeat',async t=>{let now=100;const {transport,socket}=await setup(t,{now:()=>now,heartbeatTimeoutMs:30,staleAfterMs:10,reconnectBaseMs:1000});await acknowledge(transport,socket);await frame(transport,socket,price(100));now=120;await frame(transport,socket,{ping:'x'});assert.equal(transport.diagnostics().status,'stale');await wait(50);assert.equal(transport.diagnostics().lastError.code,'HEARTBEAT_TIMEOUT')});
test('BingX reconnect creates fresh UUIDs, exact resubscription and rejects old same-generation callbacks',async t=>{const {transport,socket,events}=await setup(t);await acknowledge(transport,socket);await frame(transport,socket,price(99));const oldId=JSON.parse(socket.sent[0]).id;socket.emit('close',{code:1006,reason:'test disconnect'});await wait(30);const fresh=Socket.all.at(-1);assert.notEqual(fresh,socket);fresh.emit('open');assert.notEqual(JSON.parse(fresh.sent[0]).id,oldId);assert.equal(JSON.parse(fresh.sent[0]).dataType,'BTC-USDT@lastPrice');assert.equal(transport.diagnostics().acknowledgedSubscriptions,0);await frame(transport,fresh,{id:oldId,code:0});assert.equal(transport.diagnostics().status,'subscribing');await frame(transport,socket,price(200,2000));assert.equal(events.length,1);await acknowledge(transport,fresh);await frame(transport,fresh,price(101,2000));assert.equal(events.length,2);assert.equal(transport.diagnostics().reconnectCount,1);assert.equal(transport.diagnostics().lastDisconnect.reason,'test disconnect')});
test('BingX asynchronously decoded old-generation message cannot escape stop',async t=>{let release;const {transport,socket,events}=await setup(t,{decode:()=>new Promise(resolve=>release=resolve)});socket.emit('message',{data:'ignored'});await Promise.resolve();await transport.stop();release(JSON.stringify(price(101)));await drain(transport);await wait(0);assert.equal(events.length,0);assert.equal(transport.diagnostics().activeSockets,0)});
for(const [name,mutate] of [['missing exchange timestamp',p=>delete p.timestamp],['compact symbol',p=>p.data.s='BTCUSDT'],['invalid price',p=>p.data.c='NaN']])test(`BingX rejects ${name} without fallback`,async t=>{const {transport,socket,events}=await setup(t);await acknowledge(transport,socket);const value=price(101);mutate(value);await frame(transport,socket,value);assert.equal(events.length,0);assert.equal(transport.diagnostics().lastError.code,'MALFORMED_FRAME')});
test('BingX duplicate and out-of-order prices are not forwarded twice',async t=>{const {transport,socket,events}=await setup(t);await acknowledge(transport,socket);await frame(transport,socket,price(100,2000));await frame(transport,socket,price(100,2000));await frame(transport,socket,price(90,1000));assert.equal(events.length,1)});
test('BingX volume warm-up uses v2 closed quote volume, exact interval and never substitutes base volume',async t=>{const rows=Array.from({length:21},(_,i)=>[1000+i*300000,'100','110','90','105','9999',300999+i*300000,'10']);let url;const volume={...alert(),type:'volume',condition:{type:'volume',timeframe:'5m',multiplier:2}};const {transport}=await setup(t,{now:()=>6001000,fetchImpl:async value=>{url=value;return{ok:true,json:async()=>({code:0,data:rows.reverse()})}}},[volume]);assert.match(url,/spot\/v2\/market\/kline\?symbol=BTC-USDT&interval=5m/);const payload={dataType:'BTC-USDT@kline_5min',data:{s:'BTC-USDT',E:6001000,K:{s:'BTC-USDT',i:'5min',t:6001000,T:6300999,o:'100',h:'110',l:'90',c:'105',v:'9999',q:'25'}}};const event=transport.normalize(payload);assert.equal(event.volume,25);assert.equal(event.averageVolume,10);assert.equal(event.interval,'5m');delete payload.data.K.q;assert.equal(transport.normalize(payload),null);assert.equal(intervalMap['24h'],'1d')});
test('BingX missing warm-up remains unavailable rather than invented zero volume',async t=>{const volume={...alert(),type:'volume',condition:{type:'volume',timeframe:'5m',multiplier:2}};const {transport}=await setup(t,{fetchImpl:async()=>{throw Error('unavailable')}},[volume]);assert.equal(transport.diagnostics().lastError.code,'BASELINE_UNAVAILABLE');assert.equal(transport.baselines.size,0)});

test('BingX repeated closed candles keep 20 distinct preceding quote-volume samples',async t=>{const volume={...alert(),type:'volume',condition:{type:'volume',timeframe:'5m',multiplier:2}},rows=Array.from({length:20},(_,i)=>[1+i*300000,100,110,90,105,9999,300000+i*300000,10]);const {transport}=await setup(t,{now:()=>6300002,fetchImpl:async()=>({ok:true,json:async()=>({code:0,data:rows})})},[volume]);const payload={dataType:'BTC-USDT@kline_5min',data:{s:'BTC-USDT',E:6300001,K:{t:6000001,T:6300000,o:100,h:110,l:90,c:105,q:30}}};const first=transport.normalize(payload),duplicate=transport.normalize(payload);assert.equal(first.averageVolume,10);assert.equal(duplicate.averageVolume,10);assert.equal(transport.baselines.get('BTC-USDT:5m').size,21);payload.data.E=6300100;payload.data.K.t=6300001;payload.data.K.T=6600000;assert.equal(transport.normalize(payload).averageVolume,11)});

test('BingX existing movement and quote-volume semantics evaluate normalized candles',async t=>{for(const condition of [{type:'movement',window:'24h',direction:'up',percent:1},{type:'volume',timeframe:'5m',multiplier:2}]){const created=core.createAlert({...definition(),condition},{id:condition.type,now:1});const {transport}=await setup(t,{fetchImpl:async()=>({ok:true,json:async()=>({code:0,data:[]})})},[created]);const topic=transport.topics.find(value=>value.includes('kline'));const event=transport.normalize({dataType:topic,data:{s:'BTC-USDT',E:2000,K:{t:1000,T:3000,o:100,h:110,l:90,c:105,q:30}}});if(condition.type==='volume')event.averageVolume=10;assert.equal(core.processMarketEvent(created,event,{now:2000,eventId:'trigger'}).triggered,true);assert.equal(event.marketId,'bingx:spot:BTC-USDT')}});

test('BingX TriggerEvent uses shared toast/sound dedup and exact navigation',async()=>{const old=global.document,node=()=>({children:[],listeners:{},setAttribute(){},append(...items){this.children.push(...items)},addEventListener(type,fn){this.listeners[type]=fn},remove(){}});global.document={createElement:node};try{const {NotificationCenter}=require('../js/notifications/notification-center'),toasts=[];let plays=0,opened;const center=new NotificationCenter({region:{append:value=>toasts.push(value)},sound:{play:()=>plays++},describe:()=> 'crossing',formatTime:()=> '12:00',onOpen:event=>opened=hub.openContext(event),setTimer:()=>0});const event={...definition(),id:'unique-trigger',asset:'BTC',triggeredAt:1};const toast=center.notify(event);assert.equal(center.notify({...event}),null);toast.listeners.click();assert.equal(toasts.length,1);assert.equal(plays,1);assert.equal(opened.marketId,'bingx:spot:BTC-USDT')}finally{global.document=old}});

async function runnerFixture(t){const directory=await fs.mkdtemp(path.join(os.tmpdir(),'zych-bingx-unit-')),storage=new JsonStorageAdapter({directory,core,logger:silent});await storage.init();let now=10000;const transport=new BingxMarketTransport({WebSocketImpl:Socket}),router=new MultiExchangeMarketTransport({transports:{bingx:transport},logger:silent}),notifications=[],runner=new ServerAlertRunner({core,storage,transport:router,notifier:{notify:async e=>notifications.push(e)},logger:silent,now:()=>now});await runner.start();t.after(async()=>{await runner.stop();assert.equal(path.dirname(directory),os.tmpdir());assert.ok(path.basename(directory).startsWith('zych-bingx-unit-'));await fs.rm(directory,{recursive:true,force:true})});return{runner,storage,transport,notifications,directory,setNow:value=>now=value,async connect(){const socket=Socket.all.at(-1);socket.emit('open');await acknowledge(transport,socket);return socket},async tick(socket,value,time){await frame(transport,socket,price(value,time));await runner.queue}}}
for(const operator of ['above','below'])test(`BingX authoritative ${operator}: first satisfied tick waits for recross, exactly one persisted trigger`,async t=>{const f=await runnerFixture(t),created=await f.runner.create(definition(operator)),socket=await f.connect(),satisfied=operator==='above'?101:99,other=operator==='above'?99:101;await f.tick(socket,satisfied,1000);await f.tick(socket,satisfied,2000);assert.equal(f.runner.events().length,0);await f.tick(socket,other,3000);await f.tick(socket,satisfied,4000);await f.tick(socket,satisfied,4000);assert.equal(f.runner.events().length,1);assert.equal(f.notifications.length,1);assert.equal(f.runner.events()[0].marketId,'bingx:spot:BTC-USDT');assert.equal(f.runner.events()[0].alertId,created.alert.id);const reload=new JsonStorageAdapter({directory:f.directory,core,logger:silent});await reload.init();assert.equal(reload.loadAlerts()[0].symbol,'BTC-USDT');assert.equal(reload.loadTriggerHistory().length,1);await reload.close()});
test('BingX recurring re-arms, preserves cooldown and triggers once per valid recross',async t=>{const f=await runnerFixture(t);await f.runner.create(definition('above','recurring'));const socket=await f.connect();await f.tick(socket,99,1000);await f.tick(socket,101,2000);await f.tick(socket,102,3000);assert.equal(f.runner.events().length,1);f.setNow(11000);await f.tick(socket,99,4000);await f.tick(socket,101,5000);assert.equal(f.runner.events().length,1);f.setNow(16000);await f.tick(socket,99,6000);await f.tick(socket,101,7000);assert.equal(f.runner.events().length,2);assert.equal(f.notifications.length,2)});
test('BingX same-ID Chart update, failed drag rollback, pause/resume/delete, persistence and exact Hub navigation',async t=>{const f=await runnerFixture(t),{alert:created}=await f.runner.create(definition());assert.equal(hub.openContext(created).marketId,'bingx:spot:BTC-USDT');assert.match(hub.marketText(created),/BINGX/);assert.deepEqual(quick.matchingAlerts(f.runner.list(),'bingx:spot:BTC-USDT').map(a=>a.id),[created.id]);assert.equal(quick.matchingAlerts(f.runner.list(),'binance:spot:BTCUSDT').length,0);const updates=new quick.UpdateCoordinator(),applied=[];updates.register(created.id,100);await updates.commit(created.id,110,{update:(id,value)=>f.runner.updatePrice(id,value),apply:v=>applied.push(v)});assert.equal(f.runner.list()[0].id,created.id);assert.equal(f.runner.list()[0].condition.value,110);await assert.rejects(updates.commit(created.id,120,{update:async()=>{throw Error('server unavailable')},apply:v=>applied.push(v)}));assert.equal(applied.at(-1),110);await f.runner.pause(created.id);assert.equal(f.runner.list()[0].status,'paused');assert.equal(quick.matchingAlerts(f.runner.list(),'bingx:spot:BTC-USDT').length,1);await f.runner.resume(created.id);assert.equal(f.runner.list()[0].status,'active');await f.runner.remove(created.id);assert.equal(f.runner.list().length,0)});
test('BingX registration and UI guards share existing runner/allowlist; Radar uses its own BingX candle adapter',async()=>{const app=await fs.readFile(path.join(__dirname,'../server/app.js'),'utf8'),ui=await fs.readFile(path.join(__dirname,'../app.js'),'utf8');assert.ok(core.SUPPORTED_EXCHANGES.includes('bingx'));assert.match(app,/bingx: new BingxMarketTransport/);assert.equal((app.match(/new ServerAlertRunner/g)||[]).length,1);assert.match(app,/new CandleStreamAdapter\(\{exchange:'bingx'/);assert.match(ui,/ZychAlertCore\.SUPPORTED_EXCHANGES/);assert.match(ui,/new ZychAlerts\.ServerAlertClient/);assert.doesNotMatch(ui,/new ZychAlerts\.AlertEngine/)});

test('BingX fresh runner restart restores exact identity and subscribes once without a startup trigger',async t=>{const f=await runnerFixture(t),created=await f.runner.create(definition());await f.runner.stop();const storage=new JsonStorageAdapter({directory:f.directory,core,logger:silent});await storage.init();const transport=new BingxMarketTransport({WebSocketImpl:Socket}),runner=new ServerAlertRunner({core,storage,transport,notifier:{notify:async()=>{}},logger:silent});try{await runner.start();assert.equal(runner.list()[0].id,created.alert.id);assert.equal(runner.list()[0].marketId,'bingx:spot:BTC-USDT');const socket=Socket.all.at(-1);socket.emit('open');assert.equal(socket.sent.length,1);await acknowledge(transport,socket);await frame(transport,socket,price(101));await runner.queue;assert.equal(runner.events().length,0)}finally{await runner.stop()}});
