'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{gzipSync}=require('node:zlib');
const {BingxCatalogAdapter}=require('../server/radar/catalog-adapters'),{CandleHistoryAdapter}=require('../server/radar/candle-history-adapters'),{CandleStreamAdapter}=require('../server/radar/candle-stream-adapters');
const {normalizeBingxCandle,normalizeStream}=require('../server/radar/candle-adapters'),{radarCoverage}=require('../server/radar/coverage');
const {MarketStateStore}=require('../server/radar/market-state-store'),{RecoveryCoordinator}=require('../server/radar/recovery-coordinator');
const {PriceMomentumDetector}=require('../server/radar/detectors/price-momentum');
const {QualificationPolicy}=require('../server/radar/qualification-policy'),{UnifiedEventBuilder}=require('../server/radar/unified-event-builder'),{validateUnifiedEvent}=require('../server/radar/event-schema');
const radarUI=require('../js/services/radar-event'),{MarketUniverseService}=require('../server/radar/market-universe-service'),{loadConfig}=require('../server/config');
const market={marketId:'bingx:spot:BTC-USDT',exchange:'bingx',marketType:'spot',symbol:'BTC-USDT',baseAsset:'BTC',quoteAsset:'USDT'};
const row=(t=60000)=>[t,'100','102','99','101','3',t+59999,'303'];
const payload=(tf='1m',time=60000)=>({code:0,dataType:`BTC-USDT@kline_${tf.replace('m','min')}`,data:{s:'BTC-USDT',E:time+10,K:{s:'BTC-USDT',i:tf.replace('m','min'),t:time,T:time+59999,o:100,h:102,l:99,c:101,v:3,q:303}}});
class Socket{static all=[];constructor(){this.readyState=0;this.listeners={};this.sent=[];Socket.all.push(this)}addEventListener(type,fn){this.listeners[type]=fn}send(value){this.sent.push(value)}emit(type,value={}){if(type==='open')this.readyState=1;return this.listeners[type]?.(value)}close(){this.readyState=3}}
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
test('four-exchange event API, frontend selection and alert identity remain exact and isolated',async t=>{
  const {createCandidateEvent}=require('../server/radar/event-schema'),{UnifiedEventStore}=require('../server/radar/event-store'),{RadarEventPipeline}=require('../server/radar/event-pipeline'),{createHttpServer}=require('../server/http-server'),core=require('../js/alerts/alert-core'),hub=require('../js/alerts/alert-hub');
  const store=new UnifiedEventStore(),policy=new QualificationPolicy(),builder=new UnifiedEventBuilder(),pipeline=new RadarEventPipeline({store,promote:candidate=>builder.build(policy.evaluate({candidate}))});
  for(const exchange of ['binance','bybit','okx','bingx']){const symbol=['binance','bybit'].includes(exchange)?'BTCUSDT':'BTC-USDT',identity={...market,exchange,symbol,marketId:`${exchange}:spot:${symbol}`},now=Date.now();const candidate=createCandidateEvent({detectorId:'price-momentum',detectorVersion:'1',eventType:'PRICE_MOMENTUM_UP',market:identity,timeframe:'1m',eventTimestamp:now-60000,observedAt:now,metrics:{price:100,priceChangePct:5,deviationZScore:6},metadata:{warmupStatus:'READY',dataQuality:'COMPLETE'}});pipeline.publishCandidate(candidate);const alert=core.createAlert({...identity,condition:{type:'price',operator:'above',value:101}},{id:exchange,now});assert.equal(hub.openContext(alert).marketId,identity.marketId)}
  await pipeline.idle();assert.equal(store.size,4);const http=createHttpServer({config:{production:false},eventStore:store,universe:{health:()=>({coverage:catalog})},radar:{coverage:value=>radarCoverage(value,{exchanges:{bingx:live}})},logger:{error(){},warn(){}}});await new Promise(resolve=>http.server.listen(0,'127.0.0.1',resolve));t.after(async()=>{await new Promise(resolve=>http.server.close(resolve));await pipeline.stop();store.stop()});
  const base=`http://127.0.0.1:${http.server.address().port}`;
  for(const exchange of ['binance','bybit','okx','bingx']){const response=await fetch(`${base}/api/radar/events?exchange=${exchange}`);assert.equal(response.status,200);const body=await response.json();assert.equal(body.events.length,1);assert.equal(body.meta.coverage.healthyExchanges.length,4);const event=radarUI.create(body.events[0]);assert.equal(event.exchange,exchange);assert.equal(radarUI.filter([event],{exchange}).length,1);const selected=radarUI.resolveSelection(event,[{...body.events[0].market,id:event.marketId,enabled:true}],{supportedTimeframes:['1m']});assert.equal(selected.context.marketId,event.marketId)}
  assert.equal((await fetch(`${base}/api/radar/events?exchange=unknown`)).status,400);
});
async function frame(socket,value){await socket.emit('message',{data:gzipSync(typeof value==='string'?value:JSON.stringify(value))})}
async function setup(t,options={},timeframes=['1m','5m','15m']){const candles=[],stream=new CandleStreamAdapter({exchange:'bingx',WebSocketImpl:Socket,reconnectBaseMs:10,...options});await stream.start([market,market],timeframes,{onCandle:value=>candles.push(value)});t.after(()=>stream.stop());const socket=Socket.all.at(-1);socket.emit('open');return{stream,socket,candles}}
async function ack(socket){for(const raw of socket.sent){if(raw==='Pong')continue;await frame(socket,{id:JSON.parse(raw).id,code:0})}}
test('BingX catalog verifies exact status and buy/sell flags, derives native assets and ranks quote not base volume',async()=>{const symbols=[{symbol:'BTC-USDT',status:1,apiStateBuy:true,apiStateSell:true},{symbol:'BAD-USDT',status:2,apiStateBuy:true,apiStateSell:true},{symbol:'OFF-USDT',status:1,apiStateBuy:false,apiStateSell:true}];const adapter=new BingxCatalogAdapter({now:()=>1000,fetchImpl:async url=>({ok:true,json:async()=>({code:0,data:url.includes('symbols')?{symbols}:[{symbol:'BTC-USDT',volume:'999999',quoteVolume:'100000000'}]})})});const rows=await adapter.load();assert.equal(rows.length,1);assert.equal(rows[0].marketId,market.marketId);assert.equal(rows[0].quoteVolume24h,100000000);assert.equal(rows[0].baseAsset,'BTC');const service=new MarketUniverseService({catalog:{refresh:async()=>({exchanges:{bingx:{status:'HEALTHY',markets:rows}}})},policy:loadConfig({}).universePolicy,now:()=>1001,refreshIntervalMs:0});await service.initialize();assert.equal(service.getSnapshot().markets[0].marketId,market.marketId);await service.stop()});
test('BingX catalog rejects failed/malformed envelopes and does not substitute missing quote volume',async()=>{const adapter=new BingxCatalogAdapter({fetchImpl:async()=>({ok:true,json:async()=>({code:1,data:[]})})});await assert.rejects(adapter.load());const missing=new BingxCatalogAdapter({fetchImpl:async url=>({ok:true,json:async()=>({code:0,data:url.includes('symbols')?{symbols:[{symbol:'BTC-USDT',status:1,apiStateBuy:true,apiStateSell:true}]}:[{symbol:'BTC-USDT',volume:9999}]})})});assert.equal((await missing.load())[0].quoteVolume24h,null)});
test('BingX candle preserves both volumes and timestamps, rejects missing/invalid fields and never falls back',()=>{const value=normalizeBingxCandle(market,'1m',row(),{now:120000,closed:true});assert.equal(value.volume,3);assert.equal(value.quoteVolume,303);assert.equal(value.closeTime,119999);for(const index of [0,1,2,3,4,5,6,7]){const invalid=row();invalid[index]=null;assert.throws(()=>normalizeBingxCandle(market,'1m',invalid))}assert.throws(()=>normalizeBingxCandle({...market,exchange:'okx'},'1m',row()));assert.equal(normalizeStream('bingx',market,'1m',{...payload(),data:{...payload().data,s:'BTCUSDT'}}),null)});
for(const timeframe of ['1m','5m','15m'])test(`BingX ${timeframe} REST v2 native request, range, closed-only, order and dedup`,async()=>{let url;const adapter=new CandleHistoryAdapter({exchange:'bingx',restBase:'https://test',now:()=>180000,fetchImpl:async value=>{url=value;return{ok:true,json:async()=>({code:0,data:[row(120000),row(),row()]})}}});const values=await adapter.fetch(market,timeframe,{from:60000,to:120000,limit:70});assert.match(url,new RegExp(`symbol=BTC-USDT&interval=${timeframe}&limit=70&startTime=60000&endTime=120000`));assert.deepEqual(values.map(v=>v.openTime),[60000,120000]);assert.ok(values.every(v=>v.isClosed));await assert.rejects(new CandleHistoryAdapter({exchange:'unknown'}).fetch(market,timeframe))});
test('BingX Radar open, one ACK and heartbeat never imply full coverage; every topic needs ACK and data',async t=>{const{stream,socket}=await setup(t);assert.equal(socket.sent.length,3);assert.equal(stream.diagnostics().status,'subscribing');const requests=socket.sent.map(JSON.parse);assert.equal(new Set(requests.map(r=>r.id)).size,3);await frame(socket,{id:requests[0].id,code:0});await frame(socket,{ping:'real',time:'123'});assert.equal(socket.sent.at(-1),'Pong');assert.equal(stream.diagnostics().acknowledgedTopics,1);assert.equal(stream.diagnostics().status,'partial');await ack(socket);assert.notEqual(stream.diagnostics().status,'live');for(const tf of ['1m','5m','15m'])await frame(socket,payload(tf));assert.equal(stream.diagnostics().status,'live');assert.equal(stream.diagnostics().freshTopics,3)});
test('BingX negative and missing ACK expose failed topics and recover',async t=>{const{stream,socket}=await setup(t,{ackTimeoutMs:40,reconnectBaseMs:1000});const requests=socket.sent.map(JSON.parse);await frame(socket,{id:requests[0].id,code:0});await frame(socket,{id:requests[1].id,code:1});assert.equal(stream.diagnostics().failedTopics,1);assert.equal(stream.diagnostics().status,'partial');await sleep(60);assert.equal(stream.diagnostics().failedTopics,2);assert.equal(stream.diagnostics().status,'offline');assert.equal(stream.diagnostics().lastError.code,'ACK_TIMEOUT')});
test('BingX reconnect resets state, resubscribes with fresh UUIDs and ignores old callbacks',async t=>{const{stream,socket,candles}=await setup(t,{},['1m']);await ack(socket);await frame(socket,payload());const id=JSON.parse(socket.sent[0]).id;socket.emit('close',{code:1006,reason:'test'});await sleep(30);const next=Socket.all.at(-1);next.emit('open');assert.notEqual(JSON.parse(next.sent[0]).id,id);assert.equal(stream.diagnostics().acknowledgedTopics,0);await frame(socket,payload('1m',120000));assert.equal(candles.length,1);await ack(next);await frame(next,payload('1m',120000));assert.equal(candles.length,2);assert.equal(stream.diagnostics().reconnectCount,1)});
test('BingX heartbeat cannot conceal stale candles and heartbeat timeout reports failure',async t=>{let now=1;const{stream,socket}=await setup(t,{now:()=>now,staleAfterMs:10,heartbeatTimeoutMs:40,reconnectBaseMs:1000},['1m']);await ack(socket);await frame(socket,payload());now=20;await frame(socket,{ping:'x'});assert.equal(stream.diagnostics().status,'stale');await sleep(60);assert.equal(stream.diagnostics().heartbeatFailures,1);assert.equal(stream.diagnostics().status,'offline')});
test('BingX corrupt GZIP is counted and never becomes a candle',async t=>{const{stream,socket,candles}=await setup(t,{reconnectBaseMs:1000},['1m']);socket.emit('message',{data:Buffer.from('bad gzip')});await sleep(10);assert.equal(stream.diagnostics().decompressionFailures,1);assert.equal(candles.length,0);assert.equal(stream.diagnostics().status,'offline')});
test('BingX rollover closes observed candle once; out-of-order old period is ignored',async t=>{const{socket,candles}=await setup(t,{},['1m']);await ack(socket);await frame(socket,payload());await frame(socket,payload('1m',120000));await frame(socket,payload());assert.equal(candles.filter(v=>v.isClosed).length,1);assert.equal(candles[1].close,101);assert.equal(candles[1].quoteVolume,303);assert.equal(candles[1].openTime,60000)});
const names=['binance','bybit','okx','bingx'],catalog={status:'HEALTHY',expectedExchanges:names,healthyExchanges:names,exchanges:Object.fromEntries(names.map(n=>[n,{status:'HEALTHY'}]))},live={status:'live',activeSockets:1,requestedTopics:3,acknowledgedTopics:3,failedTopics:0,freshTopics:3,stateQuality:{total:3,COMPLETE:3}};
test('Binance combined-stream envelope reaches normalized rolling candle contract',()=>{const binance={...market,exchange:'binance',symbol:'BTCUSDT',marketId:'binance:spot:BTCUSDT'},k={t:60000,T:119999,o:'100',h:'102',l:'99',c:'101',v:'3',q:'303',x:true},value=normalizeStream('binance',binance,'1m',{stream:'btcusdt@kline_1m',data:{s:'BTCUSDT',k}},120000);assert.equal(value.isClosed,true);assert.equal(value.close,101);assert.equal(value.marketId,binance.marketId)});
test('legacy exchange disconnect cannot claim full coverage from REST warm-up alone',()=>{const result=radarCoverage(catalog,{exchanges:{binance:{subscriptions:3,activeSockets:0,stateQuality:{total:3,COMPLETE:3}},bingx:live}});assert.equal(result.healthyExchanges.length,3);assert.equal(result.exchanges.binance.status,'OFFLINE')});
test('catalog-only BingX with no requested topics cannot claim full Radar coverage',()=>{assert.equal(radarCoverage(catalog,{exchanges:{bingx:{requestedTopics:0,activeSockets:0}}}).healthyExchanges.length,3)});
test('partial BingX ACK coverage keeps lifecycle DEGRADED instead of READY',()=>{const {HealthService}=require('../server/health-service'),{ApplicationLifecycle}=require('../server/lifecycle');const lifecycle=new ApplicationLifecycle();lifecycle.transition('WARMING_UP',[]);let stream={...live,acknowledgedTopics:1};const health=new HealthService({lifecycle,now:()=>1000,universe:{health:()=>({coverage:catalog})},radar:{running:true,selected:new Map([['x',{}]]),stats:{lastHealthyProcessingTimestamp:1000},store:{diagnostics:()=>({totalStateEntries:12,COMPLETE:12})},coverage:value=>radarCoverage(value,{exchanges:{bingx:stream}})}});assert.equal(health.assess().lifecycle,'DEGRADED');stream=live;assert.equal(health.assess().lifecycle,'READY')});
test('supervisor diagnostics count one reconnect once rather than adding the callback again',()=>{const {IngestionSupervisor}=require('../server/radar/ingestion-supervisor');const supervisor=new IngestionSupervisor({store:new MarketStateStore(),streams:{bingx:{diagnostics:()=>({...live,reconnectCount:1})}}});supervisor.stats.reconnectCount=1;assert.equal(supervisor.diagnostics().reconnectCount,1)});
test('BingX delayed decompression cannot affect a stopped generation',async t=>{let release;const{stream,socket,candles}=await setup(t,{decode:()=>new Promise(resolve=>release=resolve)},['1m']);socket.emit('message',{data:'deferred'});await Promise.resolve();await stream.stop();release(JSON.stringify(payload()));await sleep(5);assert.equal(candles.length,0);assert.equal(stream.diagnostics().lastMessageTimestamp,null)});
test('BingX sharding retains partial coverage when one socket fails',async t=>{const stream=new CandleStreamAdapter({exchange:'bingx',WebSocketImpl:Socket,maxTopicsPerSocket:1,reconnectBaseMs:1000});t.after(()=>stream.stop());await stream.start([market],['1m','5m']);const sockets=Socket.all.slice(-2);for(const socket of sockets){socket.emit('open');await ack(socket)}await frame(sockets[0],payload('1m'));await frame(sockets[1],payload('5m'));assert.equal(stream.diagnostics().status,'live');sockets[1].emit('close',{code:1006});assert.equal(stream.diagnostics().status,'partial');assert.equal(stream.diagnostics().activeSockets,1);assert.equal(stream.diagnostics().acknowledgedTopics,1)});
for(const [state,expected] of [[live,'HEALTHY'],[{...live,acknowledgedTopics:2,failedTopics:1},'PARTIAL'],[{...live,status:'stale'},'STALE'],[{...live,activeSockets:0},'OFFLINE'],[{...live,stateQuality:{total:3,COMPLETE:2}},'PARTIAL']])test(`four-exchange coverage honestly handles BingX ${expected}`,()=>{const result=radarCoverage(catalog,{exchanges:{bingx:state}});assert.equal(result.expectedExchanges.length,4);assert.equal(result.exchanges.bingx.status,expected);assert.equal(result.healthyExchanges.length,expected==='HEALTHY'?4:3);assert.equal(result.status,expected==='HEALTHY'?'HEALTHY':'DEGRADED')});
test('BingX generic recovery loads, fills a gap, preserves continuity and marks stale',async()=>{let now=300000;const store=new MarketStateStore({minimumLookback:2,now:()=>now}),adapter=new CandleHistoryAdapter({exchange:'bingx',restBase:'https://test',now:()=>300000,fetchImpl:async()=>({ok:true,json:async()=>({code:0,data:[row(60000),row(120000),row(180000)]})})}),recovery=new RecoveryCoordinator({store,adapters:{bingx:adapter}});try{await recovery.enqueue({kind:'warmup',market,timeframe:'1m',limit:3});assert.equal(store.get(market.marketId,'1m').dataQuality,'COMPLETE');now=1000000;store.markStale(180000);assert.equal(store.get(market.marketId,'1m').dataQuality,'STALE');await recovery.enqueue({kind:'gap',market,timeframe:'1m',from:120000,to:180000});assert.equal(store.get(market.marketId,'1m').continuityVerified,true)}finally{await recovery.stop();store.stop()}});
test('BingX deterministic candles use unchanged detector and qualification, event schema and exact UI selection',()=>{const now=Date.now(),candles=Array.from({length:70},(_,i)=>{const close=i===69?120:100+(i%2)*.1;return normalizeBingxCandle(market,'1m',[now-(70-i)*60000,100,121,99,close,10,now-(69-i)*60000-1,1000],{now,closed:true})});const detector=new PriceMomentumDetector(),candidate=detector.evaluate({market,event:candles.at(-1),state:{dataQuality:'COMPLETE',candles}})[0];assert.ok(candidate);const qualified=new QualificationPolicy().evaluate({candidate});assert.equal(qualified.qualified,true);const event=new UnifiedEventBuilder().build(qualified);assert.equal(validateUnifiedEvent(event).valid,true);const normalized=radarUI.create(event);assert.equal(normalized.marketId,market.marketId);const selected=radarUI.resolveSelection(normalized,[{...market,id:market.marketId,enabled:true}],{supportedTimeframes:['1m'],currentTimeframe:'5m'});assert.equal(selected.context.marketId,market.marketId);assert.equal(selected.context.symbol,'BTC-USDT');assert.equal(selected.context.timeframe,'1m')});
