'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const chart=require('../js/exchanges/kraken-chart.js'),{KrakenBrowserAdapter}=require('../js/exchanges/kraken-browser.js'),watch=require('../js/services/watchlist-markets.js'),context=require('../js/services/market-context.js');
const market={id:'kraken:spot:XXBTZUSD',symbol:'XXBTZUSD',exchange:'kraken',marketType:'spot',baseAsset:'BTC',asset:'BTC',quoteAsset:'USD',enabled:true};
const time=1788393600,raw=(t=time,v='12')=>[t,'100','110','90','105','102',v,8];
class Socket{constructor(url){this.url=url;this.readyState=0;this.listeners={};this.sent=[];}addEventListener(k,f){this.listeners[k]=f;}send(s){this.sent.push(JSON.parse(s));}open(){this.readyState=1;this.listeners.open();}message(p){this.listeners.message({data:JSON.stringify(p)});}close(){this.readyState=3;this.listeners.close?.({});}}
function setup(t,frame='1m'){
 const calls=[],sockets=[],a=new KrakenBrowserAdapter({now:()=> (time+30)*1000,requestSpacingMs:0,socketFactory:url=>{const s=new Socket(url);sockets.push(s);return s;},fetchImpl:async url=>{calls.push(url);return {ok:true,text:async()=>JSON.stringify({error:[],result:{XXBTZUSD:[raw(time-60),raw()],last:time}})};}});
 a.mapping={byNative:new Map([['XXBTZUSD',{nativeSymbol:'XXBTZUSD',wsSymbol:'BTC/USD',baseAsset:'BTC',quoteAsset:'USD'}]])};
 const statuses=[],values=[],repairs=[],errors=[];const handlers={status:s=>statuses.push(s),candle:c=>values.push(c),reconcile:r=>repairs.push(r),error:e=>errors.push(e)};
 const ws=a.socket(market,frame,handlers);t.after(()=>{sockets.forEach(s=>s.close());a.dispose();});return {a,ws,calls,sockets,statuses,values,repairs,errors,handlers};
}
const flush=()=>new Promise(resolve=>setImmediate(resolve));
const ack=(interval=1)=>({method:'subscribe',req_id:1,success:true,result:{channel:'ohlc',symbol:'BTC/USD',interval,snapshot:true}});
const event=(type='update',interval=1,at=time,volume=13)=>({channel:'ohlc',type,data:[{symbol:'BTC/USD',interval,interval_begin:new Date(at*1000).toISOString(),timestamp:new Date((at+interval*60)*1000).toISOString(),open:100,high:110,low:90,close:106,vwap:102,volume,trades:9}]});
for(const [frame,interval]of Object.entries(chart.intervals))test(`Kraken REST ${frame}: native endpoint, chronology, provisional tail, cap`,async t=>{const s=setup(t,frame),rows=await s.a.candles(market,frame);const url=new URL(s.calls[0]);assert.equal(url.origin,'https://api.kraken.com');assert.equal(url.pathname,'/0/public/OHLC');assert.equal(url.searchParams.get('pair'),'XXBTZUSD');assert.equal(url.searchParams.get('interval'),String(interval));assert.equal(url.searchParams.has('since'),false);assert.deepEqual(rows.map(r=>r.time),[time-60,time]);assert.equal(rows[0].provisional,false);assert.equal(rows[1].provisional,true);assert.equal(rows[1].volume,12);assert.equal(rows.exhausted,true);assert.match(rows.historyLimit,/HISTORY LIMITED/);});
test('Kraken 1M and foreign/unadmitted identities fail closed without network',async t=>{const s=setup(t);for(const m of [{...market,symbol:'BTC/USD'},{...market,exchange:'binance'},{...market,quoteAsset:'USDT'},{...market,symbol:'UNKNOWN'}])await assert.rejects(s.a.candles(m,'1m'),/admitted/);await assert.rejects(s.a.candles(market,'1M'),/Unsupported/);assert.throws(()=>s.a.socket(market,'1M',{}),/Unsupported/);assert.equal(s.calls.length,0);assert.equal(chart.intervals['1M'],undefined);assert.ok(!Object.values(chart.intervals).includes(21600));});
test('Kraken normalization rejects missing OHLC/volume without manufacturing values',()=>{for(const index of [0,1,2,3,4,6])for(const value of [null,'',undefined,'bad']){const row=raw();row[index]=value;assert.throws(()=>chart.normalize(row),/Malformed/);}assert.equal(chart.normalize(raw(time,'0')).volume,0);assert.throws(()=>chart.normalize(raw(time,-1)),/Malformed/);});
test('Kraken 720/721 retained rows exhaust shared history and older requests do no network',async t=>{const s=setup(t);const sandbox={window:{},Date,AbortController,setTimeout,clearTimeout};vm.runInNewContext(fs.readFileSync(require.resolve('../js/services/chart-history.js'),'utf8'),sandbox);for(const size of [720,721]){let calls=0;s.a.request=async()=>{calls++;return {XXBTZUSD:Array.from({length:size},(_,i)=>raw(time-(size-i-1)*60)).reverse(),last:time};};const h=new sandbox.window.ZychChartHistory.ChartHistoryService({adapters:{kraken:s.a}}),initial=await h.initial(market,'1m');assert.equal(initial.data.length,size);assert.equal(initial.endReached,true);assert.equal(initial.pages,1);for(let i=0;i<5;i++)await h.older(market,'1m');assert.equal(calls,1);await s.a.candles(market,'1m',time*1000-1);assert.equal(calls,1);}});
test('Kraken native Thursday weekly boundary is never rebucketed',async t=>{const s=setup(t,'1w'),thursday=Date.UTC(2026,7,27)/1000;s.a.request=async()=>({XXBTZUSD:[raw(thursday)],last:thursday});const rows=await s.a.candles(market,'1w');assert.equal(rows[0].time,thursday);assert.equal(new Date(rows[0].time*1000).getUTCDay(),4);});
test('Kraken exact ACK precedes LIVE; snapshot and heartbeat alone cannot claim freshness',async t=>{const s=setup(t);s.ws.open();assert.equal(s.ws.url,'wss://ws.kraken.com/v2');assert.deepEqual(s.ws.sent[0],{method:'subscribe',params:{channel:'ohlc',symbol:['BTC/USD'],interval:1,snapshot:true},req_id:1});s.ws.message({channel:'heartbeat'});assert.ok(!s.statuses.includes('LIVE'));s.ws.message(ack());s.ws.message(event('snapshot'));await flush();assert.equal(s.ws.krakenState.acknowledged,true);assert.equal(s.ws.krakenState.snapshots,1);assert.ok(!s.statuses.includes('LIVE'));s.ws.message(event());assert.equal(s.statuses.at(-1),'LIVE');assert.equal(s.values.at(-1).time,time);assert.equal(s.values.at(-1).provisional,true);assert.ok(s.ws.krakenState.lastMessage);assert.ok(s.ws.krakenState.lastHeartbeat);assert.ok(s.ws.krakenState.lastCandle);});
for(const bad of [{...ack(),success:false,error:'Already subscribed to one ohlc interval on this symbol'},{...ack(),req_id:2},ack(5),{...ack(),result:{...ack().result,symbol:'BTC/USDT'}}])test('Kraken NACK/mismatched ACK closes transport honestly '+JSON.stringify(bad),t=>{const s=setup(t);s.ws.open();s.ws.message(bad);assert.equal(s.ws.readyState,3);assert.equal(s.errors.length,1);assert.ok(!s.statuses.includes('LIVE'));});
test('Kraken REST/WS overlap replaces cumulative volume, does not duplicate or regress',async t=>{const s=setup(t);s.ws.open();s.ws.message(ack());s.ws.message(event('snapshot',1,time,10));s.ws.message(event('update',1,time,14));await flush();s.ws.message(event('update',1,time,14));s.ws.message(event('update',1,time,13));assert.equal(s.values.at(-1).volume,14);assert.ok(s.values.every(r=>r.volume===14));const combined=new Map(s.repairs[0].map(r=>[r.time,r]));s.values.forEach(r=>combined.set(r.time,r));assert.equal(combined.size,2);assert.equal(combined.get(time).volume,14);});
test('Kraken switch 1m → 5m → 1h → 1w → 1m replaces sockets and rejects stale callbacks',async t=>{const s=setup(t);let old=s.ws;old.open();for(const frame of ['5m','1h','1w','1m']){old.close();const count=s.values.length;old.message(event());assert.equal(s.values.length,count);const fresh=s.a.socket(market,frame,s.handlers);fresh.open();assert.equal(fresh.sent.length,1);assert.equal(fresh.sent[0].params.interval,chart.intervals[frame]);assert.equal(fresh.krakenState.acknowledged,false);old=fresh;}assert.equal(s.sockets.length,5);});
test('Kraken reconnect must reconcile REST before continuity, old callbacks cannot publish',async t=>{const s=setup(t);s.ws.open();s.ws.message(ack());await flush();s.ws.message(event());s.ws.close();let release;s.a.request=()=>new Promise(resolve=>{release=resolve;});const ws=s.a.socket(market,'1m',s.handlers);ws.open();ws.message(ack());ws.message(event());const count=s.values.length;assert.notEqual(s.statuses.at(-1),'LIVE');s.ws.message(event());assert.equal(s.values.length,count);await flush();release({XXBTZUSD:[raw()],last:time});await flush();assert.equal(ws.krakenState.reconciliations,1);assert.equal(s.statuses.at(-1),'LIVE');assert.deepEqual([0,1,2,9].map(n=>s.a.reconnectDelay(n)),[5000,10000,20000,60000]);});
test('Kraken malformed WS, wrong interval, and deprecated-only identity fail closed',async t=>{const s=setup(t);s.ws.open();s.ws.message(ack());await flush();const e=event();delete e.data[0].interval_begin;s.ws.message(e);assert.equal(s.errors.length,1);assert.equal(s.ws.readyState,3);});
test('Kraken old candle updates and heartbeats cannot mark a stale feed LIVE',async t=>{const s=setup(t);s.ws.open();s.ws.message(ack());await flush();s.ws.message(event('update',1,time-120));s.ws.message({channel:'heartbeat'});assert.equal(s.ws.krakenState.lastCandle,null);assert.ok(!s.statuses.includes('LIVE'));});
test('Kraken wrong live interval is rejected even after an exact ACK',async t=>{const s=setup(t);s.ws.open();s.ws.message(ack());await flush();s.ws.message(event('update',5));assert.equal(s.errors.length,1);assert.equal(s.values.length,0);});
test('Kraken delayed REST completion after socket replacement never reconciles',async t=>{const s=setup(t);let release;s.a.request=()=>new Promise(resolve=>{release=resolve;});s.ws.open();s.ws.message(ack());s.ws.close();release({XXBTZUSD:[raw()],last:time});await flush();assert.equal(s.repairs.length,0);assert.equal(s.values.length,0);});
test('Kraken USDT retains XBTUSDT for REST and uses BTC/USDT only for WS',async t=>{const s=setup(t),m={...market,id:'kraken:spot:XBTUSDT',symbol:'XBTUSDT',quoteAsset:'USDT'};s.a.mapping.byNative.set('XBTUSDT',{nativeSymbol:'XBTUSDT',wsSymbol:'BTC/USDT',baseAsset:'BTC',quoteAsset:'USDT'});let path;s.a.request=async p=>{path=p;return {XBTUSDT:[raw()],last:time};};await s.a.candles(m,'5m');assert.equal(path,'OHLC?pair=XBTUSDT&interval=5');const ws=s.a.socket(m,'5m',s.handlers);ws.open();assert.deepEqual(ws.sent[0].params.symbol,['BTC/USDT']);assert.equal(ws.krakenState.nativeSymbol,'XBTUSDT');});
test('Kraken finalizes the previous interval only through REST reconciliation after progression',async t=>{const s=setup(t);s.ws.open();s.ws.message(ack());await flush();s.ws.message(event());s.a.now=()=> (time+90)*1000;s.a.request=async()=>({XXBTZUSD:[raw(time,'13'),raw(time+60,'2')],last:time+60});s.ws.message(event('update',1,time+60,2));await flush();const repaired=s.repairs.at(-1);assert.equal(repaired.find(r=>r.time===time).provisional,false);assert.equal(repaired.at(-1).provisional,true);assert.equal(repaired.at(-1).volume,2);assert.equal(repaired.length,2);});
test('Kraken Watchlist canonical store add/remove/persistence/quote distinctions and exact Chart',()=>{const markets=['USD','USDT','USDC','EUR'].map((quoteAsset,i)=>({...market,quoteAsset,symbol:['XXBTZUSD','XBTUSDT','XBTUSDC','XXBTZEUR'][i],id:'kraken:spot:'+['XXBTZUSD','XBTUSDT','XBTUSDC','XXBTZEUR'][i]}));let saved=[];for(const m of markets)saved=watch.toggle(saved,m);const loaded=watch.migrate(JSON.parse(JSON.stringify([...saved,...saved])),{markets});assert.equal(loaded.length,4);assert.equal(loaded[0].symbol,'XXBTZUSD');for(const item of loaded){const m=watch.resolve(item,markets);assert.equal(context.fromMarket(m).marketId,item.marketId);}assert.equal(watch.toggle(loaded,markets[0]).length,3);assert.equal(watch.resolve({...loaded[0],key:'kraken:spot:UNKNOWN'},markets),null);});
test('Kraken UI uses shared filter, capability presentation, and unchanged alert/radar boundaries',()=>{const app=fs.readFileSync(require.resolve('../app.js'),'utf8'),html=fs.readFileSync(require.resolve('../index.html'),'utf8'),core=require('../js/alerts/alert-core.js');assert.match(app,/ZychExchangeAdapterV2\.registry\.filter\(adapter=>capabilityAdmitted\(adapter\.marketTypes\.spot\.capabilities\.watchlist\)\)/);assert.equal(require('../js/exchanges/exchange-adapter-v2').get('kraken').capabilities.watchlist.state,'SUPPORTED');assert.match(app,/entries\.map\(watchTileMarkup\)/);assert.match(app,/entries\.map\(watchRowMarkup\)/);assert.match(app,/setConnection\('UNAVAILABLE'\)/);assert.match(app,/capabilities\.historyLimit,'end'/);assert.equal(core.SUPPORTED_EXCHANGES.includes('kraken'),true);assert.doesNotMatch(html.match(/id="radar-exchange-filter"[\s\S]*?<\/select>/)[0],/kraken|coinbase/);});
