'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const k=require('../js/exchanges/kraken-public.js'),{KrakenBrowserAdapter}=require('../js/exchanges/kraken-browser.js');
const search=require('../js/services/instrument-search.js'),data=require('../js/services/markets-data.js'),workspace=require('../js/services/exchange-workspace.js'),context=require('../js/services/market-context.js'),core=require('../js/alerts/alert-core.js');
const at=Date.parse('2026-09-02T12:00:00Z');
function fixture(){
  const assets={},modernAssets={},legacy={},modern={};
  for(const [raw,key,altname]of [['XXBT','BTC','XBT'],['XETH','ETH','ETH'],['XXDG','DOGE','XDG'],['ZUSD','USD','USD'],['ZEUR','EUR','EUR'],['USDT','USDT','USDT'],['USDC','USDC','USDC'],['EURC','EURC','EURC'],['XZED','XZED','XZED']]){assets[raw]={aclass:'currency',status:'enabled',altname};modernAssets[key]={...assets[raw]};}
  for(const [native,base,quote]of [['XXBTZUSD','XXBT','ZUSD'],['XBTUSDT','XXBT','USDT'],['XETHZUSD','XETH','ZUSD'],['ETHUSDT','XETH','USDT'],['XXDGZUSD','XXDG','ZUSD'],['XXBTZEUR','XXBT','ZEUR'],['XBTUSDC','XXBT','USDC'],['EURCUSD','EURC','ZUSD'],['XZEDUSD','XZED','ZUSD']]){
    const b=Object.keys(modernAssets).find(key=>modernAssets[key].altname===assets[base].altname),q=Object.keys(modernAssets).find(key=>modernAssets[key].altname===assets[quote].altname),row={altname:assets[base].altname+assets[quote].altname,wsname:assets[base].altname+'/'+assets[quote].altname,base,quote,aclass_base:'currency',aclass_quote:'currency',execution_venue:'international',status:'online',pair_decimals:2,lot_decimals:8,cost_decimals:5,ordermin:'0.0001',costmin:'0.5',tick_size:'0.01',leverage_buy:[2,3]};legacy[native]=row;modern[b+'/'+q]={...row,base:b,quote:q};
  }
  return{legacy,modern,assets,modernAssets};
}
const mapping=f=>k.registry(f.legacy,f.modern,f.assets,f.modernAssets);
const rawRest=()=>({c:['100','1'],h:['999','110'],l:['1','90'],v:['2','50'],p:['3','99'],o:'1'});
const rawWs=(extra={})=>({symbol:'BTC/USD',last:101,change_pct:-2.42,change:-2.5,high:111,low:91,volume:51,vwap:100,timestamp:new Date(at).toISOString(),...extra});
const row=()=>mapping(fixture()).byNative.get('XXBTZUSD');
test('Kraken canonical native identities and metadata-derived bidirectional WS registry',()=>{const m=mapping(fixture());for(const[native,ws]of [['XXBTZUSD','BTC/USD'],['XBTUSDT','BTC/USDT'],['XETHZUSD','ETH/USD'],['ETHUSDT','ETH/USDT'],['XXDGZUSD','DOGE/USD']]){assert.equal(m.byNative.get(native).wsSymbol,ws);assert.equal(m.byWs.get(ws).nativeSymbol,native);assert.equal(k.instrument(m.byNative.get(native)).id,'kraken:spot:'+native);}assert.equal(m.byNative.get('XZEDUSD').baseAsset,'XZED');assert.ok(m.byNative.get('XXBTZUSD').metadata);});
for(const[title,mutate,reason]of [
  ['cancel_only',f=>f.legacy.XXBTZUSD.status='cancel_only','NOT_ONLINE'],
  ['post_only',f=>f.legacy.XXBTZUSD.status='post_only','NOT_ONLINE'],
  ['unknown status',f=>f.legacy.XXBTZUSD.status='future','NOT_ONLINE'],
  ['execution venue',f=>f.legacy.XXBTZUSD.execution_venue='us','UNSUPPORTED_VENUE'],
  ['tokenized class',f=>f.legacy.XXBTZUSD.aclass_base='tokenized_asset','NOT_CURRENCY_SPOT'],
  ['missing mapping',f=>delete f.modern['BTC/USD'],'AMBIGUOUS_OR_MISSING_MAPPING'],
  ['ambiguous modern mapping',f=>f.modern.DUPLICATE={...f.modern['BTC/USD']},'AMBIGUOUS_OR_MISSING_MAPPING'],
  ['ambiguous native mapping',f=>f.legacy.DUPLICATE={...f.legacy.XXBTZUSD},'AMBIGUOUS_OR_MISSING_MAPPING'],
  ['inconsistent assets',f=>f.modern['BTC/USD'].base='XBT','INVALID_ASSET_MAPPING'],
  ['missing asset metadata',f=>delete f.assets.XXBT,'INVALID_ASSET_MAPPING'],
  ['invalid minimum',f=>f.legacy.XXBTZUSD.ordermin='NaN','INVALID_PRECISION_OR_MINIMUM'],
  ['invalid precision',f=>f.legacy.XXBTZUSD.lot_decimals=-1,'INVALID_PRECISION_OR_MINIMUM']
])test('Kraken quarantines '+title,()=>{const f=fixture();mutate(f);const m=mapping(f);assert.equal(m.byNative.has('XXBTZUSD'),false);assert.equal(m.excluded.find(x=>x.nativeSymbol==='XXBTZUSD').reason,reason);});
test('Kraken excludes dark/nonstandard symbols; margin metadata does not exclude currency Spot',()=>{const f=fixture();f.legacy['XXBTZUSD.d']={...f.legacy.XXBTZUSD,altname:'XBTUSD.d'};const m=mapping(f);assert.ok(m.byNative.has('XXBTZUSD'));assert.equal(m.excluded[0].reason,'NONSTANDARD_SYMBOL');});
test('Kraken REST uses the rolling array slots, never midnight open or fabricated quote turnover',()=>{const s=k.snapshot(row(),k.restTicker(rawRest(),at),null,at);assert.equal(s.price,100);assert.equal(s.high24h,110);assert.equal(s.low24h,90);assert.equal(s.baseVolume24h,50);assert.equal(s.vwap24h,99);assert.equal(s.change24h,null);assert.equal(s.change,null);assert.equal(s.quoteVolume24h,null);assert.equal(s.volume,null);assert.equal(s.snapshotTimestamp,null);assert.equal(s.provenance.fields.price.sourceTimestamp,null);assert.equal(s.provenance.fields.price.receivedAt,at);});
test('Kraken WS percentages are percentage points and preserve exchange time separately',()=>{const w=k.wsTicker(rawWs(),at+100),s=k.snapshot(row(),null,w,at+100);assert.equal(s.change24h,-2.42);assert.equal(s.changePercent,-2.42);assert.equal(s.sourceTimestamp,at);assert.equal(s.provenance.fields.change24h.source,'kraken-ws-v2-ticker');assert.equal(s.provenance.fields.change24h.receivedAt,at+100);assert.equal(s.provenance.fields.change24h.sourceTimestamp,at);assert.equal(s.quoteVolume24h,null);});
test('Kraken newer partial REST cannot erase verified WS change or fabricate source time',()=>{const s=k.snapshot(row(),k.restTicker({c:['102']},at+200),k.wsTicker(rawWs(),at+100),at+300);assert.equal(s.price,102);assert.equal(s.high24h,111);assert.equal(s.change24h,-2.42);assert.equal(s.provenance.fields.price.source,'kraken-rest-ticker');assert.equal(s.provenance.fields.price.sourceTimestamp,null);assert.equal(s.provenance.fields.change24h.sourceTimestamp,at);});
test('Kraken missing, invalid, stale and zero values remain distinct',()=>{for(const x of [null,undefined,'',false,true,'NaN','Infinity','0x10'])assert.equal(k.numeric(x),null);assert.equal(k.numeric('0'),0);const s=k.snapshot(row(),k.restTicker({c:['0'],h:['0','0'],l:['0','0'],v:['0','0']},at),k.wsTicker(rawWs({change_pct:0}),at),at);assert.equal(s.price,0);assert.equal(s.change24h,0);assert.equal(s.quoteVolume24h,null);assert.equal(k.snapshot(row(),null,k.wsTicker(rawWs(),at),at+180001).change24h,null);assert.equal(k.wsTicker(rawWs({timestamp:'bad'}),at),null);assert.equal(k.wsTicker(rawWs({timestamp:new Date(at+10000).toISOString()}),at),null);});
test('Kraken public errors and malformed envelopes fail closed',()=>{for(const v of [{error:['EGeneral:bad'],result:{}},{result:{}},{error:[],result:[]},null])assert.throws(()=>k.unwrap(v));});
test('Kraken aliases extend existing search, preserve quote distinctions and prioritize exact aliases',()=>{const markets=[...mapping(fixture()).byNative.values()].map(k.instrument);for(const q of ['BTC','XBT','BTCUSD','BTC-USD','BTC/USD','XBTUSD','XXBTZUSD'])assert.ok(search.search(markets,q).some(x=>x.id==='kraken:spot:XXBTZUSD'),q);for(const q of ['ETH','USD','USDT','USDC','EUR'])assert.ok(search.search(markets,q).length,q);assert.equal(search.search(markets,'XBTUSD')[0].id,'kraken:spot:XXBTZUSD');assert.equal(search.search(markets,'EUR')[0].quoteAsset,'EUR');assert.ok(search.search(markets,'XDG').some(x=>x.baseAsset==='DOGE'));assert.ok(search.search(markets,'USDT').every(x=>x.quoteAsset==='USDT'));assert.equal(search.search(markets,'XBTUSD')[0].nativeSymbol,'XXBTZUSD');});
test('Kraken Markets supports rows, breadth and rankings without exact-volume metrics',()=>{const rows=[...mapping(fixture()).byNative.values()].slice(0,3).map((r,i)=>data.item(k.instrument(r),k.snapshot(r,k.restTicker(rawRest(),at),k.wsTicker(rawWs({change_pct:[2,-1,0][i]}),at),at)));assert.equal(rows[0].baseVolume24h,50);assert.equal(rows[0].searchAliases.includes('XBT'),true);assert.deepEqual(data.breadth(rows),{rising:1,falling:1,flat:1,total:3,risingPct:1/3*100,fallingPct:1/3*100});assert.equal(data.rank(rows,'change24h','desc')[0].change24h,2);assert.equal(data.rank(rows,'change24h','asc')[0].change24h,-1);assert.deepEqual(data.rank(rows,'quoteVolume24h'),[]);});
test('Kraken exact quote switches fail closed without changing other exchange fallback',()=>{const markets=[...mapping(fixture()).byNative.values()].map(k.instrument);const other={...markets[1],exchange:'binance',id:'binance:spot:BTCUSDT'};assert.equal(workspace.marketForAsset(markets,'BTC','kraken','CHF'),null);assert.equal(workspace.equivalentMarket([other],markets[0],'binance'),null);assert.equal(workspace.marketForAsset([other],'BTC','binance','CHF'),other);assert.equal(context.fromMarket(markets[0]).marketId,markets[0].id);assert.equal(context.create({...context.fromMarket(markets[0]),symbol:'BTC/USD'}),null);});
class FakeSocket extends EventTarget{
  constructor(f,{badAck=false,silent=false,unverified=false}={}){super();this.f=f;this.badAck=badAck;this.silent=silent;this.unverified=unverified;this.sent=[];this.active=new Set();this.maxActive=0;queueMicrotask(()=>this.dispatchEvent(new Event('open')));}
  emit(p){this.dispatchEvent(new MessageEvent('message',{data:JSON.stringify(p)}));}
  send(text){const p=JSON.parse(text);this.sent.push(p);queueMicrotask(()=>{if(this.closed||this.silent)return;
    if(p.params.channel==='instrument'){this.emit({method:'subscribe',req_id:p.req_id,success:true,result:{channel:'instrument'}});this.emit({channel:'instrument',type:'snapshot',data:{pairs:[...mapping(this.f).byNative.values()].map(r=>({symbol:r.wsSymbol,base:r.baseAsset,quote:r.quoteAsset,status:this.unverified?'cancel_only':'online'}))}});return;}
    for(const symbol of p.params.symbol){if(p.method==='subscribe'){this.active.add(symbol);this.maxActive=Math.max(this.maxActive,this.active.size);this.emit({method:'subscribe',req_id:p.req_id,success:true,result:{channel:'ticker',symbol,snapshot:!this.badAck,event_trigger:'trades'}});this.emit({channel:'ticker',type:'snapshot',data:[rawWs({symbol})]});}else{this.active.delete(symbol);this.emit({method:'unsubscribe',req_id:p.req_id,success:true,result:{channel:'ticker',symbol}});}}
  });}
  close(){this.closed=true;this.active.clear();this.dispatchEvent(new Event('close'));}
}
function adapter(options={}){const f=fixture(),calls=[],sockets=[];const a=new KrakenBrowserAdapter({now:()=>at+1000,requestSpacingMs:0,batchDelayMs:0,batchSize:2,ackTimeoutMs:40,collectionTimeoutMs:400,fetchImpl:async(url,options)=>{calls.push({url,options});const modern=url.includes('assetVersion=1'),result=url.includes('/AssetPairs')?(modern?f.modern:f.legacy):url.includes('/Assets')?(modern?f.modernAssets:f.assets):Object.fromEntries(Object.keys(f.legacy).map(key=>[key,rawRest()]));return{ok:true,text:async()=>JSON.stringify({error:[],result})};},socketFactory:()=>{const socket=new FakeSocket(f,options);sockets.push(socket);return socket;}});return{a,f,calls,sockets};}
test('Kraken adapter coalesces REST/WS work, validates instruments and reuses a bounded cache',async()=>{const{a,calls,sockets}=adapter();const [markets,again]=await Promise.all([a.discover(),a.discover()]);assert.deepEqual(markets,again);assert.equal(calls.length,4);const [one,two]=await Promise.all([a.allSnapshots(),a.allSnapshots()]);assert.deepEqual(one,two);assert.equal(sockets.length,1);assert.ok(sockets[0].maxActive<=2);assert.ok(sockets[0].closed);assert.equal(a.diagnostics().verifiedSnapshots,markets.length);assert.equal(a.diagnostics().connections,0);assert.equal(one[0].change24h,-2.42);assert.equal((await a.allSnapshots()).length,markets.length);assert.equal(sockets.length,1);assert.equal(calls.length,5);for(const c of calls){assert.equal(new URL(c.url).origin,'https://api.kraken.com');assert.equal(c.options.headers,undefined);assert.equal(c.options.credentials,'omit');}a.dispose();});
test('Kraken targeted snapshot lookup requires canonical native identity',async()=>{const{a}=adapter();assert.deepEqual(await a.snapshots([{id:'kraken:spot:BTC/USD',exchange:'kraken',marketType:'spot',symbol:'BTC/USD'}]),{});const rows=await a.discover(),result=await a.snapshots([rows[0]]);assert.deepEqual(Object.keys(result),[rows[0].id]);a.dispose();});
test('Kraken WS rejects incorrect ACKs and never manufactures change from REST',async()=>{const{a}=adapter({badAck:true});const rows=await a.allSnapshots();assert.ok(rows.every(row=>row.change24h===null&&row.price===100));assert.ok(a.diagnostics().rejected.length);a.dispose();});
test('Kraken WS instrument mismatch quarantines ticker requests',async()=>{const{a,sockets}=adapter({unverified:true});const rows=await a.allSnapshots();assert.ok(rows.every(row=>row.change24h===null));assert.equal(sockets[0].sent.filter(p=>p.params.channel==='ticker').length,0);assert.ok(a.diagnostics().rejected.every(x=>x.reason==='WS_INSTRUMENT_UNVERIFIED'));a.dispose();});
test('Kraken WS timeout retains partial REST metrics and closes the collector',async()=>{const{a,sockets}=adapter({silent:true});const rows=await a.allSnapshots();assert.equal(rows[0].price,100);assert.equal(rows[0].change24h,null);assert.match(a.diagnostics().lastError,/timeout/);assert.ok(sockets[0].closed);a.dispose();});
test('Kraken caller cancellation does not cancel shared catalog work',async()=>{const{a}=adapter();const c=new AbortController();const rejected=a.discover(c.signal);c.abort();await assert.rejects(rejected,{name:'AbortError'});assert.ok((await a.discover()).length);a.dispose();});
test('Kraken cached reads expire without a refresh, including while another exchange is active',async()=>{const{a}=adapter();await a.allSnapshots();assert.equal(a.cachedSnapshot('XXBTZUSD').change24h,-2.42);a.now=()=>at+190000;const stale=a.cachedSnapshot('XXBTZUSD');assert.equal(stale.change24h,null);assert.equal(stale.price,null);assert.equal(stale.high24h,null);assert.equal(stale.baseVolume24h,null);assert.equal(a.cachedSnapshot('BTC/USD'),null);a.dispose();});
test('Kraken disposal closes an in-flight collector and leaves no active connection',async()=>{const{a,sockets}=adapter({silent:true});await a.discover();const pending=a.collect(a.mapping);assert.equal(a.diagnostics().connections,1);a.dispose();await pending;assert.equal(a.diagnostics().connections,0);assert.ok(sockets[0].closed);});
test('Kraken REST failure does not erase successful verified WS fields',async()=>{const{a}=adapter();await a.discover();a.fetchImpl=async()=>{throw new Error('REST unavailable')};const rows=await a.allSnapshots();assert.ok(rows.every(row=>row.price===101&&row.change24h===-2.42&&row.quoteVolume24h===null));assert.equal(a.diagnostics().lastRestError,'REST unavailable');a.dispose();});
test('Kraken public HTTP error rejects discovery and can be retried',async()=>{const{a}=adapter();const original=a.fetchImpl;a.fetchImpl=async()=>({ok:false,status:429});await assert.rejects(a.discover(),/429/);a.fetchImpl=original;assert.ok((await a.discover()).length);a.dispose();});
test('Kraken Part B enables Chart/Watchlist while Radar remains excluded',async()=>{const{a}=adapter();await assert.rejects(a.candles(),/Unsupported Kraken interval/);assert.throws(()=>a.socket(),/Unsupported Kraken interval/);assert.equal(core.SUPPORTED_EXCHANGES.includes('kraken'),true);assert.equal(core.SUPPORTED_EXCHANGES.length,6);assert.equal(a.capabilities.chart,true);assert.equal(a.capabilities.watchlist,true);assert.equal(a.capabilities.radar,false);const html=fs.readFileSync(require.resolve('../index.html'),'utf8'),app=fs.readFileSync(require.resolve('../app.js'),'utf8');assert.equal((html.match(/data-active-exchange-option=/g)||[]).length,0);assert.match(app,/ZychExchangeAdapterV2\.manualExchangeIds\.map/);assert.equal((html.match(/id="active-exchange-selector"/g)||[]).length,1);assert.doesNotMatch(html.match(/id="radar-exchange-filter"[\s\S]*?<\/select>/)[0],/coinbase|kraken/);assert.match(app,/capabilities\?\.chart===false/);assert.match(app,/Exact quote volume, volume ranking and heatmap sizing are unavailable/);assert.match(app,/item\.change24h===null\?'':/);a.dispose();});
