const test=require('node:test');
const assert=require('node:assert/strict');

const node=()=>({children:[],listeners:{},className:'',textContent:'',setAttribute(){},addEventListener(type,handler){this.listeners[type]=handler},append(...items){this.children.push(...items)},remove(){this.removed=true}});

for(const [expected,sound] of [['SCHEDULED',{play:async()=>true}],['DISABLED',{enabled:false,play:async()=>false}],['BLOCKED',{play:async()=>false,state:()=>({enabled:true,contextState:'suspended'})}],['FAILED',{play(){throw Error('audio failed');}}]])test(`local delivery observation reports ${expected}, never heard`,async()=>{
  const original=global.document;global.document={createElement:node};
  try { const {NotificationCenter}=require('../js/notifications/notification-center');const center=new NotificationCenter({region:{append(){}},sound,describe:()=>'',formatTime:()=>'',onOpen(){},setTimer:()=>0});const event={id:`outcome-${expected}`,asset:'BTC',exchange:'binance',triggeredAt:1};center.notify(event);center.notify(event);await new Promise(resolve=>setImmediate(resolve));const facts=center.diagnostics();assert.equal(facts.latest[0].sound,expected);assert.equal(facts.latest[0].inApp,'OBSERVED');assert.equal(facts.latest[0].toast,'OBSERVED');assert.equal(facts.duplicatesSuppressed,1);assert.equal(event.sound,undefined); }
  finally{global.document=original;}
});

test('one real trigger notification dispatches the configured sound exactly once',async()=>{
  const originalDocument=global.document;global.document={createElement:node};
  try{
    const {NotificationCenter}=require('../js/notifications/notification-center.js');let plays=0;
    const center=new NotificationCenter({region:{append(){}},sound:{play:async()=>{plays++;return true}},describe:()=> 'Price above',formatTime:()=> '12:00',onOpen(){},setTimer:()=>0});
    center.notify({asset:'BTC',exchange:'bybit',timeframe:'1m',triggeredAt:1});await Promise.resolve();assert.equal(plays,1);
  }finally{global.document=originalDocument}
});

test('sound rejection is isolated from trigger notification rendering',async()=>{
  const originalDocument=global.document,originalWarn=console.warn;global.document={createElement:node};let warnings=0;console.warn=()=>warnings++;
  try{const {NotificationCenter}=require('../js/notifications/notification-center.js');assert.doesNotThrow(()=>new NotificationCenter({region:{append(){}},sound:{play:()=>Promise.reject(new Error('blocked'))},describe:()=>'',formatTime:()=>'',onOpen(){},setTimer:()=>0}).notify({asset:'BTC',exchange:'bybit',triggeredAt:1}));await new Promise(resolve=>setImmediate(resolve));assert.equal(warnings,1)}
  finally{global.document=originalDocument;console.warn=originalWarn}
});

test('the same TriggerEvent id cannot replay a toast or sound',async()=>{const originalDocument=global.document;global.document={createElement:node};try{const {NotificationCenter}=require('../js/notifications/notification-center.js');let plays=0,toasts=0;const center=new NotificationCenter({region:{append(){toasts++}},sound:{play:()=>{plays++;return true}},describe:()=>'',formatTime:()=>'',onOpen(){},setTimer:()=>0}),event={id:'stable-trigger',asset:'BTC',exchange:'binance',triggeredAt:1};assert.ok(center.notify(event));assert.equal(center.notify(event),null);await Promise.resolve();assert.equal(toasts,1);assert.equal(plays,1)}finally{global.document=originalDocument}});

test('toast auto-dismisses after eight seconds without removing trigger history',()=>{const originalDocument=global.document;global.document={createElement:node};try{const {NotificationCenter}=require('../js/notifications/notification-center.js'),timers=[],history=[{id:'auto'}],center=new NotificationCenter({region:{append(){}},sound:{play(){}},describe:()=>'',formatTime:()=>'',onOpen(){},setTimer:(callback,delay)=>{timers.push({callback,delay});return 1},clearTimer(){}}),toast=center.notify({...history[0],asset:'BTC',exchange:'binance',triggeredAt:1});assert.equal(timers[0].delay,8000);assert.equal(toast.removed,undefined);timers[0].callback();assert.equal(toast.removed,true);assert.deepEqual(history.map(event=>event.id),['auto'])}finally{global.document=originalDocument}});

test('native-style browser timers keep their required global receiver',()=>{const originalDocument=global.document,originalSetTimeout=global.setTimeout,originalClearTimeout=global.clearTimeout,timers=[];global.document={createElement:node};global.setTimeout=function(callback,delay){assert.equal(this,global);timers.push({callback,delay});return 17};global.clearTimeout=function(timer){assert.equal(this,global);assert.equal(timer,17)};try{const {NotificationCenter}=require('../js/notifications/notification-center.js'),center=new NotificationCenter({region:{append(){}},sound:{play(){}},describe:()=>'',formatTime:()=>'',onOpen(){}}),toast=center.notify({id:'browser-timer',asset:'BTC',exchange:'binance',triggeredAt:1});assert.equal(timers[0].delay,8000);timers[0].callback();assert.equal(toast.removed,true)}finally{global.document=originalDocument;global.setTimeout=originalSetTimeout;global.clearTimeout=originalClearTimeout}});

test('manual close dismisses immediately and does not alter history',()=>{const originalDocument=global.document;global.document={createElement:node};try{const {NotificationCenter}=require('../js/notifications/notification-center.js'),history=[{id:'manual'}],center=new NotificationCenter({region:{append(){}},sound:{play(){}},describe:()=>'',formatTime:()=>'',onOpen(){},setTimer:()=>1,clearTimer(){}}),toast=center.notify({...history[0],asset:'BTC',exchange:'binance',triggeredAt:1}),close=toast.children[3];let stopped=false;close.listeners.click({stopPropagation(){stopped=true}});assert.equal(stopped,true);assert.equal(toast.removed,true);assert.deepEqual(history.map(event=>event.id),['manual'])}finally{global.document=originalDocument}});

test('two unique TriggerEvents have independent toast timers',async()=>{const originalDocument=global.document;global.document={createElement:node};try{const {NotificationCenter}=require('../js/notifications/notification-center.js'),timers=[],toasts=[];let plays=0;const center=new NotificationCenter({region:{append(toast){toasts.push(toast)}},sound:{play(){plays++}},describe:()=>'',formatTime:()=>'',onOpen(){},setTimer:callback=>{timers.push(callback);return timers.length},clearTimer(){}});center.notify({id:'one',asset:'BTC',exchange:'binance',triggeredAt:1});center.notify({id:'two',asset:'ETH',exchange:'binance',triggeredAt:2});assert.equal(toasts.length,2);assert.equal(timers.length,2);timers[0]();assert.equal(toasts[0].removed,true);assert.equal(toasts[1].removed,undefined);timers[1]();assert.equal(toasts[1].removed,true);await Promise.resolve();assert.equal(plays,2)}finally{global.document=originalDocument}});

test('three observations and delivery-status updates for one TriggerEvent stay at one toast and sound',async()=>{const originalDocument=global.document;global.document={createElement:node};try{const {NotificationCenter}=require('../js/notifications/notification-center.js');let plays=0,toasts=0;const center=new NotificationCenter({region:{append(){toasts++}},sound:{play(){plays++;return true}},describe:()=>'',formatTime:()=>'',onOpen(){},setTimer:()=>0}),event={id:'triple-observation-trigger',asset:'BTC',exchange:'binance',triggeredAt:1};center.notify(event);center.notify({...event,push:'PENDING'});center.notify({...event,push:'FAILED',sound:'SCHEDULED'});await Promise.resolve();assert.equal(toasts,1);assert.equal(plays,1);assert.equal(center.diagnostics().duplicatesSuppressed,2)}finally{global.document=originalDocument}});

test('Alert Hub re-render or notification-center recreation cannot replay a session-delivered TriggerEvent',async()=>{const originalDocument=global.document;global.document={createElement:node};try{const {NotificationCenter}=require('../js/notifications/notification-center.js');let plays=0,toasts=0;const options={region:{append(){toasts++}},sound:{play(){plays++;return true}},describe:()=>'',formatTime:()=>'',onOpen(){},setTimer:()=>0},event={id:'hub-rerender-trigger',asset:'BTC',exchange:'kraken',triggeredAt:1};new NotificationCenter(options).notify(event);assert.equal(new NotificationCenter(options).notify({...event}),null);await Promise.resolve();assert.equal(toasts,1);assert.equal(plays,1)}finally{global.document=originalDocument}});

test('recurring alerts with new TriggerEvent ids each deliver once',async()=>{const originalDocument=global.document;global.document={createElement:node};try{const {NotificationCenter}=require('../js/notifications/notification-center.js');let plays=0,toasts=0;const center=new NotificationCenter({region:{append(){toasts++}},sound:{play(){plays++;return true}},describe:()=>'',formatTime:()=>'',onOpen(){},setTimer:()=>0}),base={alertId:'recurring-alert',asset:'ETH',exchange:'bingx'};center.notify({...base,id:'recurring-trigger-1',triggeredAt:1});center.notify({...base,id:'recurring-trigger-2',triggeredAt:2});await Promise.resolve();assert.equal(toasts,2);assert.equal(plays,2)}finally{global.document=originalDocument}});

test('every production sound generator has exactly one audible tone onset per play',()=>{const originalWindow=global.window,originalDocument=global.document,originalStorage=global.localStorage;global.window={};global.document={addEventListener(){},removeEventListener(){}};global.localStorage={getItem(){return null},setItem(){}};try{delete require.cache[require.resolve('../js/notifications/alert-sound.js')];require('../js/notifications/alert-sound.js');const {AlertSoundManager,SOUND_OPTIONS}=global.window.ZychNotifications,manager=new AlertSoundManager(),gain=()=>({gain:{setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){}});for(const {id} of SOUND_OPTIONS){const starts=[],context={createGain:gain,createOscillator(){return{frequency:{setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){},start(at){starts.push(at)},stop(){}}}},now=10;manager.render(id,context,{},now);const onsetGroups=[...new Set(starts.map(value=>Math.round((value-now)*1000)))];assert.equal(onsetGroups.length,1,`${id} scheduled ${onsetGroups.length} audible onsets`);assert.ok(onsetGroups[0]<=20,`${id} onset was unexpectedly delayed`)}}finally{global.window=originalWindow;global.document=originalDocument;global.localStorage=originalStorage;delete require.cache[require.resolve('../js/notifications/alert-sound.js')]}});

test('background or unfocused clients update silently without toast or Web Audio',()=>{const originalDocument=global.document;global.document={createElement:node};try{const {NotificationCenter}=require('../js/notifications/notification-center.js');let plays=0,toasts=0;const center=new NotificationCenter({region:{append(){toasts++}},sound:{play(){plays++}},describe:()=>'',formatTime:()=>'',onOpen(){},canDeliver:()=>false});assert.equal(center.notify({id:'background-trigger',asset:'BTC',triggeredAt:1}),null);assert.equal(toasts,0);assert.equal(plays,0)}finally{global.document=originalDocument}});

test('only one foreground authority delivers across multiple client observations',async()=>{const originalDocument=global.document;global.document={createElement:node};try{const {NotificationCenter}=require('../js/notifications/notification-center.js');let plays=0,toasts=0;const options={region:{append(){toasts++}},sound:{play(){plays++;return true}},describe:()=>'',formatTime:()=>'',onOpen(){}},event={id:'multi-tab-trigger',asset:'BTC',triggeredAt:1};new NotificationCenter({...options,canDeliver:()=>true}).notify(event);new NotificationCenter({...options,canDeliver:()=>false}).notify(event);await Promise.resolve();assert.equal(toasts,1);assert.equal(plays,1)}finally{global.document=originalDocument}});

test('bottom-right popup rendering is visual-only when requested and cannot play audio',async()=>{const originalDocument=global.document;global.document={createElement:node};try{const {NotificationCenter}=require('../js/notifications/notification-center.js');let plays=0,toasts=0;const center=new NotificationCenter({region:{append(){toasts++}},sound:{play(){plays++;return true}},describe:()=>'',formatTime:()=>'',onOpen(){}});assert.ok(center.notify({id:'visual-only-popup',asset:'BTC',triggeredAt:1},{playSound:false}));await Promise.resolve();assert.equal(toasts,1);assert.equal(plays,0)}finally{global.document=originalDocument}});

test('browser delivery keeps one sound outside the visual popup renderer',()=>{const source=require('node:fs').readFileSync(require.resolve('../js/notifications/browser-notifier.js'),'utf8');assert.match(source,/notify\(triggerEvent,\{playSound:false\}\)/);assert.match(source,/if\(toast\)this\.notificationCenter\.play\(triggerEvent\)/)});
