'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),path=require('node:path');
const {loadConfig}=require('../server/config.js');
const {validateConfig,validateEnvironment}=require('../server/config-validation.js');
const {ApplicationLifecycle}=require('../server/lifecycle.js');
const {HealthService}=require('../server/health-service.js');
const {ProcessMetrics}=require('../server/process-metrics.js');
const {createLogger}=require('../server/logger.js');
const {createHttpServer,createBingxPublicProxy,staticFile}=require('../server/http-server.js');
const {CandleHistoryAdapter}=require('../server/radar/candle-history-adapters.js');
const {MarketStateStore}=require('../server/radar/market-state-store.js');
const {RecoveryCoordinator}=require('../server/radar/recovery-coordinator.js');
const {DetectorRegistry}=require('../server/radar/detector-registry.js');
const {IngestionSupervisor}=require('../server/radar/ingestion-supervisor.js');
const {PriceMomentumDetector}=require('../server/radar/detectors/price-momentum.js');
const {VolumeAnomalyDetector}=require('../server/radar/detectors/volume-anomaly.js');
const {createServerApp}=require('../server/app.js');

const root=path.resolve(__dirname,'..'),base=1700000000000,silent={debug(){},info(){},warn(){},error(){}};
const market=(exchange='binance')=>({marketId:`${exchange}:spot:${exchange==='okx'?'BTC-USDT':'BTCUSDT'}`,exchange,marketType:'spot',symbol:exchange==='okx'?'BTC-USDT':'BTCUSDT',baseAsset:'BTC',quoteAsset:'USDT'});
const bar=(time,extra={})=>({marketId:'binance:spot:BTCUSDT',exchange:'binance',marketType:'spot',symbol:'BTCUSDT',timeframe:'1m',openTime:time,closeTime:time+59999,open:100,high:101,low:99,close:100,volume:1,quoteVolume:100,isClosed:true,sourceTimestamp:time+59999,receivedAt:time+60000,...extra});

test('static allowlist preserves frontend and blocks private and traversal paths',()=>{for(const value of ['/','/index.html','/style.css','/app.js','/sw.js','/js/alerts/alert-core.js'])assert.ok(staticFile(root,value));for(const value of ['/.env','/.git/config','/server/index.js','/server-data/alerts-state.json','/node_modules/x.js','/package.json','/pnpm-lock.yaml','/tests/server.test.js','/deploy/Caddyfile','/../server/index.js','/%2e%2e/server/index.js','/js\\..\\server.js','/%00.env'])assert.equal(staticFile(root,value),null)});

test('strict configuration accepts defaults and rejects invalid critical values',()=>{assert.equal(validateConfig(loadConfig({})).port,4178);for(const mutate of [c=>c.port=0,c=>c.port=NaN,c=>c.radarRecoveryConcurrency=Infinity,c=>c.universePolicy={...c.universePolicy,targetUniverseSize:201},c=>c.binanceRestBase='not-a-url']){const value=structuredClone(loadConfig({}));mutate(value);assert.throws(()=>validateConfig(value),error=>error.code==='INVALID_CONFIG')}});
test('invalid raw production numeric environment cannot silently fall back',()=>{for(const env of [{ZYCH_PORT:'bad'},{ZYCH_PORT:'70000'},{ZYCH_PORT:'4178.5'},{RADAR_RECOVERY_CONCURRENCY:'Infinity'},{RADAR_RECOVERY_CONCURRENCY:'1.5'},{RADAR_TARGET_SIZE:'-1'}])assert.throws(()=>validateEnvironment(env),error=>error.code==='INVALID_CONFIG')});
test('semantic validation rejects nonsensical universe, dedup and score relationships',()=>{for(const mutate of [c=>c.universePolicy={...c.universePolicy,allowedQuotes:[]},c=>c.universePolicy={...c.universePolicy,liquidityTiers:{A:1,B:2,C:3}},c=>c.radarQualification={...c.radarQualification,momentumZDelta:-1},c=>c.radarQualification={...c.radarQualification,cooldowns:{...c.radarQualification.cooldowns,'1m':Infinity}},c=>c.radarScore={...c.radarScore,caps:{...c.radarScore.caps,momentum:100}}]){const value=structuredClone(loadConfig({}));mutate(value);assert.throws(()=>validateConfig(value),error=>error.code==='INVALID_CONFIG')}});

test('optional push credentials remain optional',()=>{const value=validateConfig(loadConfig({VAPID_PUBLIC_KEY:'',VAPID_PRIVATE_KEY:''}));assert.equal(value.vapidPrivateKey,'')});

test('lifecycle and readiness distinguish warm-up, partial operation, outage and stopping',()=>{const lifecycle=new ApplicationLifecycle({now:()=>1}),state={totalStateEntries:10,COMPLETE:0},coverage={selectedMarketCount:3,healthyExchanges:['binance'],expectedExchanges:['binance','bybit']},radar={running:true,selected:new Map([['x',{}]]),stats:{lastHealthyProcessingTimestamp:null},store:{diagnostics:()=>state}},health=new HealthService({lifecycle,universe:{health:()=>({coverage})},radar,eventPipeline:{stopped:false},now:()=>1});lifecycle.transition('WARMING_UP',['RADAR_WARMING_UP']);assert.equal(health.ready().status,'not_ready');state.COMPLETE=2;radar.stats.lastHealthyProcessingTimestamp=1;assert.deepEqual([health.ready().status,lifecycle.state],['ready','DEGRADED']);coverage.healthyExchanges=[];assert.equal(health.ready().status,'not_ready');lifecycle.transition('STOPPING',['SHUTDOWN_REQUESTED']);assert.equal(health.ready().lifecycle,'STOPPING')});

function readinessFixture({expectedExchanges=['binance'],healthyExchanges=['binance']}={}){let listener=null;const lifecycle=new ApplicationLifecycle({now:()=>base}),state={totalStateEntries:1,COMPLETE:0},coverage={selectedMarketCount:1,healthyExchanges,expectedExchanges},radar={running:true,selected:new Map([['x',{}]]),stats:{lastHealthyProcessingTimestamp:null},store:{diagnostics:()=>state},subscribeState(value){listener=value;return()=>listener=null}},health=new HealthService({lifecycle,universe:{health:()=>({coverage})},radar,eventPipeline:{stopped:false},now:()=>base});lifecycle.transition('WARMING_UP',['RADAR_WARMING_UP']);health.start();return{lifecycle,state,coverage,radar,health,emit:()=>listener?.()}}

test('readiness follows actual Radar state changes without endpoint polling',()=>{const fixture=readinessFixture();assert.equal(fixture.lifecycle.state,'WARMING_UP');fixture.emit();assert.equal(fixture.lifecycle.state,'WARMING_UP');fixture.state.COMPLETE=1;fixture.radar.stats.lastHealthyProcessingTimestamp=base;fixture.emit();assert.equal(fixture.lifecycle.state,'READY');fixture.health.stop()});

test('restart warms independently and partial exchange readiness becomes degraded',()=>{const first=readinessFixture();first.state.COMPLETE=1;first.radar.stats.lastHealthyProcessingTimestamp=base;first.emit();assert.equal(first.lifecycle.state,'READY');first.health.stop();const restarted=readinessFixture({expectedExchanges:['binance','bybit'],healthyExchanges:['binance']});assert.equal(restarted.lifecycle.state,'WARMING_UP');restarted.state.COMPLETE=1;restarted.radar.stats.lastHealthyProcessingTimestamp=base;restarted.emit();assert.deepEqual([restarted.lifecycle.state,...restarted.lifecycle.reasonCodes],['DEGRADED','PARTIAL_PROCESSING_AVAILABLE']);restarted.health.stop()});

test('incomplete supervisor warm-up publishes nothing and completed live processing advances lifecycle',async()=>{const m=market(),store=new MarketStateStore({minimumLookback:2}),published=[],registry={evaluate:value=>published.push(value),stop(){},diagnostics:()=>[]},recovery={enqueue:()=>Promise.resolve(),stop:async()=>{},cancelMarket(){},diagnostics:()=>({})},universe={getSnapshot:()=>({markets:[m]}),subscribe:()=>()=>{},health:()=>({coverage:{selectedMarketCount:1,healthyExchanges:['binance'],expectedExchanges:['binance']}})},stream={start:async()=>{},stop:async()=>{},diagnostics:()=>({activeSockets:1,reconnectCount:0})},radar=new IngestionSupervisor({universe,store,recovery,registry,streams:{binance:stream},timeframes:['1m'],staleCheckMs:999999}),lifecycle=new ApplicationLifecycle(),health=new HealthService({lifecycle,universe,radar,eventPipeline:{stopped:false}});await radar.start();lifecycle.transition('WARMING_UP',['RADAR_WARMING_UP']);health.start();await radar.onCandle(bar(base));assert.deepEqual([store.diagnostics().WARMING_UP,lifecycle.state,published.length],[1,'WARMING_UP',0]);await radar.onCandle(bar(base+60000));assert.deepEqual([store.diagnostics().COMPLETE,lifecycle.state,published.length],[1,'READY',1]);health.stop();await radar.stop()});

test('process metrics are finite, bounded and stop cleanly',async()=>{const metrics=new ProcessMetrics().start();await new Promise(resolve=>setTimeout(resolve,30));const value=metrics.sample();assert.ok(Number.isFinite(value.memoryBytes.rss));assert.ok(Number.isFinite(value.cpu.utilizationPct));for(const key of ['mean','max','p50','p95','p99'])assert.ok(Number.isFinite(value.eventLoop[key]));metrics.stop();assert.equal(metrics.running,false)});

test('logger recursively redacts common secret fields and bearer data',()=>{const rows=[],sink={info:value=>rows.push(value),log:value=>rows.push(value)},logger=createLogger('info',sink);logger.info('test',{password:'p',apiKey:'k',nested:{Authorization:'Bearer abc',cookie:'c'},safe:'ok'});const text=rows[0];assert.equal(text.includes('"p"'),false);assert.equal(text.includes('Bearer abc'),false);assert.equal(text.includes('"k"'),false);assert.match(text,/\[REDACTED\]/)});

function httpFixture(bingxProxy=null){const lifecycle=new ApplicationLifecycle();lifecycle.transition('WARMING_UP',['RADAR_WARMING_UP']);const health={live:()=>({status:'alive',timestamp:1}),ready:()=>({status:'not_ready',lifecycle:lifecycle.state,reasonCodes:lifecycle.reasonCodes,timestamp:1}),lifecycle};const stub={status:()=>({}),diagnostics:()=>({}),list:()=>[],events:()=>[],store:{diagnostics:()=>({})},registry:{diagnostics:()=>[]},recovery:{diagnostics:()=>({})}};const value=createHttpServer({runner:stub,storage:stub,notifier:stub,universe:{health:()=>({coverage:{}}),getSnapshot:()=>({markets:[]})},eventStore:{size:0,listRecent:()=>[],getById:()=>null},eventPipeline:{diagnostics:()=>({})},radar:stub,qualification:{diagnostics:()=>({}),stats:{}},breadth:{diagnostics:()=>({})},scorePolicy:{diagnostics:()=>({})},interpretationPolicy:{diagnostics:()=>({})},health,metrics:{sample:()=>({rss:1})},bingxProxy,config:{root,allowedOrigins:['https://app.zych.markets'],internalDiagnosticsEnabled:false,vapidPublicKey:''},logger:silent});return value}
const request=(port,pathValue,options={})=>new Promise((resolve,reject)=>{const req=http.request({host:'127.0.0.1',port,path:pathValue,...options},res=>{const rows=[];res.on('data',row=>rows.push(row));res.on('end',()=>resolve({status:res.statusCode,headers:res.headers,body:Buffer.concat(rows).toString()}))});req.on('error',reject);req.end()});

test('HTTP boundary serves frontend, blocks private files, adds headers and keeps health public-safe',async()=>{const fixture=httpFixture();await new Promise(resolve=>fixture.server.listen(0,'127.0.0.1',resolve));const port=fixture.server.address().port,frontend=await request(port,'/');assert.equal(frontend.status,200);assert.match(frontend.headers['content-security-policy'],/wss:\/\/open-api-ws\.bingx\.com/);assert.doesNotMatch(frontend.headers['content-security-policy'],/https:\/\/open-api\.bingx\.com/);assert.equal((await request(port,'/style.css')).status,200);for(const target of ['/.env','/.git/config','/server/index.js','/server-data/x','/node_modules/x','/package.json','/%2e%2e/server/index.js'])assert.equal((await request(port,target)).status,404);const live=await request(port,'/health/live');assert.equal(live.status,200);assert.equal(live.headers['x-content-type-options'],'nosniff');assert.equal(JSON.parse(live.body).status,'alive');const ready=await request(port,'/health/ready');assert.equal(ready.status,503);assert.equal(/detector|threshold|score/i.test(ready.body),false);fixture.forceClose();await new Promise(resolve=>fixture.server.close(resolve))});

test('BingX public proxy allowlists endpoints, validates envelopes, caches and coalesces',async()=>{let calls=0,clock=1000,release;const gate=new Promise(resolve=>{release=resolve}),fetchImpl=async(url,options)=>{calls++;assert.equal(url,'https://open-api.bingx.com/openApi/spot/v1/common/symbols');assert.deepEqual(Object.keys(options),['signal']);await gate;return{ok:true,status:200,json:async()=>({code:0,data:{symbols:[]}})}};const proxy=createBingxPublicProxy({fetchImpl,now:()=>clock,cacheTtlMs:5});const first=proxy('catalog'),second=proxy('catalog');assert.equal(calls,1);release();assert.deepEqual(await first,await second);assert.equal(await proxy('catalog').then(value=>value.code),0);assert.equal(calls,1);clock+=6;await proxy('catalog');assert.equal(calls,2);await assert.rejects(()=>proxy('anything'),/not allowed/)});

test('BingX public proxy rejects upstream failures and malformed envelopes',async()=>{await assert.rejects(()=>createBingxPublicProxy({fetchImpl:async()=>({ok:false,status:503})})('tickers'),/HTTP 503/);for(const payload of [{code:1,data:[]},{code:0,data:{}},{code:0,data:null}])await assert.rejects(()=>createBingxPublicProxy({fetchImpl:async()=>({ok:true,status:200,json:async()=>payload})})('tickers'),/invalid envelope/)});

test('BingX HTTP proxy exposes only exact public GET routes',async()=>{const calls=[],fixture=httpFixture(async key=>{calls.push(key);return key==='catalog'?{code:0,data:{symbols:[]}}:{code:0,data:[]}});await new Promise(resolve=>fixture.server.listen(0,'127.0.0.1',resolve));const port=fixture.server.address().port;assert.equal((await request(port,'/api/markets/bingx/catalog')).status,200);assert.equal((await request(port,'/api/markets/bingx/tickers')).status,200);assert.deepEqual(calls,['catalog','tickers']);assert.equal((await request(port,'/api/markets/bingx/catalog/extra')).status,404);assert.equal((await request(port,'/api/markets/bingx/https%3A%2F%2Fevil.example')).status,404);assert.equal((await request(port,'/api/markets/bingx/catalog',{method:'POST'})).status,404);fixture.forceClose();await new Promise(resolve=>fixture.server.close(resolve))});

test('production CORS and internal diagnostics boundary reject remote callers',async()=>{const fixture=httpFixture();await new Promise(resolve=>fixture.server.listen(0,'127.0.0.1',resolve));const port=fixture.server.address().port;assert.equal((await request(port,'/api/health',{headers:{origin:'https://evil.example'}})).status,403);const accepted=await request(port,'/api/health',{headers:{origin:'https://app.zych.markets'}});assert.equal(accepted.headers['access-control-allow-origin'],'https://app.zych.markets');assert.equal((await request(port,'/api/radar/health',{headers:{'x-forwarded-for':'203.0.113.9'}})).status,404);fixture.forceClose();await new Promise(resolve=>fixture.server.close(resolve))});

test('all exchange history adapters exclude current open rows and retain closed history',async()=>{const now=base+120000,closed=base,open=base+120000;const fixtures={binance:{body:[[closed,'1','1','1','1','1',closed+59999,'1'],[open,'1','1','1','1','1',open+59999,'1']]},bybit:{body:{retCode:0,result:{list:[[closed,'1','1','1','1','1','1'],[open,'1','1','1','1','1','1']]}}},okx:{body:{code:'0',data:[[closed,'1','1','1','1','1','x','1','1'],[open,'1','1','1','1','1','x','1','0']]}}};for(const exchange of Object.keys(fixtures)){const adapter=new CandleHistoryAdapter({exchange,restBase:'https://example.test',now:()=>now,fetchImpl:async()=>({ok:true,json:async()=>fixtures[exchange].body})}),rows=await adapter.fetch(market(exchange),'1m');assert.deepEqual(rows.map(item=>item.openTime),[closed],exchange)}});

test('REST/live overlap evaluates exactly once in both arrival orders',async()=>{for(const liveFirst of [false,true]){const m=market(),store=new MarketStateStore({minimumLookback:2}),evaluated=[];let release;const recovery=new RecoveryCoordinator({store,retries:0,isMarketActive:()=>true,adapters:{binance:{fetch:async()=>{if(liveFirst)await new Promise(resolve=>release=resolve);return[bar(base),bar(base+60000)]}}}}),registry={evaluate:input=>evaluated.push(input.event.openTime),stop(){},diagnostics:()=>[]},universe={getSnapshot:()=>({markets:[m]}),subscribe:()=>()=>{}},stream={start:async()=>{},stop:async()=>{},diagnostics:()=>({activeSockets:1,reconnectCount:0})},supervisor=new IngestionSupervisor({universe,store,recovery,registry,streams:{binance:stream},timeframes:['1m'],warmupLimit:2,staleCheckMs:999999});await supervisor.start();if(liveFirst){await supervisor.onCandle(bar(base+60000));release()}await new Promise(resolve=>setImmediate(resolve));if(!liveFirst)await supervisor.onCandle(bar(base+60000));await new Promise(resolve=>setImmediate(resolve));assert.deepEqual(evaluated,[base+60000]);await supervisor.stop()}});

test('removed markets cannot be recreated by queued or active recovery',async()=>{for(const active of [false,true]){const m=market(),store=new MarketStateStore({minimumLookback:1});let allowed=true,release;const adapter={fetch:async()=>{if(active)await new Promise(resolve=>release=resolve);return[bar(base)]}},recovery=new RecoveryCoordinator({store,concurrency:active?1:0,retries:0,isMarketActive:()=>allowed,adapters:{binance:adapter}});const pending=recovery.enqueue({kind:'warmup',market:m,timeframe:'1m'});await new Promise(resolve=>setImmediate(resolve));allowed=false;recovery.cancelMarket(m.marketId);store.removeMarket(m.marketId);if(release)release();await pending;assert.equal(store.get(m.marketId,'1m'),null);await recovery.stop()}});

test('integrated restart safety remains silent until continuous warm-up completes',()=>{const m=market(),oldStore=new MarketStateStore({minimumLookback:3});oldStore.load(m,'1m',[bar(base),bar(base+60000),bar(base+120000)]);oldStore.stop();const store=new MarketStateStore({minimumLookback:3}),candidates=[],registry=new DetectorRegistry({pipeline:{publishCandidate:value=>(candidates.push(value),true)},detectors:[new PriceMomentumDetector({minimumWarmup:3,baselineWindow:2,signalWindow:1,threshold:99}),new VolumeAnomalyDetector({baselineWindow:2,minimumRelativeVolume:99,minimumZScore:99})]});const first=store.append(m,'1m',bar(base));registry.evaluate({event:first.candle,market:m,state:first.state});assert.equal(store.get(m.marketId,'1m').dataQuality,'WARMING_UP');assert.equal(candidates.length,0);store.load(m,'1m',[bar(base+60000),bar(base+120000)]);assert.equal(store.get(m.marketId,'1m').dataQuality,'COMPLETE');const live=store.append(m,'1m',bar(base+180000));registry.evaluate({event:live.candle,market:m,state:live.state});assert.equal(candidates.length,0)});

test('partial startup failure cleans already-started resources',async()=>{let stopped=0;const runner={async start(){},async stop(){stopped++}},storage={async init(){}},config={host:'127.0.0.1',port:0,dataDir:root,historyLimit:500,logLevel:'error',root,radarEnabled:true,radarIngestionEnabled:false,radarEventStoreLimit:10,radarEventQueueLimit:10,radarQualification:{},radarScore:{},universePolicy:{}},universe={async initialize(){throw new Error('startup failure')}};await assert.rejects(createServerApp({config,logger:silent,storage,runner,transport:{},notifier:{},universe}),/startup failure/);assert.equal(stopped,1)});

async function lifecycleApp({hanging=false,timeout=1000}={}){const config={...loadConfig({RADAR_UNIVERSE_ENABLED:'false'}),port:0,shutdownTimeoutMs:timeout},runner={async start(){},async stop(){if(hanging)await new Promise(()=>{})},diagnostics:()=>({}),list:()=>[],events:()=>[]},storage={async init(){},status:()=>({}),async close(){}},notifier={status:()=>({})};return createServerApp({config,logger:silent,storage,runner,transport:{},notifier})}
test('SIGTERM and SIGINT request graceful idempotent shutdown',async()=>{for(const signal of ['SIGTERM','SIGINT']){const app=await lifecycleApp();await Promise.all([app.stop(signal),app.stop(signal)]);assert.equal(app.lifecycle.state,'STOPPED');assert.ok(app.lifecycle.history.some(item=>item.reasonCodes.includes(`SIGNAL_${signal}`)))}});
test('shutdown deadline forces controlled completion',async()=>{const app=await lifecycleApp({hanging:true,timeout:20}),start=Date.now();await app.stop('SIGTERM');assert.ok(Date.now()-start<500);assert.equal(app.lifecycle.state,'STOPPED')});

test('shutdown aborts active recovery requests',async()=>{const m=market(),store=new MarketStateStore({minimumLookback:1});let aborted=false;const recovery=new RecoveryCoordinator({store,retries:0,isMarketActive:()=>true,adapters:{binance:{fetch:async(_m,_t,{signal})=>new Promise((resolve,reject)=>signal.addEventListener('abort',()=>{aborted=true;reject(Object.assign(new Error('aborted'),{name:'AbortError'}))},{once:true}))}}});const pending=recovery.enqueue({kind:'warmup',market:m,timeframe:'1m'}).catch(()=>{});await new Promise(resolve=>setImmediate(resolve));await recovery.stop();await pending;assert.equal(aborted,true)});
