'use strict';
const assert=require('node:assert/strict');
const quick=require('../js/alerts/quick-chart-alerts.js');
assert.equal(quick.coordinateToPrice({coordinateToPrice:y=>100-y},25),75);
assert.equal(quick.coordinateToPrice({coordinateToPrice:()=>NaN},25),null);
assert.equal(quick.operatorFor(101,100),'above');assert.equal(quick.operatorFor(99,100),'below');
const market=(exchange,symbol)=>({id:`${exchange}:${symbol}`,marketId:`${exchange}:${symbol}`,exchange,symbol,asset:'BTC',baseAsset:'BTC',quoteAsset:'USDT'});
for(const [exchange,symbol] of [['binance','BTCUSDT'],['bybit','BTCUSDT'],['okx','BTC-USDT']]){const definition=quick.definitionFor(market(exchange,symbol),101,100);assert.equal(definition.exchange,exchange);assert.equal(definition.marketId,`${exchange}:${symbol}`);assert.equal(definition.symbol,symbol);assert.equal(definition.condition.operator,'above')}
const alerts=[...['binance:BTCUSDT','bybit:BTCUSDT','okx:BTC-USDT'].map((marketId,index)=>({id:String(index),marketId,status:'active',condition:{type:'price',value:100+index}})),{id:'paused',marketId:'binance:BTCUSDT',status:'paused',condition:{type:'price',value:90}},{id:'volume',marketId:'binance:BTCUSDT',status:'active',condition:{type:'volume',value:90}}];
assert.deepEqual(quick.matchingAlerts(alerts,'binance:BTCUSDT').map(item=>item.id),['0','paused']);assert.deepEqual(quick.matchingAlerts(alerts,'bybit:BTCUSDT').map(item=>item.id),['1']);assert.deepEqual(quick.matchingAlerts(alerts,'okx:BTC-USDT').map(item=>item.id),['2']);
const normalized=[{id:'normalized',marketId:'bybit:spot:BTCUSDT',status:'active',condition:{type:'price',value:80000}}];
const selectedMarketId='bybit:spot:BTCUSDT',openAlerts=quick.matchingAlerts(normalized,selectedMarketId),chartLines=quick.matchingAlerts(normalized,selectedMarketId);
assert.deepEqual(openAlerts.map(item=>item.id),['normalized']);assert.strictEqual(openAlerts[0],chartLines[0]);
const action={textContent:''},element={hidden:true,style:{},querySelector:()=>action},menu=new quick.MenuController(element);menu.open({x:10,y:20,price:123,label:'123.00'});assert.equal(element.hidden,false);assert.equal(menu.payload.price,123);assert.match(action.textContent,/123\.00/);menu.close();assert.equal(element.hidden,true);assert.equal(menu.payload,null);
assert.equal(quick.closestLine([{id:'a',price:100},{id:'b',price:200}],52,price=>price/2,4).id,'a');assert.equal(quick.closestLine([{id:'a',price:100}],70,price=>price/2,4),null);
assert.equal(quick.exceedsDragThreshold({x:10,y:10},12,12),false);assert.equal(quick.exceedsDragThreshold({x:10,y:10},14,10),true);
const deferred=()=>{let resolve,reject;const promise=new Promise((yes,no)=>{resolve=yes;reject=no});return{promise,resolve,reject}};
(async()=>{
  const coordinator=new quick.UpdateCoordinator(),applied=[],calls=[];coordinator.register('a',100);
  await coordinator.commit('a',110,{update:async(id,value)=>{calls.push([id,value]);return{alert:{condition:{value}}}},apply:value=>applied.push(value)});assert.deepEqual(calls,[['a',110]]);assert.deepEqual(applied,[110]);assert.equal(coordinator.confirmed('a'),110);
  const first=deferred(),second=deferred();calls.length=0;applied.length=0;const p1=coordinator.commit('a',120,{update:async(_id,value)=>{calls.push(value);return first.promise},apply:value=>applied.push(value)});const p2=coordinator.commit('a',130,{update:async(_id,value)=>{calls.push(value);return second.promise},apply:value=>applied.push(value)});await new Promise(resolve=>setImmediate(resolve));assert.deepEqual(calls,[120]);first.resolve({alert:{condition:{value:120}}});await new Promise(resolve=>setImmediate(resolve));assert.deepEqual(calls,[120,130]);assert.deepEqual(applied,[]);second.resolve({alert:{condition:{value:130}}});await Promise.all([p1,p2]);assert.deepEqual(applied,[130]);assert.equal(coordinator.confirmed('a'),130);
  const staleFailure=deferred(),newSuccess=deferred();applied.length=0;const p3=coordinator.commit('a',140,{update:()=>staleFailure.promise,apply:value=>applied.push(value)}).catch(()=>{});const p4=coordinator.commit('a',150,{update:()=>newSuccess.promise,apply:value=>applied.push(value)});staleFailure.reject(new Error('old'));await new Promise(resolve=>setImmediate(resolve));assert.deepEqual(applied,[]);newSuccess.resolve({alert:{condition:{value:150}}});await Promise.all([p3,p4]);assert.deepEqual(applied,[150]);
})().then(async()=>{
  const coordinator=new quick.UpdateCoordinator(),applied=[];coordinator.register('a',100);const failure=coordinator.commit('a',120,{update:async()=>{throw new Error('down')},apply:value=>applied.push(value)}).catch(()=>{});await failure;assert.deepEqual(applied,[100]);coordinator.register('b',200);await coordinator.commit('b',210,{update:async(_id,value)=>({alert:{condition:{value}}}),apply:value=>applied.push(value)});assert.equal(coordinator.confirmed('a'),100);assert.equal(coordinator.confirmed('b'),210);
  const actions=new quick.ActionCoordinator(),states=[];actions.register('a','active');await actions.commit('a','paused',{update:async()=>({alert:{status:'paused'}}),apply:value=>states.push(value)});assert.deepEqual(states,['paused','paused']);assert.equal(actions.confirmed('a'),'paused');const rollback=actions.commit('a','active',{update:async()=>{throw new Error('down')},apply:value=>states.push(value)}).catch(()=>{});await rollback;assert.deepEqual(states.slice(-2),['active','paused']);
  const old=deferred(),latest=deferred();states.length=0;const pause=actions.commit('a','active',{update:()=>old.promise,apply:value=>states.push(value)});const resume=actions.commit('a','paused',{update:()=>latest.promise,apply:value=>states.push(value)});old.resolve({alert:{status:'active'}});await new Promise(resolve=>setImmediate(resolve));latest.resolve({alert:{status:'paused'}});await Promise.all([pause,resume]);assert.deepEqual(states,['active','paused','paused']);assert.equal(actions.confirmed('a'),'paused');
  const staleFail=deferred(),newer=deferred();states.length=0;const oldFailure=actions.commit('a','active',{update:()=>staleFail.promise,apply:value=>states.push(value)}).catch(()=>{});const newerSuccess=actions.commit('a','paused',{update:()=>newer.promise,apply:value=>states.push(value)});staleFail.reject(new Error('old'));await new Promise(resolve=>setImmediate(resolve));newer.resolve({alert:{status:'paused'}});await Promise.all([oldFailure,newerSuccess]);assert.deepEqual(states,['active','paused','paused']);
  actions.register('b','active');states.length=0;await actions.commit('b',null,{optimistic:false,update:async()=>({}),apply:value=>states.push(value)});assert.deepEqual(states,[null]);assert.equal(actions.confirmed('b'),null);actions.register('c','active');states.length=0;await actions.commit('c',null,{optimistic:false,update:async()=>{throw new Error('down')},apply:value=>states.push(value)}).catch(()=>{});assert.deepEqual(states,['active']);assert.equal(actions.confirmed('c'),'active');console.log('quick chart alerts tests: PASS')}).catch(error=>{console.error(error);process.exitCode=1});
