'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {BinanceCatalogAdapter,BybitCatalogAdapter,OkxCatalogAdapter}=require('../server/radar/catalog-adapters.js');
const {MarketCatalogService}=require('../server/radar/market-catalog-service.js');
const {MarketUniverseService}=require('../server/radar/market-universe-service.js');
const {evaluateEligibility,REASONS}=require('../server/radar/universe-policy.js');
const {marketId,matches}=require('../server/radar/market-identity.js');
const {loadConfig}=require('../server/config.js');
const silent={warn(){}};
const response=value=>({ok:true,json:async()=>value});
const now=1700000000000;
const policy={version:'test-v1',marketType:'spot',allowedQuotes:['USDT'],targetUniverseSize:100,minimumQuoteVolume24h:1000,staleSnapshotTimeoutMs:60000,maximumSpreadPct:null,missingSpreadPolicy:'allow',liquidityTiers:{A:100000,B:10000,C:1000}};
const market=(exchange,symbol,volume,extra={})=>({marketId:`${exchange}:spot:${symbol}`,legacyMarketId:`${exchange}:${symbol}`,exchange,marketType:'spot',symbol,baseAsset:symbol.replace(/-?USDT$/,''),quoteAsset:'USDT',status:exchange==='okx'?'live':'TRADING',quoteVolume24h:volume,marketAge:null,spread:null,snapshotTimestamp:now,...extra});

test('catalog adapters normalize Binance Bybit OKX spot markets',async()=>{
  const binance=new BinanceCatalogAdapter({now:()=>now,fetchImpl:async url=>url.endsWith('exchangeInfo')?response({symbols:[{symbol:'BTCUSDT',baseAsset:'BTC',quoteAsset:'USDT',status:'TRADING',isSpotTradingAllowed:true}]}):response([{symbol:'BTCUSDT',quoteVolume:'2000',bidPrice:'99',askPrice:'101'}])});
  const bybit=new BybitCatalogAdapter({now:()=>now,fetchImpl:async url=>url.includes('instruments-info')?response({retCode:0,result:{list:[{symbol:'BTCUSDT',baseCoin:'BTC',quoteCoin:'USDT',status:'Trading'}]}}):response({retCode:0,result:{list:[{symbol:'BTCUSDT',turnover24h:'3000',bid1Price:'99',ask1Price:'100'}]}})});
  const okx=new OkxCatalogAdapter({now:()=>now,fetchImpl:async url=>url.includes('/public/instruments')?response({code:'0',data:[{instId:'BTC-USDT',baseCcy:'BTC',quoteCcy:'USDT',state:'live'}]}):response({code:'0',data:[{instId:'BTC-USDT',volCcy24h:'4000',bidPx:'99',askPx:'100'}]})});
  const rows=(await Promise.all([binance.load(),bybit.load(),okx.load()])).flat();assert.deepEqual(rows.map(row=>row.marketId),['binance:spot:BTCUSDT','bybit:spot:BTCUSDT','okx:spot:BTC-USDT']);assert.equal(rows.every(row=>row.marketType==='spot'),true);assert.deepEqual(rows.map(row=>row.quoteVolume24h),[2000,3000,4000]);assert.equal(rows.every(row=>Number.isFinite(row.spread)),true)
});
test('typed identity is exchange specific and legacy compatible',()=>{const a=market('binance','SOLUSDT',2000),b=market('bybit','SOLUSDT',2000),c=market('okx','SOL-USDT',2000);assert.equal(new Set([a.marketId,b.marketId,c.marketId]).size,3);assert.equal(marketId(a),a.marketId);assert.equal(matches(a,'binance:SOLUSDT'),true)});
test('eligibility exposes quote volume stale and reason codes with tiers',()=>{assert.deepEqual(evaluateEligibility(market('binance','AUSDT',200000),policy,now),{eligible:true,liquidityTier:'A',reasons:[REASONS.ACTIVE_MARKET,REASONS.SPOT_MARKET,REASONS.ALLOWED_QUOTE,REASONS.SUFFICIENT_VOLUME]});assert.equal(evaluateEligibility(market('binance','BUSD',200000,{quoteAsset:'USD'}),policy,now).reasons.includes(REASONS.DISALLOWED_QUOTE),true);assert.equal(evaluateEligibility(market('binance','CUSDT',999),policy,now).reasons.includes(REASONS.LOW_VOLUME),true);assert.equal(evaluateEligibility(market('binance','DUSDT',2000,{snapshotTimestamp:now-60001}),policy,now).reasons.includes(REASONS.STALE_SNAPSHOT),true);assert.equal(evaluateEligibility(market('binance','EUSDT',20000),policy,now).liquidityTier,'B')});
test('universe ranks Top 100 without collapsing same symbols and reports coverage',async()=>{const rows=[];for(let i=0;i<120;i++)rows.push(market('binance',`A${i}USDT`,1000+i));rows.push(market('bybit','SOLUSDT',9000),market('okx','SOL-USDT',8000));const catalog={refresh:async()=>({exchanges:{binance:{status:'HEALTHY',markets:rows.filter(x=>x.exchange==='binance'),error:null},bybit:{status:'HEALTHY',markets:rows.filter(x=>x.exchange==='bybit'),error:null},okx:{status:'HEALTHY',markets:rows.filter(x=>x.exchange==='okx'),error:null}}})},service=new MarketUniverseService({catalog,policy,now:()=>now,refreshIntervalMs:0});await service.initialize();const snapshot=service.getSnapshot({includeExcluded:true});assert.equal(snapshot.markets.length,100);assert.equal(snapshot.markets[0].marketId,'bybit:spot:SOLUSDT');assert.equal(snapshot.markets.some(x=>x.marketId==='okx:spot:SOL-USDT'),true);assert.equal(snapshot.coverage.status,'HEALTHY');assert.equal(snapshot.coverage.marketCount,122);assert.equal(snapshot.coverage.selectedMarketCount,100);await service.stop()});
test('one failed exchange stays isolated and cached exchange becomes stale',async()=>{let fail=false;const adapters=[{id:'binance',load:async()=>[market('binance','BTCUSDT',5000)]},{id:'bybit',load:async()=>{if(fail)throw new Error('down');return[market('bybit','BTCUSDT',4000)]}},{id:'okx',load:async()=>[market('okx','BTC-USDT',3000)]}],catalog=new MarketCatalogService({adapters,now:()=>now,logger:silent}),service=new MarketUniverseService({catalog,policy,now:()=>now,refreshIntervalMs:0});await service.initialize();fail=true;await service.refresh();const snapshot=service.getSnapshot({includeExcluded:true});assert.equal(snapshot.markets.some(x=>x.exchange==='binance'),true);assert.equal(snapshot.markets.some(x=>x.exchange==='okx'),true);assert.equal(snapshot.markets.some(x=>x.exchange==='bybit'),false);assert.equal(snapshot.excludedMarkets.find(x=>x.exchange==='bybit').eligibility.reasons.includes(REASONS.EXCHANGE_STALE),true);assert.equal(snapshot.coverage.exchanges.bybit.status,'STALE');assert.equal(snapshot.coverage.status,'DEGRADED');await service.stop()});
test('overlapping refresh returns one job and stop aborts cleanly',async()=>{let calls=0,release;const catalog={refresh:signal=>{calls++;return new Promise((resolve,reject)=>{release=()=>resolve({exchanges:{binance:{status:'HEALTHY',markets:[],error:null}}});signal.addEventListener('abort',()=>reject(Object.assign(new Error('aborted'),{name:'AbortError'})),{once:true})})}},service=new MarketUniverseService({catalog,policy,now:()=>now,refreshIntervalMs:0});service.running=true;const first=service.refresh(),second=service.refresh();assert.equal(first,second);assert.equal(calls,1);release();await first;const pending=service.refresh();await service.stop();await assert.rejects(pending,{name:'AbortError'});assert.equal(service.timer,null)});
test('configuration loading is bounded and explicit',()=>{const config=loadConfig({RADAR_TARGET_SIZE:'200',RADAR_ALLOWED_QUOTES:'USDT,USDC',RADAR_MIN_QUOTE_VOLUME_24H:'2500',RADAR_MAX_SPREAD_PCT:'0.5'});assert.equal(config.radarEnabled,true);assert.equal(config.universePolicy.marketType,'spot');assert.equal(config.universePolicy.targetUniverseSize,200);assert.deepEqual([...config.universePolicy.allowedQuotes],['USDT','USDC']);assert.equal(config.universePolicy.minimumQuoteVolume24h,2500);assert.equal(config.universePolicy.maximumSpreadPct,.5)});
