'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const adapters=require('../js/exchanges/exchange-adapter-v2'),workspace=require('../js/services/exchange-workspace'),instruments=require('../js/services/instrument-search');
const market=(exchange,symbol,baseAsset='BTC',quoteAsset='USDT')=>instruments.normalize({exchange,marketType:'spot',symbol,baseAsset,quoteAsset,enabled:true,status:'TRADING'});
const markets=[market('binance','BTCUSDT'),market('bybit','BTCUSDT'),market('okx','BTC-USDT'),market('binance','ETHUSDT','ETH'),market('bybit','ETHUSDT','ETH'),market('okx','ETH-USDT','ETH')];

for(const [from,to] of [['binance','bybit'],['bybit','okx'],['okx','binance']])test(`Stage 13C.2 manual selection ${from} → ${to} preserves exact exchange`,()=>{const current=markets.find(row=>row.exchange===from&&row.baseAsset==='BTC'),selected=workspace.manualSwitchMarket(markets,current,to);assert.equal(workspace.resolveExchange(to),to);assert.equal(selected.exchange,to);assert.equal(selected.id,`${to}:spot:${to==='okx'?'BTC-USDT':'BTCUSDT'}`);});

test('manual exchange identities and selector membership come from Adapter v2',()=>{assert.equal(workspace.exchanges,adapters.manualExchangeIds);for(const id of ['binance','bybit','okx']){assert.equal(workspace.resolveExchange(id),adapters.resolveExchange(id).id);assert.equal(adapters.get(id).capabilities.manualExchangeSwitch.state,'SUPPORTED');}});
test('invalid or normalized-looking exchange IDs fail closed without a fake canonical exchange',()=>{for(const id of ['BINANCE',' binance ','unknown','']){assert.equal(workspace.resolveExchange(id),null);assert.equal(workspace.manualSwitchMarket(markets,markets[0],id),null);assert.equal(adapters.canonicalId(id,'spot','BTCUSDT'),null);}});
test('manual switch preserves native symbol and rejects cross-exchange or corrupted canonical IDs',()=>{const okx=workspace.manualSwitchMarket(markets,markets[0],'okx');assert.equal(okx.symbol,'BTC-USDT');assert.deepEqual(adapters.parseCanonicalId(okx.id),{exchange:'okx',marketType:'spot',nativeSymbol:'BTC-USDT',marketId:'okx:spot:BTC-USDT'});assert.equal(workspace.manualSwitchMarket([{...okx,id:'binance:spot:BTCUSDT'}],markets[0],'okx'),null);});
test('Stage 13C.1 Search remains exchange-exact after manual switching',()=>{const selected=workspace.manualSwitchMarket(markets,markets[0],'okx'),results=instruments.search(markets,'BTC');assert.equal(selected.exchange,'okx');assert.deepEqual(results.map(row=>row.id).sort(),['binance:spot:BTCUSDT','bybit:spot:BTCUSDT','okx:spot:BTC-USDT']);assert.equal(results.find(row=>row.id===selected.id).symbol,'BTC-USDT');});
test('browser selector is generated from Adapter v2 and the handler uses exact resolution',()=>{const source=fs.readFileSync(path.join(__dirname,'..','app.js'),'utf8'),html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');assert.match(source,/ZychExchangeAdapterV2\.manualExchangeIds\.map/);assert.match(source,/ZychWorkspace\.resolveExchange\(exchange\)/);assert.doesNotMatch(html,/data-active-exchange-option=/);});
