'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const instruments=require('../js/services/instrument-search.js'),marketContext=require('../js/services/market-context.js'),radarEvents=require('../js/services/radar-event.js');
const markets=[
  {exchange:'binance',marketType:'spot',symbol:'BTCUSDT',baseAsset:'BTC',quoteAsset:'USDT'},
  {exchange:'bybit',marketType:'spot',symbol:'BTCUSDT',baseAsset:'BTC',quoteAsset:'USDT'},
  {exchange:'okx',marketType:'spot',symbol:'BTC-USDT',baseAsset:'BTC',quoteAsset:'USDT'},
  {exchange:'binance',marketType:'spot',symbol:'WBTCUSDT',baseAsset:'WBTC',quoteAsset:'USDT'},
  {exchange:'binance',marketType:'spot',symbol:'AAVEBTC',baseAsset:'AAVE',quoteAsset:'BTC'}
];
test('normalized instrument IDs are stable and retain native and display symbols',()=>{const a=instruments.normalize(markets[0]),b=instruments.normalize({...markets[0],status:'TRADING'});assert.equal(a.id,'binance:spot:BTCUSDT');assert.equal(a.id,b.id);assert.deepEqual([a.displaySymbol,a.nativeSymbol],['BTC/USDT','BTCUSDT'])});
test('global BTC search is case-insensitive, cross-exchange, and ranks exact bases first',()=>{for(const query of ['BTC','btc','Btc']){const results=instruments.search(markets,query);assert.deepEqual(results.slice(0,3).map(item=>item.exchange),['binance','bybit','okx']);assert.equal(results.slice(0,3).every(item=>item.baseAsset==='BTC'),true);assert.equal(results.at(-1).baseAsset,'WBTC');assert.equal(results.some(item=>item.baseAsset==='AAVE'),false)}});
test('selected search identity preserves the exact exchange and instrument for chart context',()=>{const selected=instruments.search(markets,'BTC').find(item=>item.exchange==='okx'),context=marketContext.fromMarket(selected);assert.deepEqual([context.marketId,context.exchange,context.symbol],['okx:spot:BTC-USDT','okx','BTC-USDT'])});
test('English fallback, Russian loading, and persisted language preference work',()=>{class Storage{constructor(){this.value=new Map()}getItem(key){return this.value.get(key)||null}setItem(key,value){this.value.set(key,String(value))}}global.localStorage=new Storage();delete require.cache[require.resolve('../js/services/i18n.js')];const i18n=require('../js/services/i18n.js');assert.equal(i18n.resolveLocale('fr-FR'),'en');i18n.setPreference('en');assert.equal(i18n.t('search.noResults'),'No markets found');i18n.setPreference('ru');assert.equal(i18n.t('search.noResults'),'Рынки не найдены');assert.equal(global.localStorage.getItem(i18n.STORAGE_KEY),'ru');delete require.cache[require.resolve('../js/services/i18n.js')];assert.equal(require('../js/services/i18n.js').preference(),'ru');delete global.localStorage});
const unified=({exchange='binance',symbol='BTCUSDT',eventId='radar-1',timestamps=[1000,1001,1002],metrics={price:100,priceChangePct:2.5,volume:400,relativeVolume:4},score={value:82,quality:'STRONG'},interpretation={label:'Momentum <strong>',summary:'Move & volume'},deepLink}={})=>{const marketType='spot',marketId=`${exchange}:${marketType}:${symbol}`;return{schemaVersion:1,eventId,detectorId:'qualification',detectorVersion:'qualification-v1',eventType:'RADAR_OPPORTUNITY',setupType:'MOMENTUM_WITH_VOLUME_CONFIRMATION',direction:'UP',market:{marketId,exchange,marketType,symbol,baseAsset:'BTC',quoteAsset:'USDT'},timeframe:'5m',eventTimestamp:timestamps[0],observedAt:timestamps[1],createdAt:timestamps[2],metrics,score,interpretation,marketContext:{breadth:{dataQuality:'COMPLETE'}},deepLink:deepLink||{marketId,exchange,marketType,symbol,timeframe:'5m',eventTimestamp:timestamps[0]}}};
test('RadarEvent normalizes production UnifiedEvents and preserves honest display fields',()=>{const event=radarEvents.create(unified());assert.deepEqual({eventId:event.eventId,marketId:event.marketId,exchange:event.exchange,marketType:event.marketType,symbol:event.symbol,baseAsset:event.baseAsset,quoteAsset:event.quoteAsset,timeframe:event.timeframe}, {eventId:'radar-1',marketId:'binance:spot:BTCUSDT',exchange:'binance',marketType:'spot',symbol:'BTCUSDT',baseAsset:'BTC',quoteAsset:'USDT',timeframe:'5m'});assert.deepEqual([event.eventTimestamp,event.observedAt,event.createdAt],[1000,1001,1002]);assert.deepEqual([event.interpretationLabel,event.interpretationSummary],['Momentum <strong>','Move & volume']);assert.equal(event.eventChangePct,2.5);assert.equal(event.eventVolume,400);assert.equal('change24h' in event,false);assert.equal('volume24h' in event,false);assert.equal(Object.isFrozen(event),true)});
test('RadarEvent keeps canonical Binance, Bybit, and native OKX identities',()=>{for(const [exchange,symbol]of [['binance','BTCUSDT'],['bybit','BTCUSDT'],['okx','BTC-USDT']]){const event=radarEvents.create(unified({exchange,symbol}));assert.equal(event.marketId,`${exchange}:spot:${symbol}`);assert.equal(event.deepLink.marketId,event.marketId);assert.equal(event.symbol,symbol)}});
test('RadarEvent rejects inconsistent identities, event IDs, and timestamps',()=>{assert.equal(radarEvents.create(unified({deepLink:{marketId:'bybit:spot:BTCUSDT',exchange:'bybit',marketType:'spot',symbol:'BTCUSDT',timeframe:'5m',eventTimestamp:1000}})),null);assert.equal(radarEvents.create(unified({eventId:''})),null);assert.equal(radarEvents.create(unified({eventId:'bad id'})),null);for(const timestamps of [[0,1,2],[1,0,2],[1,2,NaN]])assert.equal(radarEvents.create(unified({timestamps})),null)});
test('RadarEvent preserves unavailable optional metrics and valid zero score',()=>{const event=radarEvents.create(unified({metrics:{},score:{value:0,quality:'LOW'},interpretation:null}));assert.equal(event.score,0);assert.equal(event.scoreQuality,'LOW');assert.equal(event.price,null);assert.equal(event.eventChangePct,null);assert.equal(event.eventVolume,null);assert.equal(event.relativeVolume,null);assert.equal(event.interpretationLabel,null);assert.equal(event.interpretationSummary,null)});
