'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const adapters=require('../js/exchanges/exchange-adapter-v2'),search=require('../js/services/instrument-search'),context=require('../js/services/market-context'),workspace=require('../js/services/exchange-workspace');
const {markets}=require('./six-exchange-fixture');
const exchanges=['binance','bybit','okx','bingx','coinbase','kraken'];

test('13C.1 registry is the ordered product membership authority',()=>{assert.deepEqual(adapters.exchangeIds,exchanges);assert.equal(new Set(adapters.exchangeIds).size,6);assert.deepEqual(search.PRODUCT_EXCHANGES,adapters.exchangeIds);assert.deepEqual(workspace.exchanges,adapters.exchangeIds);assert.deepEqual([...search.MARKET_TYPES],['spot']);});
test('13C.1 Search admits only registered Spot exchanges without capability filtering',()=>{const foreign={exchange:'unknown',marketType:'spot',symbol:'BTCUSDT',baseAsset:'BTC',quoteAsset:'USDT'},perpetual={exchange:'binance',marketType:'perpetual',symbol:'BTCUSDT',baseAsset:'BTC',quoteAsset:'USDT'},result=search.search([...markets,foreign,perpetual],'BTC');assert.deepEqual([...new Set(result.map(row=>row.exchange))].sort(),[...exchanges].sort());assert.ok(result.some(row=>row.exchange==='coinbase'));assert.ok(result.some(row=>row.exchange==='kraken'));assert.equal(result.some(row=>row.exchange==='unknown'||row.marketType!=='spot'),false);});
test('13C.1 all six native BTC identities round-trip without rewriting',()=>{const examples={binance:'BTCUSDT',bybit:'BTCUSDT',okx:'BTC-USDT',bingx:'BTC-USDT',coinbase:'BTC-USD',kraken:'XXBTZUSD'};for(const [exchange,nativeSymbol] of Object.entries(examples)){const id=`${exchange}:spot:${nativeSymbol}`,row=search.normalize({exchange,marketType:'spot',symbol:nativeSymbol,baseAsset:'BTC',quoteAsset:nativeSymbol.endsWith('USDT')?'USDT':'USD'});assert.equal(row.nativeSymbol,nativeSymbol);assert.equal(row.symbol,nativeSymbol);assert.equal(row.marketId,id);assert.equal(context.fromMarket(row).marketId,id);assert.deepEqual(adapters.parseCanonicalId(id),{exchange,marketType:'spot',nativeSymbol,marketId:id});}});
test('13C.1 Kraken aliases resolve only to the native REST key',()=>{const identity=adapters.get('kraken').identity,catalog=[{nativeSymbol:'XXBTZUSD',symbol:'XXBTZUSD',searchAliases:['XBT/USD','BTC/USD','XBTUSD']}];for(const alias of ['XBT/USD','BTC/USD','XBTUSD','XXBTZUSD'])assert.equal(identity.resolve(alias,catalog),'kraken:spot:XXBTZUSD');assert.equal(search.search(markets,'XBTUSD')[0].nativeSymbol,'XXBTZUSD');});
test('13C.1 Coinbase product ID stays canonical and synthetic forms are input only',()=>{const row=search.search(markets,'BTCUSD').find(item=>item.exchange==='coinbase'&&item.quoteAsset==='USD');assert.equal(row.nativeSymbol,'BTC-USD');assert.equal(row.marketId,'coinbase:spot:BTC-USD');assert.equal(adapters.canonicalId('coinbase','spot','BTCUSD'),null);assert.equal(search.normalize({...row,symbol:'BTC/USD',nativeSymbol:'BTC/USD'}),null);});
test('13C.1 representative Search aliases preserve exchange-distinct native results',()=>{for(const query of ['BTC','BTCUSDT','BTC-USDT','BTC/USDT','BTC-USD','XBTUSD','XXBTZUSD','USDC','EUR']){const rows=search.search(markets,query);assert.ok(rows.length,query);for(const row of rows){assert.ok(exchanges.includes(row.exchange));assert.equal(row.id,`${row.exchange}:spot:${row.nativeSymbol}`);assert.ok(markets.some(item=>item.id===row.id));}}const btc=search.search(markets,'BTC');assert.equal(new Set(btc.map(row=>row.id)).size,btc.length);});
test('13C.1 Search navigation and saved IDs resolve the exact original market',()=>{for(const id of ['binance:spot:BTCUSDT','bingx:spot:BTC-USDT','coinbase:spot:BTC-USD','kraken:spot:XXBTZUSD']){const selected=markets.find(row=>row.id===id),result=search.search(markets,selected.nativeSymbol).find(row=>row.id===id),marketContext=context.fromMarket(result,{timeframe:'1h'});assert.equal(marketContext.marketId,id);assert.equal(workspace.restoreMarket(markets,{exchange:result.exchange,marketId:id}),selected);}});
test('13C.1 browser loads the registry before migrated consumers and preserves six registry-backed options',()=>{const html=fs.readFileSync(require.resolve('../index.html'),'utf8'),app=fs.readFileSync(require.resolve('../app.js'),'utf8'),registry=html.indexOf('js/exchanges/exchange-adapter-v2.js');assert.ok(registry>0);for(const file of ['js/services/instrument-search.js','js/services/exchange-workspace.js','js/services/market-context.js'])assert.ok(registry<html.indexOf(file));assert.equal((html.match(/data-active-exchange-option=/g)||[]).length,0);assert.match(app,/ZychExchangeAdapterV2\.manualExchangeIds\.map/);assert.equal(adapters.manualExchangeIds.length,6);});
