'use strict';
const {createCandidateEvent}=require('../event-schema.js');
const {volumeBaseline}=require('../rolling-baseline.js');
class VolumeAnomalyDetector{
  constructor({enabled=true,timeframes=['1m','5m','15m'],baselineWindow=60,minimumRelativeVolume=2,minimumZScore=3,now=Date.now}={}){this.id='volume-anomaly';this.version='1';Object.assign(this,{enabled,timeframes,baselineWindow,minimumRelativeVolume,minimumZScore,now});this.stats={evaluations:0,candidateEventsProduced:0,skippedWarmingUp:0,skippedUnhealthy:0,skippedInsufficientBaseline:0,skippedInvalidVolume:0,evaluationFailures:0,lastCandidateTimestamp:null,metricSourceCounts:{quoteVolume:0,baseVolume:0}}}
  evaluate({event,market,state,context={},now=this.now()}){if(!this.enabled||!this.timeframes.includes(event.timeframe))return[];if(state.dataQuality==='WARMING_UP'){this.stats.skippedWarmingUp++;return[]}if(state.dataQuality!=='COMPLETE'){this.stats.skippedUnhealthy++;return[]}this.stats.evaluations++;try{const baseline=volumeBaseline(state.candles,event,{window:this.baselineWindow});if(baseline.status==='INSUFFICIENT_HISTORY'){this.stats.skippedInsufficientBaseline++;return[]}if(baseline.status!=='READY'){this.stats.skippedInvalidVolume++;return[]}this.stats.metricSourceCounts[baseline.source]++;const relativeVolume=baseline.currentValue/baseline.mean,deviationFloor=Math.max(Math.abs(baseline.mean)*1e-9,Number.EPSILON),deviationZScore=(baseline.currentValue-baseline.mean)/Math.max(baseline.standardDeviation,deviationFloor);if(relativeVolume<this.minimumRelativeVolume||deviationZScore<this.minimumZScore)return[];const candidate=createCandidateEvent({detectorId:this.id,detectorVersion:this.version,eventType:'VOLUME_ANOMALY',market:{marketId:market.marketId,exchange:market.exchange,marketType:market.marketType,symbol:market.symbol,baseAsset:market.baseAsset,quoteAsset:market.quoteAsset},timeframe:event.timeframe,eventTimestamp:event.openTime,observedAt:event.receivedAt,metrics:{price:event.close,volume:baseline.currentValue,relativeVolume,deviationZScore},evidence:['ABOVE_NORMAL_VOLUME','EXTREME_RELATIVE_VOLUME','VOLUME_DISTRIBUTION_OUTLIER'],confirmationFactors:[],metadata:{warmupStatus:'READY',dataQuality:state.dataQuality,sourceCoverage:['closed-candles',baseline.source],volumeMetric:baseline.source,baselineWindow:this.baselineWindow,processingTimings:{closedCandleReceivedAt:context.closedCandleReceivedAt||event.receivedAt,stateUpdatedAt:context.stateUpdatedAt||null,baselineCalculatedAt:now,detectorEvaluatedAt:now}}},{now});this.stats.candidateEventsProduced++;this.stats.lastCandidateTimestamp=now;return[candidate]}catch(error){this.stats.evaluationFailures++;throw error}}
  diagnostics(){return{detectorId:this.id,detectorVersion:this.version,enabled:this.enabled,timeframes:[...this.timeframes],...this.stats}}
}
module.exports={VolumeAnomalyDetector};
