(function(global){
  'use strict';
  const STORAGE_KEY='zych.language.v1',SUPPORTED=Object.freeze(['en','ru']),messages={
    en:{'nav.markets':'Markets','nav.watchlist':'Watchlist','nav.radar':'Radar','radar.marketTitle':'Market Radar','radar.tagline':'ZYCH detects unusual market activity.','common.retry':'Retry','common.settings':'Settings','common.system':'System','search.label':'Global symbol search','search.placeholder':'Search markets…','search.loading':'Loading market universe…','search.unavailable':'Market catalog unavailable','search.noResults':'No markets found','search.empty':'Type a symbol to search all exchanges','search.sort':'Market sorting','market.spot':'Spot','market.perpetual':'Perpetual','market.high':'High','market.low':'Low','market.volume':'Volume','market.indicators':'Indicators','watchlist.title':'Watchlist','watchlist.asset':'Asset','watchlist.last':'Last','watchlist.change':'Chg%','watchlist.empty':'Watchlist is empty','watchlist.find':'Find a market','radar.title':'Radar','radar.preparing':'Radar is being prepared','radar.description':'Market events will appear here when the Radar Engine is ready.','settings.language':'Language','alert.create':'Create Alert','connection.loading':'Loading market data…','connection.connecting':'Connecting','connection.live':'Live','connection.offline':'Offline','connection.reconnecting':'Reconnecting','connection.liveData':'live market data','connection.streamUnavailable':'Live stream unavailable','connection.connectingTo':'Connecting to'},
    ru:{'nav.markets':'Рынки','nav.watchlist':'Избранное','nav.radar':'Радар','radar.marketTitle':'Рыночный радар','radar.tagline':'ZYCH обнаруживает необычную рыночную активность.','common.retry':'Повторить','common.settings':'Настройки','common.system':'Системный','search.label':'Глобальный поиск инструментов','search.placeholder':'Поиск рынков…','search.loading':'Загрузка списка рынков…','search.unavailable':'Каталог рынков недоступен','search.noResults':'Рынки не найдены','search.empty':'Введите символ для поиска на всех биржах','search.sort':'Сортировка рынков','market.spot':'Спот','market.perpetual':'Бессрочный','market.high':'Макс.','market.low':'Мин.','market.volume':'Объём','market.indicators':'Индикаторы','watchlist.title':'Избранное','watchlist.asset':'Актив','watchlist.last':'Цена','watchlist.change':'Изм.%','watchlist.empty':'Список пуст','watchlist.find':'Найти рынок','radar.title':'Радар','radar.preparing':'Радар готовится','radar.description':'Рыночные события появятся здесь после запуска Radar Engine.','settings.language':'Язык','alert.create':'Создать алерт','connection.loading':'Загрузка рыночных данных…','connection.connecting':'Подключение','connection.live':'Онлайн','connection.offline':'Офлайн','connection.reconnecting':'Переподключение','connection.liveData':'рыночные данные онлайн','connection.streamUnavailable':'Поток данных недоступен','connection.connectingTo':'Подключение к'}
  };
  messages.en['search.topMatches']='TOP MATCHES';messages.en['search.otherMarkets']='OTHER MARKETS';messages.ru['search.topMatches']='ЛУЧШИЕ СОВПАДЕНИЯ';messages.ru['search.otherMarkets']='ДРУГИЕ РЫНКИ';
  messages.en['connection.subscribing']='Subscribing';messages.ru['connection.subscribing']='Подписка';
  Object.assign(messages.en,{'nav.chart':'Chart','nav.primary':'Primary navigation','common.login':'Login'});
  Object.assign(messages.ru,{'nav.chart':'График','nav.primary':'Основная навигация','common.login':'Войти'});
  Object.assign(messages.en,{
    'common.unavailable':'Unavailable','radar.taglineFull':'ZYCH detects unusual market activity in real time.','radar.preparingShort':'Preparing','radar.engine':'Radar Engine','radar.status':'Status','radar.engineDescription':'The engine is being prepared to detect unusual market activity.','radar.eventsWhenReady':'Events will appear when verified Radar data is available.','radar.signalInputs':'Signal inputs','radar.metrics':'Radar metrics','radar.events':'Radar Events','radar.highScore':'High Score','radar.dataQuality':'Data Quality','radar.awaitingData':'Awaiting verified data','radar.marketMode':'Market Mode','radar.instruments':'instruments','radar.activeAlerts':'Active Alerts','radar.alerts':'alerts','radar.eventsToday':'Radar Events Today','radar.eventsHour':'Events This Hour','radar.lastUpdate':'Last Update','radar.autoRefresh':'Auto Refresh','radar.topOpportunities':'Top Radar Opportunities','radar.filters':'Radar filters','filter.all':'All','filter.volume':'Volume','filter.exchange':'Exchange','filter.allExchanges':'All Exchanges','table.symbol':'Symbol','table.exchange':'Exchange','table.reason':'Reason','table.change24h':'24h Change','table.volume24h':'Volume (24h)','table.action':'Action','radar.opportunitiesPreparing':'Radar opportunities are being prepared','radar.noFabricatedData':'Verified events will appear here without illustrative or estimated values.','radar.quickAlert':'Quick Alert','radar.recentEvents':'Recent Radar Events','radar.eventsPreparing':'Radar events are being prepared','radar.eventFeedDescription':'The chronological event feed will appear when verified events are available.','radar.awaitingEngine':'Awaiting Radar Engine','radar.marketSentiment':'Market Sentiment','radar.fearGreed':'Fear & Greed Index','radar.altseason':'Altseason Index','radar.marketTrend':'Market Trend (7D)','radar.heatmap':'Heatmap (Top 20)','radar.sourceNotConnected':'Verified source not connected.','radar.trendSourceNotConnected':'Verified trend source not connected.','radar.heatmapUnavailable':'Market heatmap requires verified context data.','radar.verifiedSources':'Verified sources only'
  });
  Object.assign(messages.ru,{
    'common.unavailable':'Недоступно','radar.taglineFull':'ZYCH обнаруживает необычную рыночную активность в реальном времени.','radar.preparingShort':'Подготовка','radar.engine':'Radar Engine','radar.status':'Статус','radar.engineDescription':'Система готовится к обнаружению необычной рыночной активности.','radar.eventsWhenReady':'События появятся после подключения проверенных данных Radar.','radar.signalInputs':'Входные сигналы','radar.metrics':'Метрики Radar','radar.events':'События Radar','radar.highScore':'Высший балл','radar.dataQuality':'Качество данных','radar.awaitingData':'Ожидание проверенных данных','radar.marketMode':'Режим рынка','radar.instruments':'инструментов','radar.activeAlerts':'Активные алерты','radar.alerts':'алертов','radar.eventsToday':'События Radar сегодня','radar.eventsHour':'События за час','radar.lastUpdate':'Последнее обновление','radar.autoRefresh':'Автообновление','radar.topOpportunities':'Лучшие возможности Radar','radar.filters':'Фильтры Radar','filter.all':'Все','filter.volume':'Объём','filter.exchange':'Биржа','filter.allExchanges':'Все биржи','table.symbol':'Инструмент','table.exchange':'Биржа','table.reason':'Причина','table.change24h':'Изм. 24ч','table.volume24h':'Объём (24ч)','table.action':'Действие','radar.opportunitiesPreparing':'Возможности Radar готовятся','radar.noFabricatedData':'Проверенные события появятся без иллюстративных или расчётных значений.','radar.quickAlert':'Быстрый алерт','radar.recentEvents':'Последние события Radar','radar.eventsPreparing':'События Radar готовятся','radar.eventFeedDescription':'Хронологическая лента появится после получения проверенных событий.','radar.awaitingEngine':'Ожидание Radar Engine','radar.marketSentiment':'Настроение рынка','radar.fearGreed':'Индекс страха и жадности','radar.altseason':'Индекс альтсезона','radar.marketTrend':'Тренд рынка (7д)','radar.heatmap':'Тепловая карта (топ-20)','radar.sourceNotConnected':'Проверенный источник не подключён.','radar.trendSourceNotConnected':'Проверенный источник тренда не подключён.','radar.heatmapUnavailable':'Для тепловой карты нужны проверенные контекстные данные.','radar.verifiedSources':'Только проверенные источники'
  });
  Object.assign(messages.en,{
    'chart.quickAlert':'Quick Alert','chart.trade':'Trade','chart.scoreUnavailable':'Score unavailable','chart.noRadarEvent':'No verified Radar event','chart.templates':'Templates','chart.alertLines':'Alert Lines','chart.automatic':'Automatic','chart.drawing':'Drawing','chart.hotkeyHint':'Hotkeys: type 15 + Enter for 15m','chart.orderBook':'Order Book','chart.trades':'Trades','chart.orderBookUnavailable':'Order book unavailable','chart.verifiedOnly':'A verified live feed is required.','chart.marketInfo':'Market Info','chart.baseCurrency':'Base Currency','chart.quoteCurrency':'Quote Currency','chart.relatedMarkets':'Related Markets','chart.openAlerts':'Open Alerts','chart.recentAlerts':'Recent Alerts','chart.notes':'Notes','chart.notesPlaceholder':'Notes for this market…','chart.performance':'Performance','chart.performanceUnavailable':'Performance unavailable','chart.hideBottom':'Hide bottom panel','chart.showBottom':'Show bottom panel','chart.noOpenAlerts':'No open alerts for this market','chart.noRecentAlerts':'No triggered alerts for this market','chart.notesSaved':'Saved locally','chart.relatedUnavailable':'No related verified markets'
  });
  Object.assign(messages.ru,{
    'chart.quickAlert':'Быстрый алерт','chart.trade':'Торговать','chart.scoreUnavailable':'Оценка недоступна','chart.noRadarEvent':'Нет проверенного события Radar','chart.templates':'Шаблоны','chart.alertLines':'Линии алертов','chart.automatic':'Автоматически','chart.drawing':'Рисование','chart.hotkeyHint':'Горячие клавиши: 15 + Enter для 15м','chart.orderBook':'Книга ордеров','chart.trades':'Сделки','chart.orderBookUnavailable':'Книга ордеров недоступна','chart.verifiedOnly':'Требуется проверенный поток данных.','chart.marketInfo':'Информация о рынке','chart.baseCurrency':'Базовая валюта','chart.quoteCurrency':'Валюта котировки','chart.relatedMarkets':'Связанные рынки','chart.openAlerts':'Открытые алерты','chart.recentAlerts':'Последние алерты','chart.notes':'Заметки','chart.notesPlaceholder':'Заметки для этого рынка…','chart.performance':'Доходность','chart.performanceUnavailable':'Доходность недоступна','chart.hideBottom':'Скрыть нижнюю панель','chart.showBottom':'Показать нижнюю панель','chart.noOpenAlerts':'Нет открытых алертов для этого рынка','chart.noRecentAlerts':'Нет сработавших алертов для этого рынка','chart.notesSaved':'Сохранено локально','chart.relatedUnavailable':'Нет связанных проверенных рынков'
  });
  Object.assign(messages.en,{
    'watchlist.subtitle':'Track your favorite markets and spot opportunities in real time.','watchlist.addSymbol':'Add Symbol','watchlist.import':'Import','watchlist.more':'More Watchlist actions','watchlist.summary':'Watchlist summary','watchlist.totalInstruments':'Total Instruments','watchlist.gainers24h':'Gainers (24h)','watchlist.losers24h':'Losers (24h)','watchlist.alertsActive':'Alerts Active','watchlist.radarEvents':'Radar Events','watchlist.radarEvent':'Radar Event','watchlist.lastUpdate':'Last Update','watchlist.controls':'Watchlist controls','watchlist.allSectors':'All Sectors','watchlist.columns':'Columns','watchlist.sort':'Sort Watchlist','watchlist.sortDefault':'Sort: Default','watchlist.sortGainers':'Sort: Gainers','watchlist.sortLosers':'Sort: Losers','watchlist.view':'Watchlist view','watchlist.tableView':'Table View','watchlist.tileView':'Compact Tile View','watchlist.marketType':'Market Type','watchlist.price':'Price','watchlist.highLow':'24h High / Low','watchlist.marketCap':'Market Cap','watchlist.sector':'Sector','watchlist.actions':'Actions','watchlist.personalizedRadar':'Personalized Radar workspace','watchlist.noEvent':'No event','watchlist.sparklineUnavailable':'Sparkline unavailable','watchlist.remove':'Remove from Watchlist','watchlist.openChart':'Open Chart','watchlist.quickAlert':'Quick Alert','watchlist.showing':'Showing {shown} of {total} instruments','watchlist.importTitle':'Import Watchlist','watchlist.importDescription':'Import support for external formats is being prepared.','watchlist.importPreparing':'Import is preparing','watchlist.importNoFake':'No file will be processed until a verified importer is available.','common.close':'Close'
  });
  Object.assign(messages.ru,{
    'watchlist.subtitle':'Следите за избранными рынками и находите возможности в реальном времени.','watchlist.addSymbol':'Добавить символ','watchlist.import':'Импорт','watchlist.more':'Другие действия списка','watchlist.summary':'Сводка списка наблюдения','watchlist.totalInstruments':'Всего инструментов','watchlist.gainers24h':'Растущие (24ч)','watchlist.losers24h':'Падающие (24ч)','watchlist.alertsActive':'Активные алерты','watchlist.radarEvents':'События Radar','watchlist.radarEvent':'Событие Radar','watchlist.lastUpdate':'Последнее обновление','watchlist.controls':'Управление списком','watchlist.allSectors':'Все секторы','watchlist.columns':'Колонки','watchlist.sort':'Сортировка списка','watchlist.sortDefault':'Сортировка: по умолчанию','watchlist.sortGainers':'Сортировка: рост','watchlist.sortLosers':'Сортировка: падение','watchlist.view':'Вид списка','watchlist.tableView':'Табличный вид','watchlist.tileView':'Компактные плитки','watchlist.marketType':'Тип рынка','watchlist.price':'Цена','watchlist.highLow':'Макс. / мин. 24ч','watchlist.marketCap':'Капитализация','watchlist.sector':'Сектор','watchlist.actions':'Действия','watchlist.personalizedRadar':'Персональная рабочая область Radar','watchlist.noEvent':'Нет события','watchlist.sparklineUnavailable':'График недоступен','watchlist.remove':'Удалить из списка','watchlist.openChart':'Открыть график','watchlist.quickAlert':'Быстрый алерт','watchlist.showing':'Показано {shown} из {total} инструментов','watchlist.importTitle':'Импорт списка','watchlist.importDescription':'Поддержка внешних форматов готовится.','watchlist.importPreparing':'Импорт готовится','watchlist.importNoFake':'Файлы не обрабатываются до появления проверенного импортера.','common.close':'Закрыть'
  });
  Object.assign(messages.en,{'watchlist.catalogLoading':'Loading catalog','watchlist.quotesLoading':'Loading quotes','watchlist.catalogError':'Catalog load failed','watchlist.quotesError':'Quote load failed','watchlist.notFound':'Pair not found in catalog','watchlist.quotesUnavailable':'Quotes unavailable'});
  Object.assign(messages.ru,{'watchlist.catalogLoading':'Загрузка каталога','watchlist.quotesLoading':'Загрузка котировок','watchlist.catalogError':'Ошибка загрузки каталога','watchlist.quotesError':'Ошибка загрузки котировок','watchlist.notFound':'Пара не найдена в каталоге','watchlist.quotesUnavailable':'Котировки недоступны'});
  Object.assign(messages.en,{'markets.coverage':'Prices {prices}/{total} · Verified 24h change {changes}/{total}','markets.partialCoverage':'Partial · coverage {count}/{total}','markets.metricCoverage':'Coverage {count}/{total}','markets.loadingPartial':'Loading · partial data','markets.partialError':'Collection error · available data only','markets.partialData':'Partial data','markets.dataReceived':'Available price and change data received'});
  Object.assign(messages.ru,{'markets.coverage':'Цены {prices}/{total} · Подтверждённое изменение 24ч {changes}/{total}','markets.partialCoverage':'Частично · охват {count}/{total}','markets.metricCoverage':'Охват {count}/{total}','markets.loadingPartial':'Загрузка · частичные данные','markets.partialError':'Ошибка сбора · только доступные данные','markets.partialData':'Частичные данные','markets.dataReceived':'Доступные цены и изменения получены'});
  messages.en['alert.serviceUnavailable']='Alert service unavailable';messages.ru['alert.serviceUnavailable']='Сервис алертов недоступен';
  Object.assign(messages.en,{'reliability.lastData':'Last data:','reliability.noData':'Last data: —','reliability.ago':'ago','reliability.waiting':'Waiting','reliability.statusUnavailable':'Status unavailable'});
  Object.assign(messages.ru,{'reliability.lastData':'Последние данные:','reliability.noData':'Последние данные: —','reliability.ago':'назад','reliability.waiting':'Ожидание','reliability.statusUnavailable':'Статус недоступен'});
  const storage=()=>{try{return global.localStorage}catch{return null}},resolveLocale=value=>{const locale=String(value||'').toLowerCase().split('-')[0];return SUPPORTED.includes(locale)?locale:'en'},systemLocale=()=>resolveLocale(global.navigator?.language);
  let preference='system',active='en';
  function load(){try{const value=storage()?.getItem(STORAGE_KEY);preference=value==='en'||value==='ru'?value:'system'}catch{preference='system'}active=preference==='system'?systemLocale():preference;return active}
  function t(key){return messages[active]?.[key]??messages.en[key]??key}
  function apply(root=global.document){if(!root)return;root.documentElement?.setAttribute('lang',active);root.querySelectorAll?.('[data-i18n]').forEach(node=>node.textContent=t(node.dataset.i18n));root.querySelectorAll?.('[data-i18n-placeholder]').forEach(node=>node.setAttribute('placeholder',t(node.dataset.i18nPlaceholder)));root.querySelectorAll?.('[data-i18n-aria]').forEach(node=>node.setAttribute('aria-label',t(node.dataset.i18nAria)))}
  function setPreference(value){preference=value==='en'||value==='ru'?value:'system';try{storage()?.setItem(STORAGE_KEY,preference)}catch{}active=preference==='system'?systemLocale():preference;apply();global.dispatchEvent?.(new CustomEvent('zych:languagechange',{detail:{locale:active,preference}}));return active}
  function locale(){return active==='ru'?'ru-RU':'en-US'}
  load();const api={STORAGE_KEY,SUPPORTED,messages,resolveLocale,t,apply,load,setPreference,preference:()=>preference,locale};if(typeof module==='object'&&module.exports)module.exports=api;else global.ZychI18n=api;
})(typeof window!=='undefined'?window:globalThis);
