(function(global){
  'use strict';
  const exchanges=new Set(['binance','bybit','okx','bingx']),marketTypes=new Set(['spot','perpetual']),safe=value=>typeof value==='string'&&/^[A-Za-z0-9:_-]{1,120}$/.test(value),timeframe=value=>value==null||/^(1|3|5|15|30)m$|^(1|2|4|6|8|12)h$|^1d$|^1w$|^1M$/.test(value),stamp=value=>Number.isFinite(Number(value))&&Number(value)>0,numeric=value=>value!=null&&value!==''&&Number.isFinite(Number(value)),text=value=>typeof value==='string'?value:null;
  const freeze=value=>{if(value&&typeof value==='object'&&!Object.isFrozen(value)){Object.values(value).forEach(freeze);Object.freeze(value)}return value};
  function identity(value){if(!value||!exchanges.has(value.exchange)||!marketTypes.has(value.marketType)||!safe(value.symbol))return null;const marketId=`${value.exchange}:${value.marketType}:${value.symbol}`;return value.marketId===marketId?marketId:null}
  function create(value){const market=value?.market,deepLink=value?.deepLink,marketId=identity(market),deepMarketId=identity(deepLink);if(!safe(value?.eventId)||!marketId||deepMarketId!==marketId||!safe(market.baseAsset)||!safe(market.quoteAsset)||!timeframe(value.timeframe)||!timeframe(deepLink.timeframe)||deepLink.timeframe!==value.timeframe||!stamp(value.eventTimestamp)||!stamp(value.observedAt)||!stamp(value.createdAt))return null;const linkTimestamp=deepLink.eventTimestamp==null?null:Number(deepLink.eventTimestamp);if(linkTimestamp!==null&&(!stamp(linkTimestamp)||linkTimestamp!==Number(value.eventTimestamp)))return null;const metrics=value.metrics&&typeof value.metrics==='object'?value.metrics:{},score=value.score&&typeof value.score==='object'?value.score:{},interpretation=value.interpretation&&typeof value.interpretation==='object'?value.interpretation:{},context=value.marketContext&&typeof value.marketContext==='object'?structuredClone(value.marketContext):null;return freeze({eventId:value.eventId,marketId,exchange:market.exchange,marketType:market.marketType,symbol:market.symbol,baseAsset:market.baseAsset,quoteAsset:market.quoteAsset,timeframe:value.timeframe,eventTimestamp:Number(value.eventTimestamp),observedAt:Number(value.observedAt),createdAt:Number(value.createdAt),setupType:text(value.setupType),direction:text(value.direction),interpretationLabel:text(interpretation.label),interpretationSummary:text(interpretation.summary),score:numeric(score.value)?Number(score.value):null,scoreQuality:text(score.quality),price:numeric(metrics.price)?Number(metrics.price):null,eventChangePct:numeric(metrics.priceChangePct)?Number(metrics.priceChangePct):null,eventVolume:numeric(metrics.volume)?Number(metrics.volume):null,relativeVolume:numeric(metrics.relativeVolume)?Number(metrics.relativeVolume):null,dataQuality:text(context?.breadth?.dataQuality),context,deepLink:{marketId,exchange:deepLink.exchange,marketType:deepLink.marketType,symbol:deepLink.symbol,timeframe:deepLink.timeframe||null,eventTimestamp:linkTimestamp}})}
  function filter(events,{anomaly='all',exchange='all'}={}){const types={momentum:new Set(['MOMENTUM','MOMENTUM_WITH_VOLUME_CONFIRMATION']),volume:new Set(['VOLUME_EXPANSION','MOMENTUM_WITH_VOLUME_CONFIRMATION'])};return(events||[]).filter(event=>(exchange==='all'||event.exchange===exchange)&&(anomaly==='all'||types[anomaly]?.has(event.setupType)))}
  function status(state={}){if(state.error)return{code:state.lastSuccessfulFetch?'STALE':'OFFLINE',label:state.lastSuccessfulFetch?'Stale data':'Radar unavailable'};if(state.loading&&!state.lastSuccessfulFetch)return{code:'LOADING',label:'Loading'};const meta=state.meta||{},reasons=meta.reasonCodes||[],coverage=meta.coverage||{};if(meta.lifecycle==='WARMING_UP'||reasons.includes('RADAR_WARMING_UP'))return{code:'WARMING_UP',label:'Warming up'};if(reasons.includes('HEALTHY_PROCESSING_STALE'))return{code:'STALE',label:'Stale data'};if(coverage.status==='DEGRADED'||(coverage.expectedExchanges?.length&&coverage.healthyExchanges?.length<coverage.expectedExchanges.length))return{code:'PARTIAL',label:'Partial data'};if(meta.lifecycle==='READY'&&!(state.events||[]).length)return{code:'EMPTY',label:'No qualified events yet'};if(meta.lifecycle==='READY')return{code:'READY',label:'Live'};if(meta.lifecycle==='DEGRADED')return{code:'DEGRADED',label:'Degraded'};return{code:'OFFLINE',label:'Radar unavailable'}}
  function resolveSelection(event,markets,{supportedTimeframes=[],currentTimeframe=null}={}){const link=event?.deepLink,marketId=identity(link);if(!marketId||marketId!==event?.marketId||link.exchange!==event.exchange||link.marketType!==event.marketType||link.symbol!==event.symbol)return{error:'INVALID_DEEP_LINK',market:null,context:null};const market=(markets||[]).find(item=>item.enabled&&item.id===marketId&&item.exchange===link.exchange&&item.marketType===link.marketType&&item.symbol===link.symbol)||null;if(!market)return{error:'MARKET_NOT_FOUND',market:null,context:null};const timeframe=supportedTimeframes.includes(link.timeframe)?link.timeframe:currentTimeframe;return{error:null,market,context:{marketId,exchange:link.exchange,marketType:link.marketType,symbol:link.symbol,timeframe,eventTimestamp:link.eventTimestamp}}}
  class Feed{
    constructor({fetchImpl=globalThis.fetch,intervalMs=10000,now=Date.now,onChange=()=>{},setTimer=setTimeout,clearTimer=clearTimeout}={}){Object.assign(this,{fetchImpl:fetchImpl.bind(globalThis),intervalMs,now,onChange,setTimer:setTimer.bind(globalThis),clearTimer:clearTimer.bind(globalThis)});this.state={events:[],meta:null,loading:true,lastSuccessfulFetch:null,error:null,filters:{anomaly:'all',exchange:'all'}};this.active=null;this.controller=null;this.timer=null;this.generation=0;this.running=false}
    notify(){this.onChange(this.state);return this.state}
    refresh(){if(this.active)return this.active;const generation=this.generation,controller=new AbortController();this.controller=controller;this.state={...this.state,loading:true};this.notify();const task=(async()=>{try{const response=await this.fetchImpl('/api/radar/events',{signal:controller.signal});if(!response.ok)throw new Error(`Radar request failed (${response.status})`);const payload=await response.json(),events=[...new Map((Array.isArray(payload.events)?payload.events:[]).map(create).filter(Boolean).map(event=>[event.eventId,event])).values()];if(generation!==this.generation)return this.state;this.state={...this.state,events,meta:payload.meta&&typeof payload.meta==='object'?payload.meta:null,loading:false,lastSuccessfulFetch:this.now(),error:null};return this.notify()}catch(error){if(generation!==this.generation||error.name==='AbortError')return this.state;this.state={...this.state,loading:false,error:error.message||'Radar unavailable'};return this.notify()}finally{if(this.active===task){this.active=null;this.controller=null}}})();this.active=task;return task}
    setFilters(filters){this.state={...this.state,filters:{...this.state.filters,...filters}};this.notify()}
    schedule(){this.clearTimer(this.timer);if(this.running)this.timer=this.setTimer(async()=>{await this.refresh();this.schedule()},this.intervalMs)}
    start(){if(this.running)return;this.running=true;this.refresh().finally(()=>this.schedule())}
    stop(){this.running=false;this.generation++;this.clearTimer(this.timer);this.timer=null;this.controller?.abort();this.controller=null;this.active=null}
  }
  const api={create,filter,status,resolveSelection,Feed};if(typeof module==='object'&&module.exports)module.exports=api;else global.ZychRadarEvent=api;
})(typeof window!=='undefined'?window:globalThis);
