(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ZychReliabilityUx=api})(typeof window!=='undefined'?window:globalThis,function(){
  'use strict';
  const STATE_LABELS=Object.freeze({LIVE:'LIVE',READY:'READY',FRESH:'FRESH',CONNECTING:'CONNECTING',SUBSCRIBING:'SUBSCRIBING',WAITING:'WAITING',WAITING_FOR_DATA:'WAITING FOR DATA',WAITING_FOR_BASELINE:'WAITING FOR BASELINE',RECONNECTING:'RECONNECTING',STALE:'STALE',PARTIAL:'PARTIAL',DEGRADED:'DEGRADED',OFFLINE:'OFFLINE',PAUSED:'PAUSED',UNSUPPORTED:'UNSUPPORTED',LIMITED:'LIMITED',RADAR_INELIGIBLE:'RADAR-INELIGIBLE',FAILED:'FAILED',CACHED:'CACHED',UNAVAILABLE:'UNAVAILABLE',UNKNOWN:'WAITING',DISABLED:'DISABLED',BLOCKED:'BLOCKED',SCHEDULED:'SCHEDULED',ACCEPTED:'ACCEPTED',PENDING:'PENDING'});
  const REASONS=Object.freeze({EXACT_LIQUIDITY_UNAVAILABLE:'Radar unavailable: exact liquidity source required',INTERVAL_UNSUPPORTED:'Interval unavailable on this exchange',UNSUPPORTED_INTERVAL:'Interval unavailable on this exchange',HISTORY_WINDOW_LIMITED:'This exchange provides a limited recent history window',HISTORY_LIMITED:'This exchange provides a limited recent history window',EXACT_QUOTE_VOLUME_UNAVAILABLE:'Volume alert unavailable on this exchange',MARKET_UNAVAILABLE:'Market not available on this exchange',BASELINE_UNPROVEN:'Waiting for enough baseline data',RUNNER_NOT_RUNNING:'Alert monitor is starting',CONNECTION_RECOVERING:'Market feed is reconnecting',ACQUISITION_STALE:'Last acquired data is stale',REFRESH_FAILED:'Refresh failed; retained values are shown',CACHE_HIT:'Cached values are shown',PERSISTENCE_FAILED:'Alert could not be saved',EVALUATION_FAILED:'Alert evaluation failed',TRANSPORT_FAILED:'Alert market feed failed',ALERT_INACTIVE:'Alert is paused'});
  function age(milliseconds){if(!Number.isFinite(milliseconds)||milliseconds<0)return null;const seconds=Math.floor(milliseconds/1000);if(seconds<2)return'now';if(seconds<60)return`${seconds}s`;const minutes=Math.floor(seconds/60);if(minutes<60)return`${minutes}m`;const hours=Math.floor(minutes/60);if(hours<24)return`${hours}h`;return`${Math.floor(hours/24)}d`}
  function ageAgo(milliseconds){const value=age(milliseconds);return value===null?null:value==='now'?'now':`${value} ago`}
  const label=state=>STATE_LABELS[String(state||'UNKNOWN').toUpperCase()]||'STATUS UNAVAILABLE';
  const reason=code=>REASONS[code]||null;
  function alertSummary(reliability={}){const counts=reliability.counts||{},supported=Math.max(0,Number(counts.total||0)-Number(counts.unsupported||0)),ready=Math.min(supported,Number(counts.ready||0));let state='WAITING';if(!supported)state=counts.total?'UNSUPPORTED':'WAITING';else if(ready===supported)state='READY';else if(Number(counts.failed||0))state=ready?'PARTIAL':'FAILED';else if(Number(counts.stale||0))state=ready?'PARTIAL':'STALE';else if(ready)state='PARTIAL';return{state,label:state==='READY'?'READY':state==='PARTIAL'?`PARTIAL · ${ready}/${supported} ready`:label(state),ready,supported,unsupported:Number(counts.unsupported||0)}}
  function alertDetail(alert,detail={}){const state=detail.state||(!alert||alert.status!=='active'?'PAUSED':'WAITING_FOR_DATA'),ageText=age(detail.lastMarketDataAgeMs),why=(detail.reasons||[]).map(reason).find(Boolean);return{state,label:label(state),age:ageText,ageLabel:ageAgo(detail.lastMarketDataAgeMs),reason:why,baseline:detail.baseline||null,lastEvaluationAt:detail.lastEvaluation?.at??detail.lastEvaluation?.timestamp??null}}
  function delivery(outcome={},push={}){return{alert:outcome.execution==='SUCCESS'?(outcome.trigger==='PERSISTED'?'TRIGGERED · PERSISTED':'TRIGGERED'):label(outcome.execution),push:outcome.push==='UNKNOWN'&&!push.pushEnabled?'NOT CONFIGURED':label(outcome.push),sound:label(outcome.sound==='UNKNOWN'?'DISABLED':outcome.sound)}}
  function radar(coverage={},quarantine=[]){const supported=Array.isArray(coverage.expectedExchanges)?coverage.expectedExchanges.length:0,healthy=Array.isArray(coverage.healthyExchanges)?coverage.healthyExchanges.length:0,state=supported&&healthy===supported?'READY':healthy?'PARTIAL':'OFFLINE';return{state,label:`${label(state)} · ${healthy}/${supported}`,healthy,supported,quarantined:Array.isArray(quarantine)?quarantine.length:Number(quarantine||0)}}
  return{age,ageAgo,label,reason,alertSummary,alertDetail,delivery,radar,STATE_LABELS,REASONS};
});
